### ISSUE TITLE
Mensagem de alerta sobre fontes com data mais recente ao aplicar patchs

### ISSUE THREAD

**Issue by IgorKbcao** [totvs/advpl-vscode#138]
Apliquei o patch de correção usando o IDE TDS e apareceu a mensagem que existe fontes no RPO com data mais recente que os fontes do Patch e com as opções de escolher (Todos ou Somente os mais Recentes), ao aplicar esse mesmo Patch pelo VsCode a mensagem não é apresentada.

**Comment by killerall** [comment]
De fato ele substitui.
Tem que implementar.

**Comment by lucasdittrich** [comment]
Existe alguma previsão para liberação dessa melhoria? Acredito que é uma funcionalidade do TDS extremamente importante e que falta no VSCode.

**Comment by edusfc15** [comment]
@killerall não tem como pelo menos enquanto não implementa a melhoria por completo, forçar para aplicar somente os mais recentes?

**Comment by robsonrosilva** [comment]
@killerall acho que seria bom poder configurar ou perguntar se quer aplicar todos ou somente os mais recentes. Tem previsão para essa implementação?

**Comment by killerall** [comment]
@robsonrosilva No momento o esforço esta no port para linux/mac.
Voltarei a ver a parte de path depois disso.

**Comment by rafaeldepaula5000** [comment]
Previsão?

**Comment by killerall** [comment]
Sem previsão ainda.

**Comment by renanconaut** [comment]
Rodrigo muito boa tarde,

Parabens pelo trabalho, esta muito melhor para trabalhar, mas esta feature realmente é muito importante para abandonarmos de vez as demais IDE's. Sei que tempo é precioso e escaso, mas olhe com carinho para esta funcionalidade.

Abraços.

**Comment by williankaneta** [comment]
Bom dia, 
alguma previsão ?

**Comment by robsonrosilva** [comment]
Isso já foi implementado.
https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs#somente-atualizados

**Comment by killerall** [comment]
Implementado na versão 0.14.2.
