### ISSUE TITLE
Protheus cai quando está sendo executado via VSCODE

### ISSUE THREAD

**Issue by kleestadt** [totvs/advpl-vscode#144]
Bom dia, 

Alguém já teve esse problema?

O protheus "cai" depois de um período de inatividade quando esta rodando via VSCODE (F5 ou Ctrl + F5)

![image](https://user-images.githubusercontent.com/29710136/33212373-e6cf90c2-d109-11e7-8fea-6d51d50800ac.png)

**Comment by killerall** [comment]
O AppServer as vezes dropa mesmo a conexao depois de um tempo.
Existe uma chave no server se não me engano de inactiveTimeout, 
Não sei no seu caso foi isso, mais ja cheguei a deixar mais de 1 hora parado em breakpoint e segura normal.

Se você conseguir reproduzir sempre, coloque um passo a passo, aqui por favor.

**Comment by kleestadt** [comment]
Bom dia Rodrigo, obrigado pelo retorno,

Só encontrei essa tag no appserver.ini na sessão da img anexo, seria esse que você comentou?

![image](https://user-images.githubusercontent.com/29710136/33759318-0a6feb3c-dbe9-11e7-8ff6-3e3904bbc8da.png)

**Comment by killerall** [comment]
Essa chave que mostrou é do WS, não iria interferir.
Ao menos que ela estive-se no general, conforme a doc:
http://tdn.totvs.com.br/display/tec/InactiveTimeOut+--+29311
