### ISSUE TITLE
Erro ao tentar aplicar Patch

### ISSUE THREAD

**Issue by DiegoSantos90** [totvs/advpl-vscode#152]
Estou tentando aplicar uma patch, e ao utilizar o F1 Advpl - Patch - Apply recebo a seguinte mensagem:

![erro-ao-tentar-aplicar-patch](https://user-images.githubusercontent.com/24779908/33957324-758c4f30-e028-11e7-94c0-cc69ab3a4e4a.JPG)

**Comment by Verdao90** [comment]
Precisa copiar a patch para o explorer do VsCode para aplicar clicando com o botão direito no Patch
