### ISSUE TITLE
Configuração "apenas fontes atualizados" aplicação patch

### ISSUE THREAD

**Issue by marcelosecate** [totvs/advpl-vscode#227]
Qual a configuração, para que na aplicação do patch reconhecer apenas fontes novos ou atualizados?

**Comment by killerall** [comment]
Hoje não existe.

**Comment by killerall** [comment]
Precisa ser feito, mais hoje não esta com prioridade.

**Comment by tembra** [comment]
@killerall Qual é a tratativa padrão do plugin? Aplicar como *Somente atualizados* ou *Todos os fontes*?

Outra dúvida que tenho diz respeito sobre a forma de aplicação do patch. Como o plugin exige apenas o caminho da pasta do Smartclient e a existência do executável *appre.exe* o mesmo deve utilizar o mesmo método de compilação e aplicação de patches que o DevStudio, correto?

Acontece que já tive problemas com alguns patches liberados pela TOTVS onde aplicando pelo DevStudio o mesmo não funcionava. Depois de algumas horas tentando desvendar o problema resolvi aplicar pelo TDS para testar e, _não_ para minha surpresa, funcionou! Desde então utilizo apenas o TDS para aplicação de patches.

Você tem alguma informação a respeito deste meu relato?

Hoje meu ambiente de desenvolvimento se baseia no _Sublime Text 3_ com uma _build_ que utiliza o TDS Linha de Comando (tdscli) para compilação de fontes. Entretanto na aplicação de patches e realização de debugs uso o próprio TDS, apesar do primeiro também ser suportado pelo _tdscli_.

Como estou migrando para o VS Code por trabalhar com desenvolvimento web gostaria de utilizá-lo também para o ADVPL, ainda mais devido ao mesmo não necessitar do TDS instalado para compilação e debug.

**Comment by killerall** [comment]
@tembra 
Ele atualiza sempre Todos os fontes.

O DEVStudio foi descontinuado até onde sei, e os appsrv novos não permitem a conexão entre ele e Devstudio.
O suporte do Advpl no vscode escrevi do zero, utilizando a api do appsrv disponível para compilar, debugar e aplicar e gerar path.

**Comment by tembra** [comment]
@killerall IMHO, acredito que a opção default deveria ser "Somente os atualizados" para não gerar maiores problemas.

O DevStudio ainda conecta com o último AppServer disponibilizado para download no site da TOTVS. Mas realmente é muito provável que esta compatibilidade deixe de existir com o lançamento do AppServer Lobo-Guará, afinal ele pode ser considerado um divisor de águas e a TOTVS já vem avisando a algum tempo que tiraria esta comunicação, inclusive com mensagens durante a abertura do DevStudio.

Como você citou ali em cima que não está na lista de prioridades esta funcionalidade, pensei em contribuir para o projeto enviando um PR. Entretanto verifiquei que você utiliza um _Bridge_ o qual não possui o código fonte no projeto. Neste caso o _Bridge_ deve suportar esta opção.

Para obter todos os fontes do RPO você utiliza o argumento `--getMap` no _Bridge_. Este argumento é apenas do tipo true/false ou está pronto para receber um valor, como por exemplo, quais funções quero obter os dados do RPO?

A ideia seria executar o `--patchInfo` seguido do `--getMap`, onde neste último buscaria apenas pelos fontes retornados no primeiro. Então faria a comparação se existirem fontes mais novos no RPO e deixando o usuário realizar a escolha através do prompt. No final o `--patchApply` teria também que ser modificado para suportar um novo argumento.

Você pretende disponibilizar o código-fonte do _Bridge_ ou de nada adiantaria uma vez que não temos conhecimento da API de comunicação do AppServer ?

**Comment by killerall** [comment]
@tembra 
O desenvolvimento da extensão nunca teve a intenção de substitur como um todo o TDS, concordo que para aplicação de path em ambiente de produção seria mais correrto mesmo somente os atualizados.
Porem como o foco sempre foi o desenvolvedor aqui, e não o administrador do sistema, eu tomei esse rumo.
Sobre contribuir nesse ponto em especifico, acho que não é necessario fazer toda essa volta, para implementar isso. Principalmente no que bridge.
A parte mais trabalhosa e configurar tudo isso na extensão em typescript mesmo, dando opção de cada coisa.
(Caso queira-se fazer igual ao TDS, ao aplicar e der divergencia).
Se tiver interesse em fazer a parte em ts, posso ver como alterar o bridge.
[]s

**Comment by tembra** [comment]
@killerall Entendo, compreendo e concordo com o objetivo. 😄 

Entretanto sempre "nas pontas" os desenvolvedores são os administradores também hehehe.

Como você disse, e eu também citei na minha resposta, se podermos mudar o _Bridge_ fica bem mais tranquilo fazer o TS se adaptar a ele.

Dito isto, posso fazer sim a mudança no TS. Basta você modificar o _Bridge_ para tal ação.

Segue abaixo minha sugestão:

- Criar uma configuração opcional `advpl.patchApplyType` com os valores possíveis `all` e `newest`.
- Se esta configuração estiver presente o _Bridge_ não fará nenhuma verificação e o TS não exibirá nenhum prompt. Ou seja, será forçado o modo escolhido: _Todos os fontes_ ou _Somente atualizados_, respectivamente.
- Se a configuração acima não existir o _Bridge_ irá verificar as divergências e caso existam retorná-las. Caso não existam o patch será aplicado normalmente.
- Se existirem divergências o TS irá exibir ao usuário e solicitar a ação a ser tomada por meio de prompt: Aplicar _Todos os fontes_ ou _Somente atualizados_.
- Será chamado novamente a rotina de aplicação de patch, mas agora passando o argumento `--patchApplyType=` com um dos valores possíveis (`all`/`newest`) conforme escolha do usuário.

Resumindo, o _Bridge_ irá forçar a aplicação do patch da forma escolhida, seja devido a configuração do `advpl.patchApplyType` no ambiente ou devido ao argumento  `--patchApplyType=` ter sido passado a ele diretamente. Caso contrário ele deverá fazer a análise das divergências e, se encontrar, retorná-las.

Me diga o que acha deste processo.

**Comment by cmgalves** [comment]
Bom dia, apesar deste assunte ser um pouco antigo, gostaria de colocar a minha dúvida:

Hoje, na aplicação das patches, só aplica os fontes mais atuais?

Grato.

**Comment by killerall** [comment]
Bom dia,
Não, ele continua aplicando todos os fontes.

**Comment by tembra** [comment]
@killerall se você conseguir mudar o _Bridge_ para retornar a lista de divergências, e também para aceitar o parâmetro `--patchApplyType` conforme descrito acima, eu faço as modificações no TS.

**Comment by keinou** [comment]
Alguma previsão para este?

**Comment by killerall** [comment]
Por enquanto não.

**Comment by killerall** [comment]
Implementado e liberado na versão 0.14.2
