### ISSUE TITLE
Erro ao tentar executar o Fonte

### ISSUE THREAD

**Issue by W1ll14nC4rl0s** [totvs/advpl-vscode#270]
Compilei o fonte verifiquei no Inspetor de Objeto e de fato compilou porem quando dou F5 e digito u_VsCode e pressiono enter nada acontece 
minhas configurações
`
  "editor.fontSize": 13,
    "files.encoding": "windows1252",
    //ambientes
    "advpl.environments": [

        {
            "name": "TESTE",
            "smartClientPath": "C://Totvs//Teste//smartclient//",
            "environment": "RAZNVN_TESTE",
            "serverVersion": "131227A",
            "server": "192.168.0.189",
            "port": "54510",
            "user": "ADMIN",
            "passwordCipher": "dkQ5Q0taNUxsNmVzQUQ5SGF0aW5TT1RVT3M3Tjh5S0lqS2pMYU5YQitBL2hob21JY3N3MkMvRmZWd1Z2ejNVSFNIRlJsZ3dBb1g3aGtQR2ZldGVqbW8yUUZabjc4ZWpuYjFBa2ZNSGdORUN5a0REVnpMRXNjTjNJUWpBUlgrY0c=",
            "includeList": "C:\\include\\",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "name": "PRODUCAO",
            "smartClientPath": "C:\\Totvs\\smartclient",
            "environment": "RAZNVN",
            "serverVersion": "131227A",
            "server": "192.168.0.189",
            "port": "54517",
            "user": "ADMIN",
            "passwordCipher": "dkQ5Q0taNUxsNmVzQUQ5SGF0aW5TT1RVT3M3Tjh5S0lqS2pMYU5YQitBL2hob21JY3N3MkMvRmZWd1Z2ejNVSFNIRlJsZ3dBb1g3aGtQR2ZldGVqbW8yUUZabjc4ZWpuYjFBa2ZNSGdORUN5a0REVnpMRXNjTjNJUWpBUlgrY0c=",
            "includeList": "Z:\\PRODUCAO\\protheus_data\\include",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
            
        }
    ],
   
    "advpl.selectedEnvironment": "TESTE",
    "advpl.startProgram": "SIGAMDI",
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true,
    "advpl.debug_showTables": true

}
`

Fonte

`
 #Include 'Protheus.ch' 
User Function VsCode()    

 MsgInfo("Teste VsCode com AdvPL!","SigaMDI.net") 

Return
`

**Comment by killerall** [comment]
Veja na sua sub-pasta .vscode da pasta que você trabalhando, se existe o arquivo launch.json.

Veja se esta com o seguinte conteudo.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Advpl Debug",
            "type": "advpl",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceRoot}",
            "programRun": "${command:AskForProgramName}",
            "stopOnEntry": false,
            "enviromentInfo": "${command:GetEnvInfos}",
            "workspace": "${workspaceRoot}/"
        }
    ]
}
```
Esse arquivo é criado automaticamente, quando ele não existe, e se da o primeiro F5. Deve-se escolher AdvplDebug

**Comment by valtercezar** [comment]
Ola killerall 
Estou tentando habilitar o parâmetro  "advpl.debug_showTables": true no arquivo settings.json 
só que na pasta variaveis não aparece as tabelas o que pode ser?

**Comment by killerall** [comment]
Você usa o vscode em que sistema operacional?
Esta rodando o debug dentro de uma thread do protheus, depois que logou?

**Comment by valtercezar** [comment]
Olá Rodrigo estou usando em uma três utilizando o Protheus

Em qua, 22 de mai de 2019 16:25, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by valtercezar** [comment]
Windows

Em qua, 22 de mai de 2019 16:25, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
Testei aqui e esta normal.
Você habilitou no seu setting?
"advpl.debug_showTables": true,

**Comment by valtercezar** [comment]
Amanhã eu vou te mandar um vídeo de como está blz valeu

Em qua, 22 de mai de 2019 19:35, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by valtercezar** [comment]
Dá uma olhada como está configurado na aparece as tabelas na aba variáveis

Em qua, 22 de mai de 2019 19:35, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
@valtercezar Dar uma olhada aonde?

**Comment by valtercezar** [comment]
No anexo do vídeo

Em qui, 23 de mai de 2019 09:20, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
@valtercezar Se você está respondendo isso via email, os anexos não vão pro github.
Por favor, entre na pagina e adicione o video pela pagina.

[]s

**Comment by valtercezar** [comment]
Segue o link do vídeo

https://github.com/valtercezar/advpl/blob/master/vscode.mp4

Em qui, 23 de mai de 2019 09:31, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
@valtercezar 
Você está utilizando a extensão da Totvs e não a minha.
Acredito que precise entrar em contato com eles para verificar o que ocorre.
(Se as duas estiverem instaladas pode dar problema)

**Comment by valtercezar** [comment]
Entendi muito obrigado

Em qui, 23 de mai de 2019 09:45, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:
