### ISSUE TITLE
Erro ao Descompilar Resource

### ISSUE THREAD

**Issue by cmregazzo** [totvs/advpl-vscode#272]
Bom dia,

Ao tentar Descompilar um Resource do RPO, no caso uma imagem PNG, é exibido o seguinte erro:

Bridge Return:

SyntaxError: Unexpected end of JSON input
Iniciando a compilação do fonte:c:\Projeto Protheus\Workspace\Resources\IconeWord.png

Obrigado.

**Comment by killerall** [comment]
Não consegui reproduzir. Estou fechando esta issue.
