### ISSUE TITLE
Compilar Fonte no Linux

### ISSUE THREAD

**Issue by brunosps** [totvs/advpl-vscode#274]
Boa tarde, 

Instalei o VSCode e a instação advpl-vscode no linux mint 19.
Após a configuração dos ambientes, eu tento compilar um fonte e aparece a mensagem "Por favor selecione um ambiente". A mensagem aparece toda vez que tento compilar, mesmo já tendo selecionado um ambiente.

**Comment by killerall** [comment]
Boa tarde,

Você conseguiu gerar o Cipher da sua senha?
Cola o seu settings aqui, por favor.

**Comment by brunosps** [comment]
Tarde, 

Então eu copiei a configuração de uma maquina windows então o cipher tava lá.

Segue a configuração:

```json
{
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.debug_multiThread": false,
    "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true,
    "advpl.debug_showTables": false,
    "advpl.environments": [{
        "smartClientPath": "/home/bruno/smartclient",
        "environment": "BRUNO",
        "includeList": "/home/bruno/includes",
        "server": "192.168.1.185",
        "port": "1301",
        "user": "bruno",
        "passwordCipher": "T25rM3pOMElmVWhVRGhWQTJobnI2OUZaaGRiMkRyL0RFbXQ0bFp0d3BJOFRsSElGbldVOVdvRkpGbGNYcUhNYWNQRm5NWDRzL3F2YnlkRDNwRG5YMFplRm9DcWJtcDF0TjBMbERySmpPc1h6YXQ2LzlwL2NqcVNVRzVwRHVqTWg="
    }],
    "advpl.startProgram": "SIGAMDI",
    "files.encoding": "windows1252",
    "workbench.sideBar.location": "left",
    "workbench.statusBar.visible": true,
    "editor.minimap.enabled": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.fontSize": 12,
    "workbench.iconTheme": "vscode-icons",
    "workbench.editor.enablePreview": true,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.fontFamily": "'Courier New', monospace",
    "workbench.activityBar.visible": true,
    "editor.renderIndentGuides": false,
    "advpl.compile_threads": 1,
    "advpl.logger": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true
    },
    "search.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true
    },
    "vsicons.projectDetection.autoReload": true,
    "workbench.colorCustomizations": {
        "editorIndentGuide.activeBackground": "#ff0000"
    },
    "window.zoomLevel": 0
}
​
```

**Comment by brunosps** [comment]
Selecionei a opção Cipher com CTRL + SHIFT + P, e no output ficou com as seguintes mensagens:

AdvPL Iniciado
Erro ao iniciar compilação: Nenhum ambiente selecionado!

Segue print da tela.
![vscode_linux](https://user-images.githubusercontent.com/595279/45645564-3bbefb00-ba97-11e8-8f1c-ec4a94dc4921.png)

**Comment by killerall** [comment]
Quando você clica no Esquilo no canto inferior direito para selecionar o ambiente, ele mostra a lista de ambientes corretamente ?

**Comment by brunosps** [comment]
Sim,

Aparece a lista com os ambientes.
![selecao_ambiente](https://user-images.githubusercontent.com/595279/45647929-83e11c00-ba9d-11e8-8b58-f6deb74de28f.png)


Tem algum parametro de debug ?

**Comment by killerall** [comment]
Quando você clica no Bruno, ele não fica selecionado em baixo?
Para debugar isso, teria que fazer clone desse reposistorio e fazer o debug da extensão. Pois isso esta na camada do vscode.

**Comment by brunosps** [comment]
Sim na hora que seleciono o ambiente dá uma mensagem de sucesso.
![ambiente_selecionado](https://user-images.githubusercontent.com/595279/45648489-1c2bd080-ba9f-11e8-9d3a-8e880e6b76ec.png)

**Comment by killerall** [comment]
Gerando o Cipher depois disso, some o ambiente selecionado?

**Comment by brunosps** [comment]
Não quando tento o Cipher só dá a mensagem "Erro ao iniciar compilação: Nenhum ambiente selecionado!" no output e o ambiente ali no esquilo fica como BRUNO mesmo.

**Comment by killerall** [comment]
Tenta fazer o seguinte:
entre na pasta.
/Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.9/bin/alpha/linux

E rode 
$.\AdvplDebugBridgeC --getId

Ele roda e retorna um valor XXXX-YYYY?

**Comment by brunosps** [comment]
O AdvplDebugBridgeC não funciona, dá a seguinte mensagem:
```
.AdvplDebugBridgeC: comando não encontrado
```

Acredito que seja algum problema com as lib32 no linux mint 19, pois instalei o ubuntu 14 em outra VM e lá consigo compilar.

**Comment by brunosps** [comment]
Alias o ubuntu é o 16.04

**Comment by killerall** [comment]
Veja as permisoes do executavel, veja se tem o X.

**Comment by jmfrolim** [comment]
Estou com um problema similar no Linux Xubuntu versão:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu

Só que no meu caso eu consigo selecionar o ambiente tudo certo, mas ele não acha a pasta dos includes da mensagem:
 **APPRE1.PRW(0) Error C2090  File not found PRTOPDEF.CH**

Segue o meu settings:


            files.autoSave": "off",
           "editor.minimap.enabled": false,
           "files.encoding": "windows1252",
            "git.autofetch": true,
            "advpl.environments": [
            {
               "smartClientPath": "/home/joao/totvs/smartclient/",
              "environment": "PPADRAO",
               "includeList": "//home//joao//totvs//includes",
                "server": "192.168.56.11",
                "port": "1234",
                "user": "Admin",
               "passwordCipher": "/JXN8Gt69qQcBuvTXEJxRf45ePBAVVjwtqU6lZeMB1NzNM7BegMOv6zbkNhdAr3yAADznXvyMoDiVa0  NQADNTyFL="

        },
        {"smartClientPath": "/home/joao/totvs/smartclient/",
            "environment": "PFERT",
            "includeList": "/home/joao/totvs/include/",
            "server": "192.168.56.11",
            "port": "1239",
            "user": "Admin",
            "passwordCipher": "/JXN8Gt69qQcBuvTXEJxRf45ePBAVVjwtqU6lZeMB1NzNM7BegMOv6zbkNhdAr3yAADznXvyMoDiVa0NQADNTyFL="
   
           },
           {"smartClientPath": "/home/joao/totvs/smartclient/",
            "environment": "API_WEB",
            "includeList": "/home/joao/totvs/include/",
            "server": "192.168.56.11",
            "port": "1235",
            "user": "Admin",
            "passwordCipher": "/JXN8Gt69qQcBuvTXEJxRf45ePBAVVjwtqU6lZeMB1NzNM7BegMOv6zbkNhdAr3yAADznXvyMoDiVa0NQADNTyFL="
   
           }
    ],
    "advpl.debug_showTables": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showPrivates": true,
    "advpl.compileFolderRegex": ".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl|tlpp)",
    "advpl.debug_multiThread": true,
    "advpl.workspaceFolders": ""
         }


Antes eu usava windows e funcionava beleza, mas mudei para linux e agora da esse problema.

**Comment by jmfrolim** [comment]
Consegui resolver o meu problema, foi bem simples que sinto até vergonha hahahah. O windows não diferencia letras maiúsculas de minusculas ou seja ela não e case sensitive, mas o Linux sim, os meus includes eu havia copiado de uma pasta windows então os nomes estavam todos meio esquisitos.
Eu baixei novamente os includes do portal da totvs e funcionou corretamente.
Por mim essa issue pode ser fechada.
