### ISSUE TITLE
Compilar Fontes Abertos

### ISSUE THREAD

**Issue by ricardobz** [totvs/advpl-vscode#282]
Olá, estou utilizando o plugin no vscode, excelente diga-se de passagem, e me deparei com uma situação que utilizava muito no TDS, compilar os fontes em aberto!
Não identifiquei essa opção, a principio criei um arquivo txt com os nomes das rotinas que estou trabalhando e serviu mto bem, mas gostaria de saber se existe uma demanda de quem utiliza o plugin relacionada a essa questão?

**Comment by killerall** [comment]
@ricardobz 
É uma opção que seria bacana sim.
No momento não consigo parar para implementar isso. Mais essa parte fica no TypeScript disponível aqui no github.
Um pullrequest com essa melhoria seria bem vinda.

**Comment by diogenesdauster** [comment]
Eu vou tentar fazer, vou criar um fork.

**Comment by robsonrosilva** [comment]
Tentei fazer, mas não consigo obter a lista de arquivos abertos até consigo compilar se eu conseguir a lista usando a funcionalidade de compilação de arquivo texto gero um arquivo na pasta temporário do windows com os arquivos e esse arquivo consigo compilar, mas não consigo obter a lista completa com os arquivos abertos, se alguém puder me ajudar a obter todos os arquivos abertos consigo terminar a minha tentativa de implementação.

**Comment by robsonrosilva** [comment]
@killerall fiz uma implementação da compilação dos arquivos abertos, ela só funciona com os arquivos abertos ou acionados após a abertura do vscode e utiliza a compilação de arquivos TXT, com certeza está longe de ser a melhor forma de implementação, mas foi o que consegui fazer com os conhecimentos que tenho de typescript. Estou criando uma branch compileOpenFiles e vou subir o que fiz.

**Comment by robsonrosilva** [comment]
@killerall acredito que vou precisar de permissão no projeto para enviar o que fiz.

**Comment by diogenesdauster** [comment]
Eu dei uma olhada e vi que voce pode usar o Open Editor ai evita voce criar uma arquivo temporario na maquina se nao vai ter que tratar para as outras plataformas

**Comment by robsonrosilva** [comment]
Desculpe minha ignorância(sou leigo), o Open Editor que você fala seria um pacote NPM certo? Vi vários de criação de arquivos temporários, mas não consegui implementar, se puder me dar uma luz, não conheço muito, mas tenho vontade de aprender e de contribuir.
