### ISSUE TITLE
[0.10.12] Debug - CallStack with only one item

### ISSUE THREAD

**Issue by vlopes11** [totvs/advpl-vscode#292]
Colleagues,

The call stack is showing only the top 1 item from the stack after the latest update

https://ibb.co/dnBFvf

**Comment by vlopes11** [comment]
Seems like it's the VSCode latest.

We restored to 0.10.10 and it also didn't work

**Comment by killerall** [comment]
@vlopes11 
Eu já questionei a microsoft sobre isso:
https://github.com/Microsoft/vscode/issues/61088

Estou no aguardo se preciso alterar algo

**Comment by MiguelGontijo** [comment]
Oi Rodrigo, boa tarde. Acompanhei o chamado aberto por você na Microsoft sobre o VSCode, sabe me dizer quando sai o release com a correção do call stack ?

Obrigado, desde já!

**Comment by killerall** [comment]
@MiguelGontijo 
Provavelmente na versão de Outubro, que deve sair no fim desse mes.

**Comment by killerall** [comment]
@vlopes11 essa issue foi corrigida no vscode?

**Comment by vlopes11** [comment]
Oi, vou retornar de ferias na quarta-feira. Ai verifico, ok?

**Comment by vlopes11** [comment]
Confirmado, esta corrigido!

Obrigado :)

**Comment by tigas360** [comment]
Boa tarde. Como foi corrigido o problema do call stack que mostra apenas a ultima pilha de chamada?
estou com a ultima versão do vscode September 2019 (version 1.39) e da extensão do ADVPL 0.12.3.

No aguardo e obrigado.

**Comment by killerall** [comment]
Boa tarde,
O problema dessa issue tinha relação com o proprio vscode.
Se você estiver tendo esse comportamento mesmo com a ultima versao (1.39.2), por favor detalhe como reproduzo esse problema, e em que SO e versao.

**Comment by tigas360** [comment]
> Boa tarde,
> O problema dessa issue tinha relação com o proprio vscode.
> Se você estiver tendo esse comportamento mesmo com a ultima versao (1.39.2), por favor detalhe como reproduzo esse problema, e em que SO e versao.

Estou usando Windows 7, para reproduzir é preciso debugar um fonte passando pelas funções com o F11(Step Into) o caso é intermitente. (Todos os meus fontes que estou debugando estão locais)

Não sei se pode ser algum problema de sincronismo com o AppServer.exe.
