### ISSUE TITLE
Permitir configuração de multi-thread por environment.

### ISSUE THREAD

**Issue by izacsc** [totvs/advpl-vscode#304]
Existem ambientes que não deve ser utilizado depuração em muliplas threads. Uma configuração por ambiente evita parar acidentalmente um ambiente.

**Comment by AlencarGabriel** [comment]
@izacsc , boa tarde. 

No próprio TDS a opção Multi-Thread é compartilhada pela IDE entre todos os ambientes configurados, até porque esta opção não costuma ser muito utilizada, então acho que configurar por ambiente não seria tão útil. 

Mas estava lendo sua issue e pensei em uma implementação simples, que envolve colocar na Status Bar do VSCode uma informação se a configuração `advpl.debug_multiThread` estiver habilitada. O que acha?

**Comment by AlencarGabriel** [comment]
Sim sim, esse problema acontece com muitos rs. 

Mas a minha preocupação é na verdade a compatibilidade com os usuários que já tem instalado, hoje são mais de 8000 instalações válidas, e como você pensa migrar este tipo de configuração, ou notificar a todos como configurar novamente?

Com essa minha sugestão da Status Bar, pode ser possível habilitar/desabilitar o multi-thread facilmente e de forma intuitiva.

**Comment by izacsc** [comment]
Entendo o seu ponto. Na verdade não me parece tão difícil migrar para uma opção por ambiente. Segue o que eu imaginei.

1. Default para a opção seria Falso. Único colateral seria desativar o debug multithread de quem já estivesse habilitado. 
2. Warning de propriedade deprecada no json, apontando pra nova configuração.

A forma de armazenagem da configuração, no entanto, não impede de fazer a sua sugestão do Status Bar, já que é uma forma visual de alterar a configuração. Caso fosse por ambiente, ao mudar de ambiente a Status Bar seria atualizada com a configuração correta.

**Comment by killerall** [comment]
@izacsc 
Acho que a solução do @AlencarGabriel  de ter uma opção no status bar, para ligar e desligar melhor. E da para implementar sem mexer no AdvplDebugBridge.

Ficar mudando isso no json, acredito que fique meio chato.

**Comment by AlencarGabriel** [comment]
@killerall ,

você faz a implementação, ou prefere um Pull Request?

**Comment by AlencarGabriel** [comment]
Como assim o replay do TDS? rsrsrs Fiquei curioso pra saber qual o futuro da extensão, já que agora está incorporado no repositório da TOTVS.
