### ISSUE TITLE
Desfragmentação de RPO

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/advpl-vscode#308]
Após comparativo de desfragmentação do TDS e da sua extensão verifiquei que há uma diferença bem grande no tamanho do RPO quando executado em ambos.

Após desfragmentar um RPO com 1.7 GB tive os seguintes resultados:
TDS= 613MB
VSCODE= 1,21 GB

Sabe o que causa uma diferença tão considerável?

**Comment by killerall** [comment]
Vc fez o teste com o mesmo RPO e binario?
Não era pra ter diferença pois é o binario que faz o Defrag.

**Comment by killerall** [comment]
Testei aqui tanto no vscode, quanto no tds deu o mesmo tamanho. Fiz o teste no binario 13 e 17.
Pode ser que o seu rpo tenha alguma coisa que eu o meu não tenha.

Vou tentar pegar algum outro rpo para testar.

**Comment by robsonrosilva** [comment]
Fiz o teste que pediu e o resultado desta vez ficou igual, tem alguma configuração para a desfragmentação pelo VsCode que elimine os registros de atualizações?

**Comment by sitiorecantodoqueijo** [comment]
Bom dia, 

Aqui também aconteceu a mesma coisa: 
RPO Antes = 1,28 GB
Defrag do VS Code = 1,21 GB
Defrag do TDS = 649 MB

Já existe alguma melhoria no vs code para este problema?

**Comment by killerall** [comment]
Na versão 0.11.0 que saira esse fds criei uma chave nova, dentro do env.
defragPackAllInfo
Defina como true, para limpara o historico de atualizações;

**Comment by sitiorecantodoqueijo** [comment]
Testei aqui e funcionou perfeitamente, muito obrigado.
