### ISSUE TITLE
Debug limitado em 64 caracteres 

### ISSUE THREAD

**Issue by rcarloslima** [totvs/advpl-vscode#310]
Boa tarde,

Quando utilizo o debug e a variável tem mais de 64 caracteres ele corta, não sei se é alguma configuração que tem q fazer, mas isso acontece tanto no Windows como no Mac.

Parabéns pela a extensão, excelente iniciativa!!!

**Comment by killerall** [comment]
Boa tarde,
Como assim ele corta? Consegue anexar um print?

**Comment by rcarloslima** [comment]
Bom dia.

Segue as imagens:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/14075363/52913719-a28f4d00-329f-11e9-8362-d28eea369412.png">


<img width="1458" alt="image" src="https://user-images.githubusercontent.com/14075363/52913726-b3d85980-329f-11e9-89ba-fb46771d3fe7.png">

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/14075363/52913820-67414e00-32a0-11e9-97bc-d6cc0c80fd54.png">


Aqui não aparece o valor todo da variável.


Tem esses links de pessoas que tiveram o mesmo problema e o povo falou que era com a extensão:

https://github.com/Microsoft/vscode-go/issues/278
https://github.com/go-delve/delve/issues/609#issuecomment-239161459

**Comment by killerall** [comment]
Não consegui ver aonde esta cortanto o texto. Na imagem do console, e no mouse houver, me parece que esta completo.
