### ISSUE TITLE
[MAC] -  SmartClient

### ISSUE THREAD

**Issue by dabraga** [totvs/advpl-vscode#311]
Não consigo subir o smartclient pelo vsCode

**Comment by killerall** [comment]
Você deve estar configurando alguma coisa errada.
Existe uma extensão que cria uma sandbox inteira para desenvolvimento advpl, e ela ja configura corretamente o vscode, inclusive no MAC.

https://marketplace.visualstudio.com/items?itemName=totvs.protheus-dev-sandbox
