### ISSUE TITLE
[WebService] Client WS Gerando vazio

### ISSUE THREAD

**Issue by Kinsuyo** [totvs/advpl-vscode#312]
Estou com problema ao gerar o client WS do seguinte link:
![erro clientws](https://user-images.githubusercontent.com/42854292/53458287-430a0d80-3a14-11e9-8291-4ccddbf51d75.png)

https://www.tramontina.net/gas/ws/r/product?WSDL

Utilizo a opção de geração e o VSCode criar um fonte chamado client.prw, mas cria o mesmo vazio. Poderia me informar se existe outra forma de gerar esse client ou se estou fazendo algo errado?

**Comment by killerall** [comment]
@Kinsuyo 
O problema esta que o prothues não consegue gerar esse WSDL.
Testei no TDS e ele deu a messagem correta:
*** ERRO AO GERAR FONTE ADVPL ***
Source URL : https://www.tramontina.net/gas/ws/r/product?WSDL
-------------------------------------------------------------------------------
WSCERR036 / Definição não suportada.
ADVPL WSDL Client 1.120703 / TOTVS Educacional Comparativo on 20190227 07:10:24
------------------------------------------------------------------------------

Vou deixar essa issue aberta para arrumar a messagem aqui no vscode.

Obrigado.

**Comment by Kinsuyo** [comment]
@killerall 
Voce sabe me dizer porque nao gera? tem algo de diferente? ou configuração ? usando esta url no SOAPUI eu consigo consumir seus métodos normalmente.

**Comment by killerall** [comment]
O gerador de Client de WS não suporta toda a spec atualizado do SOAP.
Normalmente nesses casos o pessoal usa o TWsdlManager
http://tdn.totvs.com/display/tec/Classe+TWsdlManager

**Comment by Kinsuyo** [comment]
Tentei usar essa classe tbm, neste caso o erro gerado foi este aqui:

Could not connect to https://www.tramontina.net/gas/ws/r/product

**Comment by killerall** [comment]
Corrigido na 0.11.0
