### ISSUE TITLE
[Linux] - Debugar ou Iniciar Smart Client sem debugar

### ISSUE THREAD

**Issue by dyhalmeida** [totvs/advpl-vscode#313]
**Prezados, configurei a extensão ADVPL numa distro linux derivado do debian.**
> Configuração JSON:
```json
advpl.debug_multiThread": true,
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.debug_showTables": true,
    "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true,
    "advpl.alpha_compile": true,
    "advpl.pathPatchBuild": "",
    "advpl.environments": [
        {
           "server": "10.10.1.20",
           "port": "1234",
           "compile_force_recompile": true,
           "smartClientPath": "/home/djalmeida/TOTVS/smartclient_teste/",
           "environment": "PORTAL-SA",
           "includeList": "/home/djalmeida/TOTVS/includes/",
           "startProgram": "SIGAADV",
           "user": "diego.almeida",
           "passwordCipher": "kLcX7f3q0iRZctuADWqeTaSWFhsRtChRknhr9G4soKXU9cjPfDi82O1BaBo/h1sGAA6HIxbLc5woFwzEfSEp3uOL="
        }
    ],
    "advpl.selectedEnvironment": "PORTAL-SA",
    "advpl.logger": true
```

Aplicando as seguintes configurações:
- Consigo compilar os fontes com CTRL + F9.
- Consigo executar smartClient sem parâmetros com CTRL + F11
- **Não consigo debugar com F5. Apresenta o dialogo perguntando o programa inicial, porém nada acontece e nem o smartCliente é executado**
- **Não consigo iniciar o smartClient sem debudar CTL + F5. Apresenta o dialogo perguntando o programa inicial, porém nada acontece e nem o smartCliente é executado**

Como posso solucionar isso? Lembrando que estou numa máquina Linux.

**Comment by killerall** [comment]
O Vscode mudou como é feito a construção do arquivo launch. Devo lançar em breve uma alteração para isso.

Por ora, basta ir no Debug(icone do isto) e na Engrenagem que aparece do lado do combo box.
Escolha AdvplDebug

Ele vai criar um arquivo chamado launch,json com a configuração. salve o arquivo e de o F5 novamente.

**Comment by dyhalmeida** [comment]
Valeu, sua solução funcionou!
