### ISSUE TITLE
Problemas com o Debug no Lobo Guará 

### ISSUE THREAD

**Issue by PedroPedrada** [totvs/advpl-vscode#314]
Pessoal,

Não estou conseguindo debugar no vsCode no Protheus 12.1.23 - Lobo Guará.

Está exibindo a seguinte mensagem: "This aplication failed to start because it could not to find or load to Qt platform plugin "Windows In". Reinstalling the aplication may fix this problem".

Ao verificar no caminho da instalação do smartClient, "...\bin\smartclient\dlls\platforms" o arquivo qwindows.dll está lá.

Compilar estou conseguindo normalmente.

Alguém já passou por isso ?

Obrigado.

**Comment by killerall** [comment]
Você esta conseguindo entrar no ambiente chamando o smartclient diretamente?
O Vscode para debugar não faz uso do SC, apenas da exec com parametros nele.

**Comment by PedroPedrada** [comment]
Killerall, bom dia!

Consigo entrar normalmente no ambiente chamando o smartclient diretamente! 

Agora, se eu apagar a qwindows.dll do caminho "...\bin\smartclient\dlls\platforms e tentar acessar o smartclient diretamente, ai apresenta o mesmo erro. 

Obrigado.

**Comment by PedroPedrada** [comment]
Galera, boa tarde!

Mais ninguém passou por isso? Pois com isso tive que voltar para o DevStudio! :disappointed:

**Comment by killerall** [comment]
Eu não consegui reproduzir o problema.
Fiz uma instalação do 0 da 23.
Funcionou normal.

**Comment by PedroPedrada** [comment]
Pessoal, bom dia!

Finalmente consegui resolver o problema!!! :smiley:  :tada: :tada:

Compartilhando o que foi feito:

- Criei uma variável de ambiente chamada "QT_PLUGIN_PATH" e informei o caminho das DLLs que estão na pasta smartClient.
![image](https://user-images.githubusercontent.com/48094977/54358350-ed9e4500-463e-11e9-9abb-061dc5cd9452.png)

-Verifique se o arquivo "qwindows.dll" está nesse diretório informado. Caso não esteja, copie.

Valeu pela força!

Abs.

**Comment by killerall** [comment]
@PedroPedrada Obrigado pelo compartilhamento.
