### ISSUE TITLE
Problema Debug no Mac

### ISSUE THREAD

**Issue by Evandroafv** [totvs/advpl-vscode#315]
Não estou conseguindo fazer debug.
Ao abrir o smartclient e acessar a rotina, trava o debug e aumenta muito o uso da memória.
Advpl Versão 0.10.18.

<img width="802" alt="Screen Shot 2019-03-09 at 15 32 19" src="https://user-images.githubusercontent.com/33877185/54076412-bff17e80-4281-11e9-95b7-ad3cc6384756.png">

**Comment by killerall** [comment]
Ese problema começou acontecer agora?

Você estava conseguindo debugar antes? Com qual versao?

**Comment by Evandroafv** [comment]
Voltei a usar o mac semana passada. Voltei a versão do mac para high Sierra e mesmo assim continua acontecendo. Nas versões mais antigas do advpl eu conseguia debugar.
Não me lembro qual era a versão.

**Comment by Evandroafv** [comment]
Achei o problema. Mudei a linha abaixo para 'false'. 
"advpl.debug_showStatics": true

**Comment by dabraga** [comment]
> Não estou conseguindo fazer debug.
> Ao abrir o smartclient e acessar a rotina, trava o debug e aumenta muito o uso da memória.
> Advpl Versão 0.10.18.
> 
> <img alt="Screen Shot 2019-03-09 at 15 32 19" width="802" src="https://user-images.githubusercontent.com/33877185/54076412-bff17e80-4281-11e9-95b7-ad3cc6384756.png">

Evandro , Pode me ajudar .Porque meu smartclient não abre no mac

**Comment by Evandroafv** [comment]
Veja se o seu smartclient está habilitado. Se estiver, desmarque.

<img width="662" alt="Screen Shot 2019-04-02 at 08 15 39" src="https://user-images.githubusercontent.com/33877185/55401779-c50fb980-551f-11e9-8748-0938e609969e.png">
