### ISSUE TITLE
Cannot overwrite TOTVS programs

### ISSUE THREAD

**Issue by rodrigosanches** [totvs/advpl-vscode#317]
Boa tarde,

Aconteceu uma coisa estranha comigo, eu utilizo o Advpl-vscode no MacOS, realizei a compilação de um fonte normalmente, quando eu fui compilar o mesmo fonte utilizando o próprio TDS me apresentou a seguinte mensagem => "Cannot overwrite TOTVS programs", sendo que na opção
Advpl: Authorization_permission
1 - Para permitir substiuir fontes TOTVS, 0 para Não, está com o valor 0(zero).

Eu não consigo compilar o mesmo fonte utilizando o TDS depois que eu compilo utilizando o VSCODE.

Estou fazendo alguma coisa errada?

Obrigado.

**Comment by killerall** [comment]
Boa noite,
Para compilar fontes com functions, é necessario ter chave de compilação.
Vou verificar mais você deveria ter recebido a mesma message no vscode.
