### ISSUE TITLE
[MAC] Após atualização do VSC não consigo mais debugar alguns fontes.

### ISSUE THREAD

**Issue by jcstorino** [totvs/advpl-vscode#318]
@killerall , boa noite.

Esta ocorrendo uma coisa muito estranha, ontem eu conseguia debugar normalmente, hoje após a atualização alguns fontes simplesmente não debugam, na verdade o smartclient simplesmente trava e não acontece nada, nenhum erro, nada no console, nada no advplbridge, não sei mais o que fazer para descobrir o problema.. 

O mais estranho é que alguns pontos de entrada debugam sem problema nenhum.

Alguma luz ?
Att.

[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/3045669/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
Boa noite,
Ainda não atualizei o vscode, se conseguir ver os nomes + path dos arquivos que iam certos e os que não vao talvez achamos algum padrao.

**Comment by jcstorino** [comment]
Oi @killerall 

Fiz alguns testes e acho que o problema é mesmo no VSC, pois voltando o app para a versão 1.32.2 consigo debugar normalmente, quando atualizo para 1.33.0 o problema ocorre.

Usei o Time Machine no mac para voltar todas as pastas envolvidas, mas descobri que voltando somente o .app da pasta /Applications já volta a versão..., ou seja, alguma coisa nova que fica dentro do app esta causando alguma instabilidade no Debug.

Qq coisa estou à disposição para auxiliar.

**Comment by silfar** [comment]
Aqui a mesma coisa, como consigo voltar a versão do code ?

**Comment by jcstorino** [comment]
> Aqui a mesma coisa, como consigo voltar a versão do code ?

Feche o VSC.
Abre o finder na pasta Aplicativos, execute o Time Machine.
Pega o app VSC do dia/hora anterior à que você atualizou e mande restaurar/sobrepor.
Desconecte o mac da rede/internet antes de abrir o VSC.
Desative a atualização automática do VSC senão vai atualizar denovo.

Espero ter ajudado..

**Comment by silfar** [comment]
Uso linux.
Silfar Goulart

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/04/19
16:33:50

Em qua, 10 de abr de 2019 às 16:30, Julio Cesar Storino <
notifications@github.com> escreveu:

**Comment by silfar** [comment]
Achei um deb aqui da 1.30 voltou a funcionar.
Só que  tô recebendo estas msgs:
![image](https://user-images.githubusercontent.com/68900/55908421-cc823300-5baf-11e9-9d48-e444f3c15fea.png)

E queria saber se essa tela é normal:
![image](https://user-images.githubusercontent.com/68900/55908462-e885d480-5baf-11e9-850f-29dbff98765d.png)

**Comment by jcstorino** [comment]
Tende reinstalar esta extensão… 
Verifique o console log das extensões..

**Comment by silfar** [comment]
Já reinstalei mas continua a mesma coisa. Onde vejo esse console log.

**Comment by jcstorino** [comment]
![image](https://user-images.githubusercontent.com/19559870/55912218-a3b26b80-5bb8-11e9-8517-22e7e98298f8.png)

**Comment by killerall** [comment]
@silfar Acreidto que seja informações de outra extensão que você está vendo.

Sobre o caso de nao debugar alguns fontes, acabei de migrar minha maquina do trabalho para o linux/mint. E não tive problemas com o debug, porem estou utilizando a proxima versão da extensão, que deve sair amanha.
Gostaria de pedir que assim que sair, atualizem tanto a versão do vscode quanto da extensão. E vemos se continua a dar problema.

**Comment by killerall** [comment]
@jcstorino Boa noite,
Acabei de lançar o update, se puder testar como esta funcionando, fico agradecido.

**Comment by jcstorino** [comment]
@killerall Bom dia...
Então.. no meu caso aqui ainda não deu certo.. o estranho é que o SmartClient trava somente em uma rotina ( pelo que pude observar até agora ! ). Eu tenho vários PE no cadastro de clientes, quando clico em altera um cliente, alguns PE até entram e debugam normalmente, mas depois não segue e trava.
Outros programas debugam certinho..
Não sei se é algum PE específico ou o que, pois não consigo extrair nenhuma mensagem nem no console do server.. nada...

**Comment by rodrigopg** [comment]
O meu voltou a funcionar após a atualização.. 
@jcstorino qual o nome do P.E. que está usando? 
Posso simular aqui se debuga normal ou não

**Comment by jcstorino** [comment]
De fato este erro não ocorreu mais.. pode fechar esta issue ! Obrigado.
