### ISSUE TITLE
Geração de Json de launch errado

### ISSUE THREAD

**Issue by pgeovane** [totvs/advpl-vscode#322]
Olá @killerall parabéns pela extensão, simplesmente otíma.
Estou com um problema ao debugar no Windows.
Fiz a configuração conforme consta no github mas encontro um erro.
Segue abaixo o erro e launch.json

Ao apertar F5 para iniciar o Debug o VCode retorna essa mensagem:
"Error while processing request 'launch' (exception: Unexpected character encountered while parsing value ^.path '', line 0, position 0.)"

Segue o meu launch.json:

{
    // Use o IntelliSense para aprender sobre possíveis atributos.
    // Passe o mouse para ver as descrições dos atributos existentes.
    // Para obter mais informações, visite: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Advpl Debug",
            "type": "advpl",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceRoot}",
            "programRun": "^\"\\${command:AskForProgramName}\"",
            "stopOnEntry": false,
            "enviromentInfo": "^\"\\${command:GetEnvInfos}\"",
            "workspace": "^\"\\${workspaceFolder}/\""
        }
    ]
}

se souber o que pode ser fico muito grato.
Att;

**Comment by killerall** [comment]
Estranho, ele para ele ter gerado corretamente, no linux ele faz certo, vou investigar aqui.

Para arrumar o seu arquivo, deixe ele assim:


```
        {
            "name": "Advpl Debug",
            "type": "advpl",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceRoot}",
            "programRun": "${command:AskForProgramName}",
            "stopOnEntry": false,
            "enviromentInfo": "${command:GetEnvInfos}",
            "workspace": "${workspaceFolder}"
        }
```
