### ISSUE TITLE
Compilar = Running the contributed command: 'advpl.compile' failed.

### ISSUE THREAD

**Issue by LidimonCristiano** [totvs/advpl-vscode#324]
Boa tarde,

Ao compilar qualquer fonte ocorre a mensagem: _"Running the contributed command: 'advpl.compile' failed."_ 
E logo em seguida ocorre:
_"Compilação ignorada, existe outra compilação sendo executada."_

O arquivo inicial esta conforme abaixo. Obrigado!

{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		
		"advpl.environments":[{
				"smartClientPath": "C:\\TI\\gDrive\\protheus12_teste\\",
				"environment": "h1",
				"includeList": "\\\\192.168.0.251\\grupo.ti\\workspace11.3\\include",
				"server": "192.168.0.200",
				"port": "1299",
				"user": "Admin",
				"passwordCipher": "1"
			},
			{
				"smartClientPath": "E:\\TOTVS\\Smartclient\\",
				"environment": "TESTE2",
				"includeList": "\\\\192.168.0.251\\grupo.ti\\workspace11.3\\include",
				"server": "192.168.0.200",
				"port": "1299",
				"user": "Admin",
				"passwordCipher": "1"
			}
		],
		"advpl.selectedEnvironment": "h1"
	}
}

**Comment by killerall** [comment]
Boa tarde,
A pasta de include não podem ser pasta da rede.
No minimo precisa estar mapeadas.

Uma vez que ele da erro, ele vai ficar dando a msg
"Compilação ignorada, existe outra compilação sendo executada."

**Comment by LidimonCristiano** [comment]
Bom dia, ok deu certo obrigado. E essa questão da leitura em rede depende na verdade é do VCS ? Obrigado mais uma vez.
