### ISSUE TITLE
Erro ao compilar classes Cannot overwrite TOTVS programs

### ISSUE THREAD

**Issue by Evandroafv** [totvs/advpl-vscode#327]
Após última atualização do vscode, não está aceitando compilar classes que eu compilava antes.

Error in PCSincronizacaoDados.prw Cannot overwrite TOTVS programs (PCSINCRONIZACAODADOS.PRW)
Compilation finished with errors, check the Problems tab!

**Comment by killerall** [comment]
Se você não tem chave de compilação, e essa classe foi compilada com a versao antiga do vscode, vai precisar deletar o fonte do rpo e recompilar.
Existia um bug que alguns casos poderia ter compilando com a proteção da totvs ativada de maneira errada.
