### ISSUE TITLE
Depurar WebServices

### ISSUE THREAD

**Issue by fa6ricio** [totvs/advpl-vscode#328]
Mesmo com a clausula de multiplas thedes ativada não consigo depurar webservices WSDL, ele não para no ponto de parada, alguém consegue me ajudar?

**Comment by robsonrosilva** [comment]
@fa6ricio  faço da seguinte forma.
O settings do ambiente selecionado deve estar apontando exatamente para o appserver do webservice que vai receber a requisição.
Inicio o debug(pode abrir o sigaadv nem precisa logar se estiver com a tela de login do protheus aberta já serve)
Faço a requisição para o WebService.
Ele já deve parar nos BreakPoints.

**Comment by robsonrosilva** [comment]
Esqueci de avisar o Multitread tem que estar ativado no settings para funcionar.

**Comment by igormorse** [comment]
@robsonrosilva 

Segui os passos que você disse e de acordo com a Wiki. Liguei o Multi Thread, selecionei o ambiente do WebService, marquei o breakpoint na linha desejada e quando apertei F5, ao invés de digitar SIGAADV, apenas digitei uma User Function inexistente ( Como faço no TDS ), digamos U_XXXX e quando faço a requisição no WebService, o Debug para de executar e o Webservice fica travado na requisição como se estivesse debugando.

Sabe se está faltando alguma coisa ? O Debug de fontes "normais" funciona, apenas para Webservice que não está funcionando.

**Comment by killerall** [comment]
O que normalmente precisa ser feito, é a derrubada das threads do WebService, no monitor. Depois que o debug foi iniciado.
Pois em regra, apenas threads que iniciaram depois do inicio do debug, o appserver para corretamente.

**Comment by igormorse** [comment]
Mesmo eu reiniciando o serviço e tentando novamente o que acontece é o Debug parar no VSCode ( O botão de parar, prosseguir somem ).

**Comment by killerall** [comment]
@igormorse Qual o seu sistema operacional?

**Comment by igormorse** [comment]
Windows 10 @killerall

**Comment by killerall** [comment]
Tente fazer o seguinte teste.
No seu setting, coloque a chave.
advpl.alpha_compile : true

Gere o Cipher novamente. Note que o cipher gerado deve ser bem menor do que o você usa.

Compile um fonte para ver se esta OK, e teste se consegue debugar.

**Comment by igormorse** [comment]
Tentei aqui duas vezes e com essa opção do alpha_compiler o VSCode e o sistema operacional travaram e tive que reiniciar o PC em ambos os casos.

Assim que aperto para consumir o WebService, o Debug não sai como da outra situação mas o computador vai ficando lento até travar completamente.

**Comment by killerall** [comment]
Ta estranho isso.
Desabilita o seguinte:
         "advpl.debug_showTables": false,
        "advpl.debug_showPublic": false,

A questao de ficar lento, acredito que resolva.

Qual a instalacao do protheus que esta usando? Versao e release. o WS é padrao?

**Comment by igormorse** [comment]
> Ta estranho isso.
> Desabilita o seguinte:
> "advpl.debug_showTables": false,
> "advpl.debug_showPublic": false,
> 
> A questao de ficar lento, acredito que resolva.
> 
> Qual a instalacao do protheus que esta usando? Versao e release. o WS é padrao?

Agora não travou mas o Debug não entra e a requisição fica travada como se estivesse debugando.

A versão do Protheus é a 12.1.17. 

O WebService é em REST e é de um fonte customizado.

**Comment by killerall** [comment]
Realmente não sei o que pode estar ocorrendo.
Mais acredito que tenha algo errado no seu ambiente.
Eu tentei reproduzir aqui. Mais é muita variavel diferente.
Eu usei o 12.1.23, com server em linux, e o Vscode em linux tambem. Fiz um rest de teste aqui e debugou normal.

**Comment by igormorse** [comment]
> Realmente não sei o que pode estar ocorrendo.
> Mais acredito que tenha algo errado no seu ambiente.
> Eu tentei reproduzir aqui. Mais é muita variavel diferente.
> Eu usei o 12.1.23, com server em linux, e o Vscode em linux tambem. Fiz um rest de teste aqui e debugou normal.
> 
> Seu server esta na mesma maquina?

Não, aqui o servidor fica em um Windows Server e o VSCode estou utilizando no Windows 10 em minha máquina.

Vou ver se consigo testar em alguma outra máquina diferente.

**Comment by killerall** [comment]
Nunca tive uma boa experiencia em debugar multi thread com servidor remoto. Incrementa muito as possiblidade de erro.
Certifique-se que não tem balanciador de carga no servidor.
Se possivel suba um copia local na sua maquina, ficara bem mais facil de debugar.

**Comment by igormorse** [comment]
> Nunca tive uma boa experiencia em debugar multi thread com servidor remoto. Incrementa muito as possiblidade de erro.
> Certifique-se que não tem balanciador de carga no servidor.
> Se possivel suba um copia local na sua maquina, ficara bem mais facil de debugar.

Entendi, vou ver se faço isso pra ver se aumenta minhas chances aqui! Muito obrigado pela ajuda e atenção @killerall !

**Comment by antunesls** [comment]
Eu também estou com o mesmo problema para debugar, com o WS REST em maquina local.
O VSCODE não para no breakpoint.

**Comment by killerall** [comment]
@igormorse e @antunesls 
Acabei de fazer um teste inteiro aqui.

Algumas informaçóes importantes:
- Testei tudo no linux.
- Precisa se atentar se o "advpl.debug_multiThread" esta como true.
(Tive um conflito de configuração, pois o vscode tem setting por usuario e por workspace. @AlencarGabriel , se conseguir dar uma olhada o seu botão em baixo de ativar ou nao o multi-thread so muda se tiver workspace) , ou seja, confira nos dois settings, se não tem um ativado e outro não, e deixei em apenas 1 lugar.

Fiz primeiro um teste no pior cenario, que é as threads do Rest ja esta iniciadas, e inicio o debug depois. Consegui debugar normalmente, com a seguinte configuração de rest:


```
[ONSTART]
JOBS=HTTPJOB
REFRESHRATE=120

[HTTPJOB]
MAIN=HTTP_START
ENVIRONMENT=r23

[HTTPV11]
Enable=1
Sockets=HTTPREST

[HTTPREST] 
Port=666
IPsBind=
URIs=HTTPURI
Security=0

[HTTPURI]
URL=/rest
PrepareIn=
Instances=1,1

```
e o seguinte fonte de teste:

```
#include "protheus.ch"
#include "restful.ch"
WsRestful RestTesteDebug Description "API REST para testes"

    WsMethod GET Description "Sincronização de dados via GET"    WsSyntax "TESTREST"
    

End WsRestful

WsMethod GET WsService RestTesteDebug
local nx

For nx := 1 to 10
    conout("Teste no rest")
next 

::SetResponse("Feito")        
Return .T.


```
Fazendo um get em:

http://localhost:666/rest/RestTesteDebug/TESTREST

Como eu já disse, o comportamente de debugar thread que já iniciaram não é bem definido no appserver.

Por isso prefiro a solução abaixo, que sempre funciona, indepedente da versão do server.

Primeiro desligo a subida automatica do rest no server:


```
[ONSTART]
;JOBS=HTTPJOB
REFRESHRATE=120
```

Depois deixo essa user function compilada no rpo:
```

User function start_debug()

StartJob("HTTP_START",getEnvServer(),.f.)
Alert("fica parado")


Return


```

Sempre que preciso debugar o servico, apenas chamo o debug com u_start_debug, deixo parado no alert e chamo a API. Esse é ideal.

Espero que ajudem vocês. Como não tenho mais windows aqui para testar não consigo fazer eu mesmo o teste. Porem pedi para um colega aqui testar no windows e teve sucesso.
Qualquer coisa me falem.

Attt.

**Comment by antunesls** [comment]
Estou usando a versão 0.2.1 , por que a versão 0.3.6 , não conecta no server da erro.

Será que pode ser esse o problema ?

![image](https://user-images.githubusercontent.com/3491386/59694935-c451ff80-91bf-11e9-8cde-aa5e11122ec7.png)

**Comment by igormorse** [comment]
> Estou usando a versão 0.2.1 , por que a versão 0.3.6 , não conecta no server da erro.
> 
> Será que pode ser esse o problema ?
> 
> ![image](https://user-images.githubusercontent.com/3491386/59694935-c451ff80-91bf-11e9-8cde-aa5e11122ec7.png)

Esse repositório aqui é da extensão Advpl, existe outro repositório dessa extensão no grupo totvs. Nem sabia dessa outra extensão, vou dar uma olhada depois!

**Comment by AlencarGabriel** [comment]
> Estou usando a versão 0.2.1 , por que a versão 0.3.6 , não conecta no server da erro.
> 
> Será que pode ser esse o problema ?
> 
> ![image](https://user-images.githubusercontent.com/3491386/59694935-c451ff80-91bf-11e9-8cde-aa5e11122ec7.png)

@antunesls , esta extensão que está utilizando não é a mesma que utilizaste para reportar o problema. Para sua situação em específico você precisa abrir uma issue no repositório: https://github.com/totvs/tds-vscode

**Comment by AlencarGabriel** [comment]
> @igormorse e @antunesls
> Acabei de fazer um teste inteiro aqui.
> 
> Algumas informaçóes importantes:
> 
> * Testei tudo no linux.
> * Precisa se atentar se o "advpl.debug_multiThread" esta como true.
>   (Tive um conflito de configuração, pois o vscode tem setting por usuario e por workspace. @AlencarGabriel , se conseguir dar uma olhada o seu botão em baixo de ativar ou nao o multi-thread so muda se tiver workspace) , ou seja, confira nos dois settings, se não tem um ativado e outro não, e deixei em apenas 1 lugar.
> 
> Fiz primeiro um teste no pior cenario, que é as threads do Rest ja esta iniciadas, e inicio o debug depois. Consegui debugar normalmente, com a seguinte configuração de rest:
> 
> ```
> [ONSTART]
> JOBS=HTTPJOB
> REFRESHRATE=120
> 
> [HTTPJOB]
> MAIN=HTTP_START
> ENVIRONMENT=r23
> 
> [HTTPV11]
> Enable=1
> Sockets=HTTPREST
> 
> [HTTPREST] 
> Port=666
> IPsBind=
> URIs=HTTPURI
> Security=0
> 
> [HTTPURI]
> URL=/rest
> PrepareIn=
> Instances=1,1
> ```
> 
> e o seguinte fonte de teste:
> 
> ```
> #include "protheus.ch"
> #include "restful.ch"
> WsRestful RestTesteDebug Description "API REST para testes"
> 
>     WsMethod GET Description "Sincronização de dados via GET"    WsSyntax "TESTREST"
>     
> 
> End WsRestful
> 
> WsMethod GET WsService RestTesteDebug
> local nx
> 
> For nx := 1 to 10
>     conout("Teste no rest")
> next 
> 
> ::SetResponse("Feito")        
> Return .T.
> ```
> 
> Fazendo um get em:
> 
> http://localhost:666/rest/RestTesteDebug/TESTREST
> 
> Como eu já disse, o comportamente de debugar thread que já iniciaram não é bem definido no appserver.
> 
> Por isso prefiro a solução abaixo, que sempre funciona, indepedente da versão do server.
> 
> Primeiro desligo a subida automatica do rest no server:
> 
> ```
> [ONSTART]
> ;JOBS=HTTPJOB
> REFRESHRATE=120
> ```
> 
> Depois deixo essa user function compilada no rpo:
> 
> ```
> 
> User function start_debug()
> 
> StartJob("HTTP_START",getEnvServer(),.f.)
> Alert("fica parado")
> 
> 
> Return
> ```
> 
> Sempre que preciso debugar o servico, apenas chamo o debug com u_start_debug, deixo parado no alert e chamo a API. Esse é ideal.
> 
> Espero que ajudem vocês. Como não tenho mais windows aqui para testar não consigo fazer eu mesmo o teste. Porem pedi para um colega aqui testar no windows e teve sucesso.
> Qualquer coisa me falem.
> 
> Attt.

Boa tarde @killerall , 

segundo a documentação do VsCode, as configurações de Workspace sobrepõem as configurações de usuário. Como padrão de utilização das outras configurações que você fez, eu utilizei a Api ``vscode.workspace`` para alterar as configurações. 

Dei uma olhada no **Utils.ts** onde tem a função que retorna as configurações em JSON, e você usou a mesma Api:
```javascript
export function getConfigurationAsString(): string{
    return JSON.stringify(vscode.workspace.getConfiguration("advpl"));
}
```

Vou fazer alguns testes com as configurações nos dois lugares e utilizando os dois cenários (com e sem Workspace) para verificar o comportamento do VsCode e te retorno.

**Comment by antunesls** [comment]
@killerall @AlencarGabriel @igormorse ,

Consegui aqui !!!

Desinstalei as outras extensões e configurei novamente o workspace e funcionou.

Obrigado pelas dicas e por me avisar que eu estava utilizando a extensão errada.

**Comment by igormorse** [comment]
> @igormorse e @antunesls
> Acabei de fazer um teste inteiro aqui.
> 
> Algumas informaçóes importantes:
> 
> * Testei tudo no linux.
> * Precisa se atentar se o "advpl.debug_multiThread" esta como true.
>   (Tive um conflito de configuração, pois o vscode tem setting por usuario e por workspace. @AlencarGabriel , se conseguir dar uma olhada o seu botão em baixo de ativar ou nao o multi-thread so muda se tiver workspace) , ou seja, confira nos dois settings, se não tem um ativado e outro não, e deixei em apenas 1 lugar.
> 
> Fiz primeiro um teste no pior cenario, que é as threads do Rest ja esta iniciadas, e inicio o debug depois. Consegui debugar normalmente, com a seguinte configuração de rest:
> 
> ```
> [ONSTART]
> JOBS=HTTPJOB
> REFRESHRATE=120
> 
> [HTTPJOB]
> MAIN=HTTP_START
> ENVIRONMENT=r23
> 
> [HTTPV11]
> Enable=1
> Sockets=HTTPREST
> 
> [HTTPREST] 
> Port=666
> IPsBind=
> URIs=HTTPURI
> Security=0
> 
> [HTTPURI]
> URL=/rest
> PrepareIn=
> Instances=1,1
> ```
> 
> e o seguinte fonte de teste:
> 
> ```
> #include "protheus.ch"
> #include "restful.ch"
> WsRestful RestTesteDebug Description "API REST para testes"
> 
>     WsMethod GET Description "Sincronização de dados via GET"    WsSyntax "TESTREST"
>     
> 
> End WsRestful
> 
> WsMethod GET WsService RestTesteDebug
> local nx
> 
> For nx := 1 to 10
>     conout("Teste no rest")
> next 
> 
> ::SetResponse("Feito")        
> Return .T.
> ```
> 
> Fazendo um get em:
> 
> http://localhost:666/rest/RestTesteDebug/TESTREST
> 
> Como eu já disse, o comportamente de debugar thread que já iniciaram não é bem definido no appserver.
> 
> Por isso prefiro a solução abaixo, que sempre funciona, indepedente da versão do server.
> 
> Primeiro desligo a subida automatica do rest no server:
> 
> ```
> [ONSTART]
> ;JOBS=HTTPJOB
> REFRESHRATE=120
> ```
> 
> Depois deixo essa user function compilada no rpo:
> 
> ```
> 
> User function start_debug()
> 
> StartJob("HTTP_START",getEnvServer(),.f.)
> Alert("fica parado")
> 
> 
> Return
> ```
> 
> Sempre que preciso debugar o servico, apenas chamo o debug com u_start_debug, deixo parado no alert e chamo a API. Esse é ideal.
> 
> Espero que ajudem vocês. Como não tenho mais windows aqui para testar não consigo fazer eu mesmo o teste. Porem pedi para um colega aqui testar no windows e teve sucesso.
> Qualquer coisa me falem.
> 
> Attt.

@killerall 

Esse método funcionou!!!! E ainda facilita o problema de acesso exclusivo por compilação rs.

Muito obrigado pelo suporte e pela paciência.

Sabe me dizer se a outra extensão possuí as mesmas funcionalidades que esta e se está estável também ?

O VSCode irá substituir o TDS no futuro ?

**Comment by killerall** [comment]
@igormorse 
Disponha.
Sobre a extensão do TDS, não sei responder, nunca testei. Não sei qual é os planos deles.
