### ISSUE TITLE
Bridge retornar os ambientes

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#331]
Boa tarde @killerall ,

é possível implementar um comando no VsCode que retorne todos os ambientes (RPO) configurados no INI do AppServer que está conectado?

Estou com algumas ideias de melhoria, adicionando uma nova View no Explorer do VsCode onde o usuário possa gerenciar os servidores (semelhante o do TDS mas utilizando as configurações da extensão). Daí essa View aproveitaria o Wizard de Environments para configurar os ambientes. 

Fico no aguardo de seu retorno.

**Comment by killerall** [comment]
Boa tarde,
Da pra fazer isso. Porem estou com muito pouco tempo para consegue mandar isso formatado.
O que consigo fazer rapido, é retornar o INI inteiro pra você em typescript. Ai teria que fazer o parser do ini do server do seu lado. 

Se isso te atender me avise que faço isso.

**Comment by AlencarGabriel** [comment]
Tudo bem, isso atende. 

Tratar o INI não é o problema, a maior dificuldade seria ler realmente o INI.

**Comment by AlencarGabriel** [comment]
Aproveitando o assunto, seria possível estender este recurso para também gravar uma alteração no INI? Pergunto isso pensando em um recurso que ajudaria muitas empresas, para troca a quente de RPO.

**Comment by killerall** [comment]
Escrita no ini não vai rolar.
A leitura vou tentar fazer rapido para liberar pra você fazer o resto da implementação.

**Comment by AlencarGabriel** [comment]
Sem problemas, fico no aguardo então da leitura.

**Comment by killerall** [comment]
@AlencarGabriel 
Acabei de subir na master a alteração do executavel para conseguir pegar o ini.
Ele só funciona no alfa. Precisa passar --getIni pra ele, no mesmo moldes da compilação.

Qualquer coisa me avisa.

**Comment by AlencarGabriel** [comment]
Ótimo, vou fazer o Pull aqui no meu repositório e te mantenho informado.

Obrigado desde já!

**Comment by AlencarGabriel** [comment]
Boa tarde @killerall , o Bridge não está retornando o evento `data`.  Estou usando os binários da Alpha conforme informado (``this.debugPath > "c:\Users\gabriel.s\Documents\GitHub\advpl-vscode\bin\alpha\win\AdvplDebugBridgeC.exe``), e estou passando os seguintes argumentos:

- 1 `"--compileInfo={"projectActive":"Projeto Erro Zero","onlyRelatedEnvironments":true,"foldersProject":[{"path":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\Branches\\ProtheusClean\\src","name":"Protheus Clean","environments":[]},{"path":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\Branches\\Projeto_62_GPE\\src","name":"Projeto 62 GPE","environments":["PILOTO V - PILOTO V","PILOTO V - GABRIEL","PILOTO V - WS Rest","PILOTO VI - PILOTO VI","PILOTO VI - GABRIEL"]},{"path":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\BRA P12","name":"Brametal P12"},{"path":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\trunk3\\src","name":"Trunk 3","environments":["OFICIAL 98 - BRAMETAL","OFICIAL 98 - GABRIEL","OFICIAL 99 - NFE","OFICIAL 98 - GUILHERME","OFICIAL 98 - COMP","OFICIAL RM - RM","SLV05 WS RIFe - BRAMETAL"]},{"path":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\Branches\\Projeto_Erro_Zero\\src","name":"Projeto Erro Zero","environments":["PILOTO VI - GABRIEL","PILOTO VI - PILOTO VI","PILOTO V - PILOTO VI","PILOTO V - PILOTO V","PILOTO V - GABRIEL"]}],"selectedEnvironment":"PILOTO V - GABRIEL","enableCoverage":"true","workspaceFolders":"c:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\Branches\\Projeto_Erro_Zero\\src;","environments":[{"smartClientPath":"C:\\smartclient\\","environment":"HARLEY","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.3","port":"1214","user":"admin","name":"DEV II - HARLEY","passwordCipher":"M0lzcjJDU0ZUUitlTUVYckVHcWNxeWp6MzNnQlFyQVVzZkNHM1Z0YzMxUzJTOGFtZFlXaUN4VEZ0L0VRT3M5TkVCaVJPakxycWlldTZtZ0RoYzBkbVJoc0RobHFwYzVVZzRxVmFNcW5BczJFaTRMSElPY1RvQm9xWHF4VDVKb08=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"NFE","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6099","user":"admin","name":"OFICIAL 99 - NFE","passwordCipher":"R2tMcjRENXZDSFptbm1sVkRUakxRSjU4TTZ3RU8zVDBobCszYzFlL0FrTXN4V3JVQXBYd01Qc1FRTEx6OEtQSkc3ektvRmUrZVZaVW9ORUdKQ1AxL0JnWitrRkgvaHJyTXdXNndJYnlSaXpSN29VYUpxQmZIbmhTQzVPVlllM2k=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"RM","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6097","user":"admin","name":"OFICIAL RM - RM","passwordCipher":"cVRKWE5jUkE3ZjE4UFFKb3kvVUJYWGpPT2RyUkxteEg3bFNFUmkxMnhrY0JJalZyZTN2MXdjSjI1RjJSU0JGSk9NUW9CSjlMSG9UdUx1OUFLcmdWU2dJaGpNcWVzTXVqbGRHcGlHSWFQcnNFWUUvS2lMbWg0UFkxTWthU2VEVEQ=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"COMP","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6098","user":"admin","name":"OFICIAL 98 - COMP","passwordCipher":"R2tMcjRENXZDSFptbm1sVkRUakxRSjU4TTZ3RU8zVDBobCszYzFlL0FrTXN4V3JVQXBYd01Qc1FRTEx6OEtQSkc3ektvRmUrZVZaVW9ORUdKQ1AxL0JnWitrRkgvaHJyTXdXNndJYnlSaXpSN29VYUpxQmZIbmhTQzVPVlllM2k=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"GABRIEL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6098","user":"admin","name":"OFICIAL 98 - GABRIEL","passwordCipher":"R2tMcjRENXZDSFptbm1sVkRUakxRSjU4TTZ3RU8zVDBobCszYzFlL0FrTXN4V3JVQXBYd01Qc1FRTEx6OEtQSkc3ektvRmUrZVZaVW9ORUdKQ1AxL0JnWitrRkgvaHJyTXdXNndJYnlSaXpSN29VYUpxQmZIbmhTQzVPVlllM2k=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"GUILHERME","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6098","user":"admin","name":"OFICIAL 98 - GUILHERME","passwordCipher":"R2tMcjRENXZDSFptbm1sVkRUakxRSjU4TTZ3RU8zVDBobCszYzFlL0FrTXN4V3JVQXBYd01Qc1FRTEx6OEtQSkc3ektvRmUrZVZaVW9ORUdKQ1AxL0JnWitrRkgvaHJyTXdXNndJYnlSaXpSN29VYUpxQmZIbmhTQzVPVlllM2k=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"BRAMETAL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.5","port":"6098","user":"admin","name":"OFICIAL 98 - BRAMETAL","passwordCipher":"R2tMcjRENXZDSFptbm1sVkRUakxRSjU4TTZ3RU8zVDBobCszYzFlL0FrTXN4V3JVQXBYd01Qc1FRTEx6OEtQSkc3ektvRmUrZVZaVW9ORUdKQ1AxL0JnWitrRkgvaHJyTXdXNndJYnlSaXpSN29VYUpxQmZIbmhTQzVPVlllM2k=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"BRAMETAL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.138","port":"5084","user":"admin","name":"SLV05 WS RIFe - BRAMETAL","passwordCipher":"aVNGR2Y3N0R4QkJtNE9Ga2hSeEhPWXVWdnhHN0xzWEFKbFlnWEhFK0pRZHdJbTlITU5ST1ppRVBZVGYycFZsUTBtTlhVakJhRUVpY3hBWUtCbU1IRnljRXBTS1NzZXpIbk9WWElqZlBTN2dKcUpwWGdVcDU3a2xCWW9oSFhBb1I=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"BRAMETAL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"5083","user":"admin","name":"PILOTO V - WS Rest","passwordCipher":"WGNjVXhaRE43L21sT0ZGdzArVEFmMXEwU1U5Nnp6QkZWQ1FsRlZKTUZnUnlRbThHRVp4c2hiNlBqRFRtK2Q2QkR2N3cxMVBjWkZGclZoMTJmL3JFNnBPb3Z3VTFVRW92S21kbitDMjRMWjB0TW42amU5RWVQcnhXanhMZXZYUWY=","enable":false},{"smartClientPath":"C:\\smartclient\\","environment":"GABRIEL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"5098","user":"admin","name":"PILOTO V - GABRIEL","passwordCipher":"WGNjVXhaRE43L21sT0ZGdzArVEFmMXEwU1U5Nnp6QkZWQ1FsRlZKTUZnUnlRbThHRVp4c2hiNlBqRFRtK2Q2QkR2N3cxMVBjWkZGclZoMTJmL3JFNnBPb3Z3VTFVRW92S21kbitDMjRMWjB0TW42amU5RWVQcnhXanhMZXZYUWY=","enable":true},{"smartClientPath":"C:\\smartclient\\","environment":"PILOTO5","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"5098","user":"admin","name":"PILOTO V - PILOTO V","passwordCipher":"WGNjVXhaRE43L21sT0ZGdzArVEFmMXEwU1U5Nnp6QkZWQ1FsRlZKTUZnUnlRbThHRVp4c2hiNlBqRFRtK2Q2QkR2N3cxMVBjWkZGclZoMTJmL3JFNnBPb3Z3VTFVRW92S21kbitDMjRMWjB0TW42amU5RWVQcnhXanhMZXZYUWY=","enable":true},{"smartClientPath":"C:\\smartclient\\","environment":"GABRIEL","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"6098","user":"admin","name":"PILOTO VI - GABRIEL","passwordCipher":"aSJeWR+DYQsE5SPi4TTsZqQDE4Ont/pF8jYH8YqEDS4+vBaruY26n37zNZjzicYdAAxbTNN0oSmAavyQWwMIV08L=","enable":true},{"smartClientPath":"C:\\smartclient\\","environment":"PILOTO6","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"6098","user":"admin","name":"PILOTO VI - PILOTO VI","passwordCipher":"Y3V6TjlwTVp1eDdmRHVFZnlxUzJtM3VjcDRhdlhiUURXQnFtdENCeis1OHBvaURXREFROXVQZE83bU9mVW9taGpKbW1LcFExWWtGVGJRZWk3K2xMUmhFRHRacUVUQ0p6d0ZWQ0xhL2hwSktNTkx2SUxJeWkyTkd4OGV6Zk5oZSs=","enable":true},{"smartClientPath":"C:\\smartclient\\","environment":"PILOTO6","includeList":"C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\","server":"192.168.50.31","port":"5098","user":"admin","name":"PILOTO V - PILOTO VI","passwordCipher":"L2VTT0hTcHkwQ29Ed0hXK0FITlBiU2kzek1xUXllN3RvRGJ4aGkxR21HVGtQM2w1Mm9DSkVVeVZSc2xXTVh6blZpcXU2U1NibnE5QWEyZktyUEM0Q0krbmZUdFk0eEtCSnBBQTRqYlBkNXdYZkE0dHk0Mnp4bGNRUkxaNEJqQzc=","enable":true}],"startProgram":"SIGAMDI","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl|tlpp|4gl|per|msg|ahu)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":false,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":false,"compile_force_recompile":true,"logger":false,"compile_threads":4,"alpha_compile":true}"`

- 2 `"--getIni"`

Obs.: Compilação e outros comandos funcionam, implementei copiando o método de desfragmentação.

Gist com os exemplos mais completos: [https://gist.github.com/AlencarGabriel/b5253fbe6864a8968286d5ecb0ec7aa8](https://gist.github.com/AlencarGabriel/b5253fbe6864a8968286d5ecb0ec7aa8)

**Comment by killerall** [comment]
@AlencarGabriel Eu acabei de subir uma alteração(windows apenas) para retornar erro caso algo esteja errado.
Provavelmente deu alguma coisa de conexa invalida e não mostrou nada.
Da um pull ai e me fala.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall , ainda nada. Não retorna nenhuma mensagem.

Tentei com o evento ``stdout.on("error")`` pra ver se retornava algo, mas esse evento não foi chamado.

Nem mesmo se chamar via linha de comando o AdvplDebugBridgeC.exe passando os mesmos argumentos da extensão tem retorno.

**Comment by killerall** [comment]
@AlencarGabriel Pega a versão que acabei de subir. Ve se vai.

**Comment by AlencarGabriel** [comment]
Agora sim @killerall , funcionou certinho! Vou simular alguns erros e tentar tratá-los tambem.

Vou iniciar as implementações que comentei a partir de hoje a noite. Agradecido!

**Comment by AlencarGabriel** [comment]
@killerall , implementei o comando ``advpl.getIni`` para abrir o INI no editor para testar o Bridge.

Acha interessante manter este comando para o usuário recuperar o INI, ou eu removo e trato apenas internamente sem retornar de nenhuma forma o INI para o usuário?

**Comment by killerall** [comment]
Não vejo problema em deixar aberto para o usuario.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall ,

apenas como demonstração e para reforço que estou atuando na melhoria desta issue (aos pouquinhos), segue um GIF da view de gerenciamento de ambientes. 

O tratamento dos ambientes do INI já está feita, só falta agora alguns outros detalhes de localização e submenus. Obs.: A maioria dos comandos de contexto que adicionei estão chamando os comandos já  registrados da extensão.

![Demonstracao](https://user-images.githubusercontent.com/10109480/60188798-42d51f80-9806-11e9-8ba1-26925ac62893.gif)

Caso queira comentar sobre algo, o projeto está nesse Branch: https://github.com/AlencarGabriel/advpl-vscode/tree/servers-view

**Comment by killerall** [comment]
Bom dia,
Parece que esta ficando bacana. 
Sobre o seu ultimo pull-request, estou acertando alguns pontos na versao linux do bridge, e devo liberar em breve.
Vlw

**Comment by AlencarGabriel** [comment]
@killerall , boa tarde.

Em qual diretório devo adicionar as localizações que estou criado, nos arquivos **package.nls.--.json** da raiz da **SRC**, ou dentro da pasta **i18n**?

**Comment by killerall** [comment]
Opa boa tarde.

Não sei dizer direito.

Esse link ajuda?

https://github.com/totvs/advpl-vscode/wiki/Localiza%C3%A7%C3%A3o

Senão precisa ver o commit do Victor que fez a localizacao.

**Comment by AlencarGabriel** [comment]
Boa tarde,

dei uma lida agora nessa Wiki, esclarecedora. 

A compilação com o Gulp você faz na hora de gerar a nova versão?

Outra pergunta, vou desenvolver uma Wiki sobre essa nova feature da extensão, quanto estiver pronta e com a release expedida posso te mandar como um Gist privado e você adiciona aqui no GitHub?

**Comment by killerall** [comment]
Sim o Gulp faz na geracao.
Blz, wiki vc não consegue fazer pull wiki?

**Comment by AlencarGabriel** [comment]
Beleza.

Sobre a sua pergunta, se não me engano o GitHub não tem suporte para Pull de Wiki, somente os colaboradores autorizados de um repositório podem gerenciar as Wiki Pages.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall ,

a previsão para a próxima atualização da extensão é quando? Pergunto isso pois estou finalizando as traduções desta melhoria, e dependendo de sua resposta, poderíamos ir testando e se possível já sair na próxima versão. 

Eu tenho utilizando a melhoria em modo Debug pra ir testando os recursos.

**Comment by killerall** [comment]
Temos algumas poucas alterações. Quando vc terminar a sua implementação podemos lancar.

**Comment by AlencarGabriel** [comment]
@killerall , tudo certo aqui para abrir o Pull Request. 

Poderia criar um branch novo aqui para não misturar as alterações direto na master?

**Comment by killerall** [comment]
Eu criei uma branch baseada na master 
https://github.com/totvs/advpl-vscode/tree/feature-server
Se quiser subir .

**Comment by AlencarGabriel** [comment]
@killerall , boa tarde. 

Subi ontem a Pull e finalizei a alteração da #341. 

Aguardando seu retorno e os possíveis feedbacks caso seja necessário ajustar algo.

**Comment by killerall** [comment]
Boa tarde.
Vou faz uma geracao a partir da usa implementação e pedir para o pessoal da equipe aqui usar uns dias. Para ver se nao colateral em nada. Ai publico.
Obrigado.

**Comment by AlencarGabriel** [comment]
Você sobrescreve o pacote na pasta de extensões do VsCode? Como faz para outros testarem sem estar depurando a extensão?

Estou pensando em pedir para o pessoal testar aqui tambem.

**Comment by killerall** [comment]
Instala o VSCE
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

ai na raiz vc faz:

vsce package

Isso vai gerar a instalacao da extensao via VISX

Para instalar, basta clicar no icone das extensões, ... install from visx

**Comment by AlencarGabriel** [comment]
Hummm... Eu uso o vsce pra publicar a minha extensão de gerenciamento de projetos.

Não sabia do recurso pra gerar o pacote. Boa, vou fazer aqui. Obrigado!

**Comment by AlencarGabriel** [comment]
@killerall , gerei o pacote da extensão, e ao instalar (tanto em minha maquina quanto em uma sem nenhuma extensão) os comandos da extensão não funcionam. Aparece: `command 'advpl.selectEnvironment' not found`.

Atualizei o pacote inteiro do vsce pra garantir e nada... Já aconteceu algo parecido com você?

**Comment by killerall** [comment]
Fiz o teste aqui, 
Esta dando problema no 

var INI = require('ini');

/usr/share/code/reso…kbench.main.js:3210 Activating extension 'KillerAll.advpl-vscode' failed: Cannot find module 'ini'.
_logMessageInConsole	@	/usr/share/code/reso…kbench.main.js:3210

Precisa colocar ele no package.json provalvemente.

Quando der erro assim, abra no Help -> Toggle developer Tools e va no console. La que da o erro de load da extensão.

**Comment by AlencarGabriel** [comment]
Realmente, o meu estava dando o mesmo erro.

Nos meus pacotes npm tinha o modulo **ini**, mas quando gerava o pacote vsce não ia porque não estava no package.

Vou subir a alteração. Inclusive, tive que reajustar o pacote da lib do vscode, pois agora tem que usar o `@types/vscode` nas dependências.

**Comment by AlencarGabriel** [comment]
Subi a correção e realmente agora funcionou. Obrigado @killerall .

Qualquer outro problema pode me informar.

**Comment by killerall** [comment]
@AlencarGabriel 
Estou tentando buildar a sua branch (fiz clone direto do seu repositorio).
dando npm install, e depois tentando fazer a build, da uns 500 erros.

Acho que te a ver pq vc atualizou alguns pacotes do vscode,  e nao o fez do geral.

Consegue dar uma olhada?

**Comment by AlencarGabriel** [comment]
Boa tarde,

vou dar uma olhada agora, muito estranho... Vou fazer um novo clone pra tentar simular e retorno aqui...

**Comment by AlencarGabriel** [comment]
@killerall , acho que agora vai.

Eu havia adicionado no meu package a dependência `"@types/vscode": "^1.30.0"` por conta de alguns problemas que estava tendo quando fazia o clone do seu repositório.

Mas pelo que vi, se eu apagar o **package-lock.json** que vem do seu repositório e deixar o npm recriá-lo com o `npm install` ele baixa o arquivo **vscode.d.ts** que não estava vindo, causando erros na hora de  compilar a extensão.

Como eu fiz o processo do zero pra simular a sua situação, o npm duplicou as referencias das classes do VsCode, ajustei aqui e fiz tudo do zero e consegui tanto compilar quanto gerar os pacotes.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall ,

conseguiu gerar o pacote?

**Comment by killerall** [comment]
Consegui sim.

Vou deixar o pessoal testar.

**Comment by killerall** [comment]
@AlencarGabriel 
No linux, ao tentar abrir a extensao sem o meu ambiente estar no ar. Ta dando erro:

eError [ERR_INVALID_CALLBACK]: Callback must be a function
	at makeCallback (fs.js:137)
	at Object.unlink (fs.js:917)
	at ChildProcess.<anonymous> (/home/rodrigo/.vscode/extensions/killerall.advpl-vscode-0.11.3/out/src/utils/debugBridge.js:88)
	at ChildProcess.emit (events.js:182)
	at Process.ChildProcess._handle.onex

Você esta tentand acessar o ini logo no start up ?
Outro ponto. Seria interessante ter um cfg. Para desabilitar o env que você criou. Por que sempre tem alguem que não curte.

**Comment by AlencarGabriel** [comment]
> @AlencarGabriel
> No linux, ao tentar abrir a extensao sem o meu ambiente estar no ar. Ta dando erro:
> 
> eError [ERR_INVALID_CALLBACK]: Callback must be a function
> at makeCallback (fs.js:137)
> at Object.unlink (fs.js:917)
> at ChildProcess. (/home/rodrigo/.vscode/extensions/killerall.advpl-vscode-0.11.3/out/src/utils/debugBridge.js:88)
> at ChildProcess.emit (events.js:182)
> at Process.ChildProcess._handle.onex
> 
> Você esta tentand acessar o ini logo no start up ?

@killerall , a chamada pra buscar o INI é feita somente quando o comando GetIni é executado ou o usuário clica com botão direito no Serviço lá no Gerenciador de Ambientes e manda importar os ambientes.

Inclusive só funciona na Alpha...

> Outro ponto. Seria interessante ter um cfg. Para desabilitar o env que você criou. Por que sempre tem alguem que não curte.

Você diz uma configuração para não aparecer a View de Gerenciamento de Servidores?

**Comment by AlencarGabriel** [comment]
> eError [ERR_INVALID_CALLBACK]: Callback must be a function
> at makeCallback (fs.js:137)
> at Object.unlink (fs.js:917)
> at ChildProcess. (/home/rodrigo/.vscode/extensions/killerall.advpl-vscode-0.11.3/out/src/utils/debugBridge.js:88)
> at ChildProcess.emit (events.js:182)
> at Process.ChildProcess._handle.onex
> 

A linha 88 do **debugBridge.js** é um trecho que descompacta um arquivo:

``` javascript
 fs.unlink(path + 'AdvplDebugBridge-linux.tar.gz');
```

**Comment by killerall** [comment]
Sim, uma cfg para nao aparecer a view.

**Comment by AlencarGabriel** [comment]
> Sim, uma cfg para nao aparecer a view.

Depois das ultimas atualizações do VsCode, ele tem um recurso para esconder uma View.

![image](https://user-images.githubusercontent.com/10109480/61640356-8c812080-ac73-11e9-91a7-0a16b0408e4b.png)

A gente pode adicionar isso na Wiki que estou montando. 

Falo isso pois quando estava desenvolvendo a View, não achei uma forma de de esconder isso usando as configurações, somente usando algumas key bindings, pois eu registrei a View pelo **package.json** .

https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by killerall** [comment]
@AlencarGabriel 
Acabei de integrar os 2 pull request a branch da feature.

Quero a tem o fim da semana mandar pra master. Por hora, se puder baixe essa feature, gere uma versão e vai usando ( eu subi mais 1 update no Bridge). Vou gerar aqui tambem e usar aqui. Se não tiver problemas libero no fim da semana,

**Comment by AlencarGabriel** [comment]
Beleza, vou fazer atualizar meus fontes e gerar o pacote.

**Comment by AlencarGabriel** [comment]
> Ps.
> Eu gerei aqui, os icones nao estão aparecendo.

Para que os icones apareçam é necessário que seja executado o comando ``workbench.action.selectIconTheme`` (Preferences: File Icon Theme) e selecionar o tema **AdvPL Icons** . 

Procurei uma forma de deixar isso pré-definido, mas não encontrei.

**Comment by AlencarGabriel** [comment]
@killerall , terminei a Wiki para você adicionar aqui no GitHub. 

Segue link do Gist: https://gist.github.com/AlencarGabriel/7a3cfe2b78168a1deb3aaedf93f872aa

**Comment by AlencarGabriel** [comment]
@killerall , para feedback eu e a equipe interna aqui testamos a extensão, e os recursos que foram implementados (icones, comandos, importar ambientes). Não tivemos mais nenhum problema (obs.: usamos dessa vez o Bridge normal, não o Alpha).

Acredito que já podemos liberar a versão, e a Wiki te mandei no comentário acima. 

Como foi os testes ai?

**Comment by AlencarGabriel** [comment]
Bom dia @killerall , a feature sai essa semana?

**Comment by killerall** [comment]
Bom dia,
Espero que sim. Desculpe a demora em responder, mais estou bem enrolado esses dias.

**Comment by AlencarGabriel** [comment]
Sem problemas, eu imagino e entendo.

Fico no aguardo então, e se precisar de algo estou a disposição.

**Comment by killerall** [comment]
@AlencarGabriel 
Eu já atualizei a WIki.
Hoje a noite vou fazer a geração da versao para MACOS, e se tudo der certo, amanha libero.
O Link da Wiki ficou:

https://github.com/totvs/advpl-vscode/wiki/Gerenciador-de-Ambientes

**Comment by AlencarGabriel** [comment]
Ótimo @killerall . Dei uma olhada aqui, muito obrigado!

Só vou te pedir pra puxar pra Master também meu outro Pull mais antigo, ele é sobre aquela issue que você abriu referente ao uso de CPU na animação do ícone de multi thread.

Acho bacana também, esse eu acabei não fazendo, atualizar o readme inserindo o gerenciador de ambientes e suporte a ícones.

**Comment by killerall** [comment]
@AlencarGabriel Como eu suspeitva, deu ruim no MACOS, vou tentar um help amanha na totvs, para ver se consigo buildar amanha a noite.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall ,

agradeço por toda ajuda nesses últimos meses para que essa feature e outros recursos saíssem. Já estou repassando a informação para meus amigos. Obrigado tambem pelos agradecimentos.

Estou a disposição para estar atendendo as issues referente ao gerenciador de ambientes e ícones. Estou como observador da extensão, então recebo as notificações das issues!

**Comment by killerall** [comment]
Bom dia @AlencarGabriel 
Eu que agradeço, é o empenho da comunidade que faz projetos ficarem vivos.
Tambem vou ficar de olho nas issues.
Novamente, obrigado.

**Comment by AlencarGabriel** [comment]
@killerall , poderia fazer um pequeno ajuste na Wiki do Gerenciador de Ambientes?

Adicionar abaixo mais um item nesse trecho do artigo: https://github.com/totvs/advpl-vscode/wiki/Gerenciador-de-Ambientes#importar-ambientes

https://gist.github.com/AlencarGabriel/4b3c072baa4438585d581f29d831670c

**Comment by killerall** [comment]
Feito

**Comment by AlencarGabriel** [comment]
Obrigado!
