### ISSUE TITLE
Erro e travamento do VSCode apos compilação.

### ISSUE THREAD

**Issue by FrancisOliveira** [totvs/advpl-vscode#332]
Apos efetuar a compilação a mostrada uma tela de erro e o VSCode trava e é preciso fechar e reiniciar  .

Print com o erro em anexo .
[erro VSCODE.docx](https://github.com/totvs/advpl-vscode/files/3236678/erro.VSCODE.docx)

**Comment by killerall** [comment]
@FrancisOliveira 
Bom dia. Você está utilizando está extensão ou a extensao do TDS?

**Comment by FrancisOliveira** [comment]
Opa , 

Estava utilizando a extensao, TDS for VSCode 

Valeu

**Comment by FrancisOliveira** [comment]
Rodrigo , a Issue foi encerrada ?
