### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by pgeovane** [totvs/advpl-vscode#334]
Bom dia, ao tentar compilar gera o erro SyntaxError: Unexpected end of JSON input.

No debugbridge.log gera a mensagem abaixo:

"Thread[1] - 18/06/2019 12:04:30: IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿[P12HMLDEV]'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0 while parsing line number 1 with value 'ï»¿[P12HMLDEV]' - IniParser version: 2.4.0.0 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿[P12HMLDEV]'. while parsing line number 0 with value '' - IniParser  "

Não sei o que pode ser, meu appserver.ini está correto, tem horas que funciona e tem horas que apresenta esse erro.

**Comment by killerall** [comment]
Bom dia.

O seu ini esta com alguns caracteres invalidos no inicio dele.
Recomendo abrir o ini no notepad++, e clicar no icone que mostra caractres ocultos e remover o mesmo.

**Comment by pgeovane** [comment]
pensei a mesma coisa, já fiz isso e não tem nenhum caracter oculto.
[image: image.png]

**Comment by killerall** [comment]
Aqui tem caracteres invalidos:
 'ï»¿[P12HMLDEV

Se nao consegue ver no notepad++, faz o seguinte cria um arquivo novo pro ini. copia as coisas menos essa linha.

**Comment by pgeovane** [comment]
Eu já apaguei e digitei manual essa tag, inclusive se deixar uma linha em
branco ele apresenta o erro.
Não sei o que pode ser, pois como eu disse em alguns momentos funciona e
depois para de funcionar.

**Comment by pgeovane** [comment]
Na Issue abaixo o usuario identificou o motivo, fiz o procedimento por ele descrito e resolveu o problema:

https://github.com/totvs/advpl-vscode/issues/329
