### ISSUE TITLE
Consumo de CPU quando liga o Multi-thread

### ISSUE THREAD

**Issue by killerall** [totvs/advpl-vscode#336]
@AlencarGabriel tudo bem?
Consegue verificar se no windows tem o mesmo comportamento?

No linux aqui, quando clico em multi-thread, a animação do icone faz que o vscode gaste 10% mais cpu, do que com ele desligado.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall , 

realmente há um comportamento muito estranho quando a animação está sendo executada. 

Com ela parada o consumo varia entre 0,5% e 3% de CPU, com a animação sobe para 5% a 7%, não é uma diferença exorbitante, mas é considerável, visto que no dia a dia com a utilização vai aumentar o consumo.

Vamos retirar a animação ou verificar com a MS?

**Comment by killerall** [comment]
Então, se quiser tentar abrir uma issue la, não vejo problema. Só acho que seria bom deixar outro icone, enquanto isso.

**Comment by AlencarGabriel** [comment]
Vou mandar um Pull com a alteração.

**Comment by AlencarGabriel** [comment]
Fiz o Pull agora, porem achei estranho que foi junto um commit anterior meu que você já tinha feito Merge. 

Caso dê conflito me avise para que eu possa resolvê-lo, mas acredito que não terá, pois alterei direto na classe que eu criei para esse componente.
