### ISSUE TITLE
Não compila BeginSql com %NotDel%

### ISSUE THREAD

**Issue by alvessgustavo** [totvs/advpl-vscode#339]
Olá.

Ao tentar compilar um prw que tenha BeginSql utilizando %NotDel% ele não compila.

Att.
Gustavo Santos

**Comment by killerall** [comment]
Boa tarde,

Gustavo você utilizando a minha a extensão ou a do TDS?

Acabei de testar aqui, e compilou normalmente na minha.

**Comment by alvessgustavo** [comment]
Killerall, boa noite.

Creio que no TDS, confirmarei e logo mais documento aqui.

**Comment by alvessgustavo** [comment]
Killerall.

É no TDS, desconsidera o Issues.

Valeu pela atenção.
