### ISSUE TITLE
Can't connect to server:check serverVersion settings.

### ISSUE THREAD

**Issue by LuizGMX** [totvs/advpl-vscode#340]
Olá, estou tentando compilar um fonte e está dando esse erro de versão de servidor, lembrando que estou usando o LOBO GUARÁ.

```
Versão da Lib:20190131
Data da Lib: 20190215_910
Build AppServer: 7.00.170117A-20190212 - 64 bits
Build DbAccess: 20181212
Release do RPO:  12.1.023
Release do dicionário: 12.1.023
```

**Comment by killerall** [comment]
Para o lobo você precisa configurar a chave 

serverVersion: "170117A"

No ambiente que for novo.

**Comment by LuizGMX** [comment]
Opa, funcionou perfeitamente, muito obrigado!

**Comment by AlencarGabriel** [comment]
Olá @felipecanaveze ,

Aparentemente a configuração `serverVersion` do seu ambiente não coincide com a versão do appserver que está tentando conectar.

Ex.: 
- AppServer Harpia | `210324P` 
- AppServer Lobo Guará | `191205P` ou `170117A`

**Comment by felipecanaveze** [comment]
"name": "DESENV_TCLOUD",
            "smartClientPath": "C:\\Temp\\smartclient - cloud",
            "environment": "Desenv_et",
            "serverVersion": "210324P",
            "server": "00.0.155.163",
            "port": 1109,
            "user": "admin",
            "ssl" : false,
            //"enable": true,
            "passwordCipher": "RW5GdWU1OW01Ylo1ZFlBME5DRUloREJvWTRkOHl4VTk4Z3dUaTIvQitNZlpIbUFIYVppWWxXZ0FDU2NKbkw4ZjY1bm56R0pXQW1TZ3lOVEdKZzFRU3JT3dYWFlBOWFVQXl6VzhhKzRzOVpxWWhzYUF5aExoSjU=",
            "includeList": "F:\\TOTVS12T\\Protheus\\Protheus\\include\\"

**Comment by felipecanaveze** [comment]
Mto estranho, pq so da erro nele.

**Comment by killerall** [comment]
Esse ip esta correto?

"server": "00.0.155.163",

**Comment by killerall** [comment]
Eu já vi relatos de problemas de conexão com T-cloud por conta do tipo de firewall que tem na entrada la, mais nao tenho um ambiente para testar e ver, se poder me enviar o ip / porta env, user e senha por email, consigo debugar aqui pra ver se consigo resolver. meu email da totvs é rodrigo.antonio arroba totvs.com.br

**Comment by killerall** [comment]
ta literal, tira o arroba e os espaçoskkk so pra robo da pegar o email.

**Comment by killerall** [comment]
@felipecanaveze Te mandei uma email, se puder responder.
