### ISSUE TITLE
Validação de ambiente no Wizzard

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#341]
Bom dia @killerall ,

estava fazendo alguns testes aqui utilizando o Wizzard de criação de ambientes e me deparei com a seguinte situação causada por esta validação:

https://github.com/totvs/advpl-vscode/blob/820b5196b4de4efd01d75b0c8308448b376a3fd5/src/commands/addAdvplEnvironment.ts#L10-L24

Temos aqui na empresa várias bases PILOTO, e por mais que cada uma tenha um ambiente com um nome específico, temos também ambientes separados para cada analista, ex.: GABRIEL, DIOGO, VINICIUS, etc.

Sendo assim para configurar a base no VsCode temos feito "a mão" direto nos Settings, e diferenciando pelo atributo ``name``: PILOTO V - GABRIEL, PILOTO VI - GABRIEL, ...

Isto pode estar ocorrendo também com outros usuários, o que acha de tirar essa validação, ou validar tanto o ``name`` quanto o ``Environment`` juntos?

Obs.: Percebi essa situação testando o recurso de Add Servidor que estou implementando na View de Gerenciamento de Ambientes.

**Comment by killerall** [comment]
Bom dia,
Se eu bem me lembro, o Wizard foi implementado antes de ter o conceito da name do ambiente.
Se quiser alterar a validação não vejo problemas.

**Comment by AlencarGabriel** [comment]
Maravilha então. Vou fazer a alteração no branch que estou pra lançar no Pull Request.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall ,

qual a previsão para soltar a próxima versão? Estava de férias e retornei hoje, ai percebi que ainda não saiu.

**Comment by killerall** [comment]
Na verdade estava esperando um retorno seu.
O pessoal que testou ai não encontrou mais nada?
Agente usando aqui nao pegou nada.
Você me dando ok, eu preparo a liberação.

**Comment by AlencarGabriel** [comment]
Boa tarde, 

não encontramos problemas também não.

Os que nós dois identificamos foram ajustados, inclusive a modificação referente a esta issue está funcionando.

Apenas ressalto novamente que o comando --getINI só está implementado na Alpha, e muitos aqui não testaram a importação dos ambientes por conta disso, mas eu fiz vários testes e em todos tive resultados satisfatórios.

Outra coisa que você havia me solicitado era uma configuração para não mostrar a View, e lá na outra issue apresentei um recurso novo que esconde a view de forma mais intuitiva. 

Ao meu ver já estamos prontos para lançar essa feature. Estou finalizando a Wiki, acredito que deixo ela pronta até o final desta semana.

Também estou aguardando seu retorno referente a issue que abri para o suporte a ícones, mas esse é menos prioritário.

**Comment by killerall** [comment]
Bom dia,
A ideia é que as pessoas migrem para o alpha. Se achar que o pessoal não vai migrar, posso fazer no atual, mais isso levar um tempo.
Sobre a View, eu conheço o recurso, mais não tenho certeza se a maioria conhece. Como uso muitos outros plugin acaba meio poluindo. Mais não é uma grande problema acho.

Sobre o os icones te respondi la.

**Comment by AlencarGabriel** [comment]
> Bom dia,
> A ideia é que as pessoas migrem para o alpha. Se achar que o pessoal não vai migrar, posso fazer no atual, mais isso levar um tempo.
>> **R:** Você recomenda que seja utilizada a Alpha o tempo todo? Ou somente para utilização deste recurso novo?

---

> Sobre a View, eu conheço o recurso, mais não tenho certeza se a maioria conhece. Como uso muitos outros plugin acaba meio poluindo. Mais não é uma grande problema acho.
> > **R:** Estou deixando isso explícito na Wiki.

---

> Sobre o os icones te respondi la.
>> **R:** Criei o Pull.

**Comment by killerall** [comment]
O Alpha é o que uso no linux, e a versao MAC.
Eu queria manter apenas 1 codigo. Mais preciso de mais gente usando (principalmente no windows) para que eu possa virar a chave.
Como eu uso menos advpl do que antes, não sei se é 100% garantido mudar para o alpha. E o grande problema que vejo, é que tem que refazer o cipher, não da pra ser transparente pro usuario.

**Comment by AlencarGabriel** [comment]
Entendi. Eu utilizei por bastante tempo a Alpha implementando este recurso e testando no dia-a-dia.

Percebi inclusive algumas coisas que na normal não tem, como por exemplo em uma exception, aparece uma janela vermelha com o erro posicionado na linha do problema. 

Se realmente é difícil implementar este recurso na versão normal, eu posso deixar que o recurso de buscar o INI só funciona quando a config estiver habilitada. Fica a seu critério, pois isso só vai impactar na importação dos ambientes do AppServer e obtenção do INI.
