### ISSUE TITLE
Debug não mostrando as variáveis e tabelas na área de variáveis

### ISSUE THREAD

**Issue by igormorse** [totvs/advpl-vscode#343]
# Descrição

* Versão do VSCode: **1.36.1** ( Última versão até 16/07/2019 )

``` Workspace.json

"advpl.projectActive": "PROD",
"advpl.startProgram": "SIGAADV",
"files.encoding": "windows1252",
"advpl.debug_multiThread": false,
"advpl.debug_showTables": true,
"advpl.debug_showPrivates": true,
"advpl.debug_showPublic": true,
"advpl.debug_showStatics": true,
"advpl.workspaceFolders": "\\Documents\\TDS\\Workspace\\PROD;",
"advpl.alpha_compile": false,
"advpl.selectedEnvironment": "TESTJOB"
```

Funcionou algumas vezes mas de um tempo pra cá simplesmente não mostra mais esses dados na seção de variáveis, para depurar as variáveis e tabelas preciso utilizar o monitoramento ou passar o mouse em cima. 

Podem me ajudar ? Essa funcionalidade é muito útil e economiza bastante tempo!

Obrigado,
Igor Morse.

**Comment by killerall** [comment]
@igormorse 
O appserver do protheus esta enviando alguma informação diferente, que não devo estar tratantdo.

Você tem algum fonte que consegue postar aqui onde de o problema? Tipo um ponto de entrada?

**Comment by igormorse** [comment]
Bom Dia @killerall !

Então com qualquer fonte, vou dar um exemplo de um simples que já não funciona...

``` VSTEST

#include 'protheus.ch'
#include 'totvs.ch'

User Function VSTEST()

    Local cVarTest := 'Testando'

    if (!EMPTY(cVarTest))
        Alert(cVarTest)
    EndIf

Return
```

Colocando o BreakPoint no Alert a variável cVarTest não aparece. Poderia até abrir uma tabela e ela também não apareceria em Variables.

Como observação ( Pode ser válido para o problema que estou tendo ), instalei uma outra extensão para ADVPL no VsCode para ver como era porém desinstalei após algumas validações e mantive essa aqui. Não sei se isso contribuiu em alguma coisa para deixar fazer de funcionar.

**Comment by igormorse** [comment]
@killerall 

Descobri qual era o problema, mesmo com a extensão **Totvs Developer Studio for VSCode (AdvPL, TLPP e 4GL)** desabilitada ela estava interferindo no debug das variáveis.

Acho que é bom ficar registrado aqui o problema de compatibilidade das duas extensões, removi completamente ela e voltou a funcionar a questão do Debug.

**Comment by killerall** [comment]
Obrigado pela informação. Fica aqui o registro.
