### ISSUE TITLE
Error Code: 56 - Communication error: Failure receiving message

### ISSUE THREAD

**Issue by Donads** [totvs/advpl-vscode#344]
Versão do VSCode: 1.36.1
Versão da Extensão: 0.11.3

Ao tentar rodar o Debug pelo VSCode, desde a semana passada (acredito que tenha sido após a atualização do VSCode para a 1.36), recebo o erro abaixo:
![smartclient_2019-07-17_08-52-30](https://user-images.githubusercontent.com/26306694/61373837-3c6c1d80-a871-11e9-90e4-c4b57c386552.png)

Nesse período não realizei nenhuma alteração no 'launch.json', nem no 'settings.json':
![Code_2019-07-17_08-56-19](https://user-images.githubusercontent.com/26306694/61374027-b2708480-a871-11e9-84c4-4e7f9b709625.png)
![Code_2019-07-17_08-57-55](https://user-images.githubusercontent.com/26306694/61374031-b56b7500-a871-11e9-837e-9781f0b85377.png)

Inicialmente até pensei que pudesse ser algum problema no servidor, mas o debug pelo TDS está funcionando perfeitamente.

**Comment by killerall** [comment]
Tenta fazer um teste.
desabilita:
"advpl.debug_showTables" : false,
"advpl.debug_showStatic" : false,

**Comment by Donads** [comment]
Acabei de testar desativando o showTables e showStatics para 'false' e o problema continua.
Testei desativando também o showPrivates e showPublic, ainda sem sucesso.
Por último, testei sem essas 4 configurações, e o problema persiste.

Consigo gerar algum log da extensão pra auxiliar?

**Comment by killerall** [comment]
Voce esta usando que versao do prothues? Do binario mais especificamente.

**Comment by Donads** [comment]
Segue abaixo dados completos:

![smartclient_2019-07-17_10-57-49](https://user-images.githubusercontent.com/26306694/61381661-c45a2380-a881-11e9-8d1f-9facba86c517.png)

**Comment by killerall** [comment]
Estranho isso.
O servidor esta local? Ou esta na rede?
Parece que caindo a conexao.

**Comment by Donads** [comment]
O servidor fica em Cloud da TOTVS.

Pois é, de início achei que era um problema relacionado à atualização do VSCode (especialmente por nessa versão ter sido destacada uma nova função pra debugging "Jump to Cursor"), então aguardei uns dias pra ver se a extensão era atualizada, mas quando consultei nas issues hoje vi que não houve mais nenhum relato deste problema então assumi que fosse um problema específico meu.
No meio tempo, instalei agora a "Totvs Developer Studio for VSCode" pra não ter que ficar usando o TDS hehe.

Hoje na parte da noite farei um teste tentando executar do meu PC de casa e retorno aqui com os resultados. De qualquer forma, desde já agradeço pela atenção e agilidade nas respostas!

**Comment by killerall** [comment]
A extensão do TDS entra em conflinto com esta. Deixe apenas 1 habilitada por vez.

Você não é o primeiro que relata quedas quando esta no Cloud. Eu vou tentar ver um servidor la, para tentar simular essa questão.

**Comment by Donads** [comment]
Testei ontem e casa e funcionou normalmente. Pelo visto o problema é local, então tentarei isolar se alguma extensão ou configuração diferente está causando isso.

Ainda assim, muito obrigado pela atenção!
