### ISSUE TITLE
Continuação da extensão

### ISSUE THREAD

**Issue by silfar** [totvs/advpl-vscode#345]
Pessoal desculpem o off, mas não sabia onde perguntar isso. Agora com o lançamento da extensão oficial da totvs, vcs vão manter o desenvolvimento ?
E poderiam me dizer quais as diferenças entre as extensões ?

**Comment by killerall** [comment]
As duas extensões são "oficiais" por assim dizer. ( Inclusive estão no github da Totvs).
Está extensão que foi pioneira no que se diz respeito a suporte do Advpl no VScode tem o intuito de ser leve, com o foco no dev.

A extensão do TDS, pelo que vi, me aparenta ter o objetivo de trazer a experiencia mais parecida com o TDS feito no eclipse.
