### ISSUE TITLE
Ícones na Extensão

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#346]
![image](https://user-images.githubusercontent.com/10109480/61541871-d5886900-aa16-11e9-8e22-98abcb14d619.png)

Bom dia @killerall ,

estava pensando em fazer a implementação do suporte a ícones para a extensão, e gostaria de saber se a TOTVS possui alguma documentação de padronização da Logo para Icones, ou haveria alguma restrição no uso da logo para este fim.

Suporte a ícones é uma implementação simples pelo visto, mas gostaria de saber se teria que ter o trabalho de criar um ícone específico para cada extensão suportada (prw, tlpp, ptm, prx, etc), ou usar apenas a logo da TOTVS em todos os arquivos suportados.

**Comment by killerall** [comment]
Opa, Não sei dizer sobre se teria ou não restrição. Posso tentar ver se sim e se consigo esses icones.

**Comment by AlencarGabriel** [comment]
Esse ícone eu peguei no TDN, a logo é um SVG então deu pra trata-lo.

Pensei em colocar uma cor para cada extensão, como exemplo abaixo (é claro, se puder utilizar).

Mas se tiver ícones específicos seria bem melhor em termos de "elegância".

![image](https://user-images.githubusercontent.com/10109480/61581161-ff15c300-aaf0-11e9-8c37-3076eac03e2e.png)

**Comment by killerall** [comment]
Nao vejo problema.

**Comment by AlencarGabriel** [comment]
Criei um novo Pull Request para este recurso.

**Comment by AlencarGabriel** [comment]
> Nao vejo problema.
> @AlencarGabriel Complementando.
> Só acho que devia ter a mesma cor coisas iguais:
> -. prw, prx,prg.
> -. tlpp
> -.ch
> 
> * aph, apw
>   -ptm
> 
> Concorda?

![image](https://user-images.githubusercontent.com/10109480/62794111-a6ab6300-baa9-11e9-9e0f-50cfb6fa20a7.png)

O que acha assim @killerall ?

**Comment by killerall** [comment]
Acho que ficou bacana.

**Comment by AlencarGabriel** [comment]
Feito Commit.
