### ISSUE TITLE
Alterar Password no vscode

### ISSUE THREAD

**Issue by mauriciodebarros** [totvs/advpl-vscode#351]
Bom Dia!
Como faço para alterar uma Password onde a senha foi alterada no Protheus12 e agora tento compilar no ambiente a aparece mensagem "invalid password".

**Comment by AlencarGabriel** [comment]
Bom dia @mauriciodebarros ,

você deve gerar uma nova senha e alterar nas configurações do ambiente que está tentando conectar/compilar.

Segue um artigo detalhado com a instrução: https://github.com/totvs/advpl-vscode/wiki/Configuração#gerar-senha-de-acesso-ao-um-ambiente

**Comment by mauriciodebarros** [comment]
Bom  dia!
segui os procedientos do artigo apresentado porem tento executar o cipher na paleta de comandos (ctrl+shift+p ou f1) porem não faz nada,, não apresenta campo para digitar a password.

**Comment by AlencarGabriel** [comment]
Você abriu esta issue para a extensão correta mesmo? 

![image](https://user-images.githubusercontent.com/10109480/63522639-27695680-c4cf-11e9-9a5d-3d442fadeca4.png)

**Comment by mauriciodebarros** [comment]
Sim tenho esta extensão e uso também "Totvs Developer Studio for VSCode"

**Comment by AlencarGabriel** [comment]
Você não pode manter as duas em uso. Uma vai acabar conflitando com a outra no suporte ao Advpl. 

Qual debug está usando? Manda seu launch.json

**Comment by mauriciodebarros** [comment]
Qual seria o mais estável para eu  deixar só um?


[launch.zip](https://github.com/totvs/advpl-vscode/files/3531570/launch.zip)

**Comment by AlencarGabriel** [comment]
> Qual seria o mais estável para eu deixar só um?
> 

Recomendo esta aqui mesmo, uso no meu dia-a-dia sem nenhum problema. A "Totvs Developer Studio for VSCode" é muito recente.

**Comment by AlencarGabriel** [comment]
> [launch.zip](https://github.com/totvs/advpl-vscode/files/3531570/launch.zip)

Como eu suspeitava, seu launch.json está configurado para a "Totvs Developer Studio for VSCode". Portanto para saber como alterar a senha, você precisa abrir uma issue no repositório da outra extensão.

**Comment by mauriciodebarros** [comment]
Obrigado pela ajuda!
