### ISSUE TITLE
Listar as funções esta traduzido errado.

### ISSUE THREAD

**Issue by izacsc** [totvs/advpl-vscode#354]
![image](https://user-images.githubusercontent.com/423449/63945183-432da900-ca49-11e9-8778-a4303fc4d034.png)

A tradução correta deveria ser functions

**Comment by AlencarGabriel** [comment]
Bom dia @izacsc ,

vou fazer o ajuste e abrir a Pull. Realmente, houve um problema na tradução instantânea e não me atentei.
