### ISSUE TITLE
MACOS não debuga nem compila depois da ultima atualização

### ISSUE THREAD

**Issue by iurysa** [totvs/advpl-vscode#355]
Ao tentar debugar ou compilar depois da ultima atualização apenas recebo 
Bridge Return:

SyntaxError: Unexpected end of JSON input
Compilação finalizada em Thu Aug 29 2019 10:42:58 GMT-0300 (Brasilia Standard Time) tempo consumido (0.387 segs.)

Estava tudo funcionando normalmente antes, parece que nem está lendo as configurações nem tenta nada, em outra Issue vi alguem falando sobre o fato de não estar lendo o settings.json utf-8, porem não consigo mudar o encoding no meu settings, mesmo usando  "files.encoding": "windows1252", o arquivo em si de configuracao sempre reabre como UTF-8, não sei se é isso é apenas um chute baseado no problema do colega.

**Comment by iurysa** [comment]
Voltei a versão anterior e voltou a funcionar, então é realmente algum problema com a nova versão.

**Comment by killerall** [comment]
@iurysa Obrigado por avisar, vou olhar isso

**Comment by iurysa** [comment]
Obrigado deu certo, agora está funcionando.
