### ISSUE TITLE
Lentidão na compilação

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#358]
Nas ultimas atualizações do visual studio code está muito lento para compilar, antes compilava em 2-4segundos agora é de 12-19 segundos, não sei se foi atualização do code ou do plugin em si.

**Comment by killerall** [comment]
Bom dia.

Você utiliza windows?

Se sim faz um teste.

habilita o alpha no seu setting
"advpl.alpha_compile": true,

Gere o cipher novamente da sua senha, pois o alpha o cipher é menor.

Me diga se volta a ficar rapido, por favor.

**Comment by viniciusgati** [comment]
Invalid Compile Key
 is missing, empty or invalid.
Compilação abortada, verifique o log ou a aba Problemas!
Compilação finalizada em Thu Sep 05 2019 11:42:33 GMT-0300 (Horário Padrão de Brasília) tempo consumido (0.147 segs.)

Eu sou parceiro, estou tendo problema na chave ligando o alpha.

**Comment by killerall** [comment]
Mais a sua chave de compilação esta correta?

**Comment by viniciusgati** [comment]
é a mesma de antes, só coloquei o alpha_compile e parou de compilar, mesmo criando o cipher novo.

**Comment by killerall** [comment]
Consegue colocar seu settings aqui?

**Comment by viniciusgati** [comment]
Claro segue gist:

https://gist.github.com/viniciusgati/b11b45330dbc43c315042f844bbab49f

**Comment by killerall** [comment]
Estranho o caso da senha de compilação, talvez o ID mude, e vc precise pedir outra ID.
De qualquer forma vou ver se tem algo de errado no sem ser alpha. Pois no linux, que é o que uso, é só o alpha e não consigo reproduzir a lentidao.

**Comment by killerall** [comment]
@viniciusgati  Boa noite, lancei uma correção para a lentidao, ja esta disponivel. 0.12.2
