### ISSUE TITLE
IntelliSense não funciona para variáveis?

### ISSUE THREAD

**Issue by alamvilalves** [totvs/advpl-vscode#359]
Olá, o autocomplete funciona pra várias coisas mas não para variáveis que definidas no programa. Há algo que eu possa fazer?

**Comment by killerall** [comment]
@alamvilalves 
Boa noite.
Você pode colocar mais detalhes do que esta ocorrendo?

**Comment by alamvilalves** [comment]
Obrigado por responder e desculpe se não fui muito claro. Quando digito alguns comandos o autocomplete me ajuda e me mostra várias possibilidades, porém quando defino variáveis private ou locais ou até mesmo funções, o autocomplete não funciona.
Quando eu estou digitando o nome da variável e pressiono Ctrl + Espaço, o auto complete não deveria me trazer o nome da variável que estou digitando? Veja na figura. 
![image](https://user-images.githubusercontent.com/21039326/64468555-78e32980-d0fc-11e9-9b83-c44489d69405.png)

Grato

**Comment by killerall** [comment]
@alamvilalves Acredito que você esteja utilizando a extensão do TDS, e não esta aqui.
Da uma olhadinha e se for, por favor abra a issue no respositorio deles.

Obrigado.

**Comment by alamvilalves** [comment]
Olá. VocÊ

**Comment by killerall** [comment]
Basicamente as mesmas, essa extensão tem pelo menos 2 anos a mais de vida do que a do TDS.
[]s
