### ISSUE TITLE
Debug caindo - DbCloseArea() - Lobo Guará

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#361]
Boa tarde @killerall ,

estamos homologando a Release 23 aqui na empresa, e temos percebido um problema que ocorre quando estamos depurando algum código e o Debug passa por um trecho com ``ALIAS->(DBCloseArea())``.

Toda vez que no código fonte depurado é passado por um trecho usando esta função, um "Erro de Sincronismo" é apresentado no SmartClient.

Depurando pelo TDS funciona normalmente, e percebi que nos trechos de ``DbSelectArea()`` o LOG do TDS mostra as seguintes informações em negrito:

>[INFO] Preparando comunicação com servidor: slv00_98 (D) - P7
[INFO] Aguardando resposta do servidor: slv00_98 (D) - P7 ...
[INFO] Aguardando resposta do servidor: slv00_98 (D) - P7 ... OK!
[INFO] Iniciando TOTVS Application
[INFO] ----- LINHA DE COMANDO ------
[INFO] C:\smartclient_LG\smartclient.exe
[INFO] -DEBUG=21360
[INFO] -M
[INFO] -P="SIGAMDI"
[INFO] -Y=7098
[INFO] -Z=192.168.50.31
[INFO] -E=GABRIEL
[INFO] --------------------
[INFO] Iniciando processo... 
**[INFO] Sincronizando pontos de parada com o servidor
[INFO] Sincronizando pontos de parada com o servidor (OK)
null**

Será que não é algo que deva ser tratado na Bridge?

**Comment by killerall** [comment]
Boa tarde,
Não teria muito a vem não.

Você consegue fazer uma user function, que consigo debugar aqui?

Vlw

**Comment by AlencarGabriel** [comment]
Fiz um fonte de teste aqui, não consegui simular... Muito estranho. 

Acontece em casos esporádicos pelo visto, e tambem ocorreu com outros analistas aqui.

Quanto ao Alpha, preciso ver o que está acontecendo aqui. Da erro de pasta SmartClient não encontrada, e antes do branch feature-server eu só usava a Alpha.

**Comment by killerall** [comment]
No caso do alpha, veja se no seu env, nao esta:
advpl.smartclient
ou inves de:
smartclient.

Ontem um analista pegou isso na documentação, que estava antiga na wiki, as vezes pode ser isso.

Eu só uso o alpha aqui, por conta do linux.

Outra coisa que pode ser, é o SC do lobo guara, tem maquinas windows que precisam colocar alguma variavel de ambiente que nao me recordo agora.

**Comment by AlencarGabriel** [comment]
``` json
{
	"environment": "GABRIEL",
	"name": "PILOTO VII 98 - GABRIEL",
	"server": "192.168.50.31",
	"port": "7098",
	"serverVersion": "170117A",
	"includeList": "C:\\Users\\gabriel.s\\Documents\\TDS\\Workspace\\include\\",
	"passwordCipher": "Wjg4VTJ6c1pQakJOOEZ6N0hVSkk4MmpGcGlkazZjcWlKVUJtUVRWS2ViTDk5YlNTZFR3QUt3cXRTM05qZmdSYVM4VXFjTG1oODloV292VjRVVTJ4eWxvQXNaNmdwQmpjKy9lM0YzdHhtZGU0U00veENxZzJabjJibi9qdWFkN04=",
	"user": "admin",
	"smartClientPath": "C:\\smartclient_LG",
	"enable": true
},
```

Não não, caminho do smartclient certinho. 

Usando Lobo guará fora da Alpha, funciona tranquilo... Habilitando a alpha e trocando a senha, nada...

**Comment by AlencarGabriel** [comment]
Descobri o problema:
> "smartClientPath": "C:\\smartclient_LG"

tem que estar com ``\\`` no fim do caminho. Na versão Windows abre o SmartClient certinho, mas agora na Alpha se não tiver isso ele da o erro que não encontrou o SmartClient.

Serve de dica ai pra galera...

**Comment by AlencarGabriel** [comment]
Vou fechar a issue pois o problema pelo visto era esporádico, possivelmente algo relacionado a infraestrutura.
