### ISSUE TITLE
Fonte MS LINEDRAW Visual Studio Code

### ISSUE THREAD

**Issue by williamsrcosta** [totvs/advpl-vscode#362]
Boa Tarde,
Estamos iniciando os testes com o visual Studio Code,
e nos deparamos com uma dificuldade o cabeçalho dos fontes prw.
O nossos cabeçalhos são escritos no padrão MS LINEDRAW, ao tentar colocar essa fonte no VSCODE ele vira uma bagunça nos fontes e se não coloca os cabeçalhos ficam todos estranhos.
Vocês conseguiriam simular usando essa fonte se sim como é a configuração.

**Comment by killerall** [comment]
Bom dia,
Eu pessoalmente não utilizo a MS LineDraw a muito tempo. Nunca tentei colocar ela no vscode.
E utilizo o linux, que nem possui essa fonte. Não consigo ajudar muito.

De qualquer forma, recomendo a migração desses cabeçalhos para forma estruturada do protheus.doc

https://tdn.totvs.com/pages/viewpage.action?pageId=22480577

**Comment by williamsrcosta** [comment]
Bom dia killerall,

A documentação me tirou a duvida sobre o cabeçalho obrigado.

Agora uma outra duvida que surgiu é e quando tem alteração no fonte.

Vocês criam um novo Protheus.doc  ?

Hoje nós fazemos assim:
/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±ÉÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍËÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍ»±±
±±ºPrograma  ³ ADFIN067Pº Autor ³WILLIAM COSTA       ºData  ³  19/09/2018 º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÊÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºDescricao ³ Rotina para criar a string com dados para o SISPAG ITAU    º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºUso       ³ CNAB                                                       º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºAlteracao ³ INICIO WILIAM COSTA 13/08/2019 CHAMADO 051041 || OS 052351 º±±
±±º          ³ FINANCAS || JENNIFER || 8499 || REMESSA ITAU               º±±
±±º          ³ Identificado que quando precisa ser trocado o cnpj no      º±±
±±º          ³ titulo nao levava para o arquivo CNAB SISPAG, ajustado.    º±±
±±ÌÍÍÍÍÍÍÍÍÍÍØÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¹±±
±±ºAlteracao ³ INICIO WILIAM COSTA 09/09/2019 CHAMADO 051653 || OS 052972 º±±
±±º          ³ || FINANCAS || FLAVIA || 8461 || SISPAG ITAU - RPA         º±±
±±º          ³ Identificado que existia um fornecedor que nao tem cnpj    º±±
±±º          ³ e nem cpf, foi adicionado para carregar o campo do SE2.    º±±
±±ÈÍÍÍÍÍÍÍÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
/*/
Usamos a alteração tá vendo?

Fica todo esquisito assim por conta de ser o MS LINEDRAW.

**Comment by izacsc** [comment]
Olha, eu particularmente não registro minhas alterações no fonte, somente no software de controle de versão, como por exemplo o GIT, ou o TFVC ( TFS) entre outros. Se você não usa um sugiro fortemente que comece a usar.

Abraço
