### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by GabrielPrograms** [totvs/advpl-vscode#365]
Ao instalar a extensão e clicar no ícone totvs, é apresentado o erro de Unexpected end of JSON input.

Windows 10
Versão da extensão 0.3.15

**Comment by AlencarGabriel** [comment]
Bom dia,

acredito que tenha aberto essa issue para a extensão errada, pois esta extensão está na versão 0.12.2 conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/10109480/66051318-1ae01100-e505-11e9-8b29-272b23a1b440.png)

A extensão que está utilizando provavelmente é a do [TDS For VsCode](https://github.com/totvs/tds-vscode)
