### ISSUE TITLE
Erro Compilação 4GL 

### ISSUE THREAD

**Issue by fbcaetano** [totvs/advpl-vscode#366]
![image](https://user-images.githubusercontent.com/13919141/66069469-d1ec8480-e525-11e9-837e-761ed3753894.png)

**Comment by fbcaetano** [comment]
O que pode ser.

![image](https://user-images.githubusercontent.com/13919141/66069505-e3ce2780-e525-11e9-8b31-378915a9441a.png)

**Comment by AlencarGabriel** [comment]
Boa tarde @fbcaetano ,

geralmente essa mensagem aparece quando sua função ou arquivo possui o mesmo nome que a TOTVS já utilizou em outro arquivo dela. 

Pelo menos todas as vezes que recebi esse erro utilizando Protheus era por conta disso, um arquivo que já existia no repositório de fontes e era utilizado pela TOTVS.

**Comment by killerall** [comment]
@AlencarGabriel O 4GL funciona um pouco diferente. Pode-se sim subistuir o fonte.

@fbcaetano Eu não estou tratando isso corretamente para 4GL, como você está sem a chave de compilação esta caindo no tratamento do ADVPL.

Vou acertar isso.

Obrigado por notificar.

**Comment by fbcaetano** [comment]
Obrigado

**Comment by AlencarGabriel** [comment]
> @AlencarGabriel O 4GL funciona um pouco diferente. Pode-se sim subistuir o fonte.

Bom saber @killerall , como eu comentei, não sabia como era no 4gl, mas achei que poderia ser a mesma coisa.

**Comment by fbcaetano** [comment]
@killerall  Tens alguma previsão de Liberação?

**Comment by killerall** [comment]
Versao 0.12.3, deve sair essa semana ainda.

**Comment by killerall** [comment]
Feito na 0.12.3
