### ISSUE TITLE
Alterar URL na Wiki

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#371]
Bom dia @killerall ,

vi que fez algumas mudanças na Wiki ficaram bem organizadas! 

Porém identifiquei que na Wiki do Gerenciador de Ambientes, o link que aponta para a Wiki de Wizzard para criar ambientes não foi alterado para a nova URL: https://github.com/totvs/advpl-vscode/wiki/Criação-de-ambiente-facilitada.

**Comment by killerall** [comment]
Bom dia.
Já ajustei.
