### ISSUE TITLE
Comportamento estranho no Debug 

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#372]
Boa tarde @killerall ,

estava fazendo alguns testes em uma rotina, e percebi que o debug não "passava" por uma linha específica que contém macro substituição com atribuição de valor, conforme exemplo:

```xbase
User Function Macro()

    If Type( "nTotal" ) == "U"
        &("nTotal") := 10
    EndIf

    nTotal++

Return Nil
```

No exemplo acima, o cursor do debug não passa pela linha que contém a expressão: ```&("nTotal") := 10```. 

Poderia verificar porque isso ocorre? Pois avaliando a variável ela recebe o valor **10** atribuído anteriormente.

**Comment by killerall** [comment]
Boa tarde,
Debuguei o seu fonte normalmente, passando pela linha do macro.
O teste que eu fiz aqui foi no ultimo server do lobo guara.
Porem é sabido que o server sempre teve um comportamento meio esquisito quando usado macros. E desde da epoca que eu debug no ide antigo em delphi, eu tenho o costume de por pontos de paradas depois da macro e da F5 para continuar apos ela chamar, pois as vezes o server diz ao debug que esta em algum lugar nada a ver.

Mais repito, o seu fonte no lobo guara, no alpha. Fez o debug normal.

**Comment by AlencarGabriel** [comment]
Realmente, colocando o breakpoint depois, dando F10 o debug voltou para umas linhas anteriores.

Não utilizei o alpha e nesse cliente ainda é a Release 17 (testei na minha base 17 tambem e ocorreu o mesmo). Vou fazer um teste no Lobo Guará em outro cliente.

**Comment by AlencarGabriel** [comment]
@killerall ,

fiz o debug deste fonte num server lobo guará e lá funcionou certinho, passa pelas linhas com Macro.
