### ISSUE TITLE
Ctrl+F9 Descompila o fonte

### ISSUE THREAD

**Issue by luiz-amaral** [totvs/advpl-vscode#376]
Olá, estou com um problema na compilação dos fontes.

Quando utilizo o atalho Ctrl+F9 para compilar, o fonte é descompilado do rpo, testei pelo "Advpl - Compile Advpl Source" o tive o mesmo problema.

Só consigo compilar o fonte se utilizar a função de compilar todos os fontes da pasta(Advpl - Compile Folder).

Alguém consegue me ajudar?

**Comment by killerall** [comment]
Boa tarde,
Não é possivel "descompilar" um fonte, o que pode ter é uma remoção do fonte do rpo.
Isso so seria possivel, caso o mapeamento de tecla do seu vscode estiver errada.
Olha em File-> Preferences -> keyboard short cut

![image](https://user-images.githubusercontent.com/4764609/67321695-3d52c200-f4e6-11e9-891b-86c974d55d1b.png)

Digite advpl, ele vai mostrar a lista de tecla de atalho.

**Comment by luiz-amaral** [comment]
Minha configuração está equivalente a sua para essa combinação de teclas.

![image](https://user-images.githubusercontent.com/15158805/67322112-e4cff480-f4e6-11e9-8ab7-5ce65531c48d.png)

**Comment by killerall** [comment]
Não tenho idea do que ocorre, aqui também mostra os dois.

Tente o seguinte.
- Veja se esta instalada a extensao do TDS, se sim remova, pois as duas não são compativeis.
- Remova todas as extensões, e re instale as mesmas.
- Se nao rolar, tente remover o vscode e reinstalar.

**Comment by luiz-amaral** [comment]
Boa tarde,

Desculpe a demora no retorno.
Consegue resolver reinstalando todos os componentes e alterando a criptografia para compilação.
