### ISSUE TITLE
Client WebService

### ISSUE THREAD

**Issue by marcsatiro** [totvs/advpl-vscode#378]
Issue Type: <b>Bug</b>

Estou tentando gerar um client webservice, mas ficar pedindo para selecionar um ambiente mesmo já estando com o ambiente selecinado.

Extension version: 0.12.3
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by killerall** [comment]
Boa noite

Qual o url do serviço?

**Comment by marcsatiro** [comment]
Boa noite, obrigado eu estava usando o plugin ADVPL ai resolvi usar o Plugin do TDS ai consegui

Obrigado

________________________________
De: Rodrigo Antonio Godinho da Silva <notifications@github.com>
Enviado: segunda-feira, 28 de outubro de 2019 22:16
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: marcsatiro <marcsatiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Client WebService (#378)


Boa noite

Qual o url do serviço?
