### ISSUE TITLE
EOF ETERNO

### ISSUE THREAD

**Issue by Herbert2122** [totvs/advpl-vscode#379]
Pessoal preciso de ajuda, está acontecendo um bug estranho demais, 
estava trabalhando com a tabela SA5  no protheus fazendo reclocks para inserir e atualizar dados,
do nada parou de funcionar apresentando o erro: 

Exception in thread 6720 Update error - File is in EOF - SA5010

Testei em outros IDes e com outro Visual studio com a mesma extensão em outra máquina e deu certo,
mas no meu computador em especifico não deu certo,
existe algum diretório além do %TEMP% que a extensão guarda arquivos temporários que podem está ocasionando esse problema?
Já verifiquei as configurações e está tudo certo, não sei onde pode estar dando esse gap de sempre a tabela no meu ambiente está em EOF,
já tentei dar update usando DBGOTO e mesmo assim apresenta o erro.

**Comment by Herbert2122** [comment]
Trecho do código testado em outro IDE e em outro visual studio com a extensão da TOTVS e deu certo

`            DbSelectArea("SA5")
			SA5->(dbSetOrder(14)) //INDÍCE E
		If	! SA5->(dbSeek(xFilial("SA5")+SZH->(ZH_FORNECE+ZH_LOJA) + GdFieldGet("D1_XCOD",a)))
				msUnLock()
				SA5->(msUnLock())
				
				RecLock("SA5",.T.)
				SA5->A5_FILIAL   := 'X'    ----->LINHA COM ERRO
				SA5->A5_FORNECE  := 'X' 
				SA5->A5_LOJA     := 'X' 
				SA5->A5_NOMEFOR  := 'X' 
				SA5->A5_PRODUTO  := 'X' 
				SA5->A5_NOMPROD  := 'X' 
				SA5->A5_CODPRF   := 'X' 
				SA5->(msUnLock())`

**Comment by killerall** [comment]
Bom noite. 
Não entendi direito qual o seu problema.

Você está recebendo este erro quando debuga?

A principio o IDE que vc utiliza não interferece na execução.
Se você estiver utilizando o mesmo server, e banco. 

Esta extensão não grava nada em relação a base do Protheus.

Att.

**Comment by Herbert2122** [comment]
Bom dia Killerall 
por isso esse erro intriga eu e minha equipe, o IDE não deveria interferir, 
por isso não sei Distinguir se o erro é do Visual Studio ou  da Extensão em sí, 
Qualquer outra pessoa consegue executar o bloco de código abaixo:
Menos eu.
e Somente no debug.
![image](https://user-images.githubusercontent.com/29212058/68384839-3dce9800-0137-11ea-9bed-be219e8b3d3f.png)
![image](https://user-images.githubusercontent.com/29212058/68384847-445d0f80-0137-11ea-94d0-874ca9eb5486.png)



`       DbSelectArea("SA5")
			SA5->(dbSetOrder(14)) //INDÍCE E
		If	! SA5->(dbSeek(xFilial("SA5")+SZH->(ZH_FORNECE+ZH_LOJA) + GdFieldGet("D1_XCOD",a)))
				RecLock("SA5",.T.)
				SA5->A5_FILIAL   := 'X' //xFilial("SA5")
				SA5->A5_FORNECE  := 'X' // SZH->ZH_FORNECE
				SA5->A5_LOJA     := 'X' // SZH->ZH_LOJA
				SA5->A5_NOMEFOR  := 'X' // Left(Posicione("SA2",1,xFilial("SA2")+SZH->(ZH_FORNECE+ZH_LOJA),"A2_NOME"),TamSX3("A5_NOMEFOR")[1])
				SA5->A5_PRODUTO  := 'X' // GdFieldGet("D1_XCOD",a)
				SA5->A5_NOMPROD  := 'X' // Left(Posicione("SB1",1,xFilial("SB1")+GdFieldGet("D1_XCOD",a),"B1_DESC"),TamSX3("A5_NOMPROD")[1])
				SA5->A5_CODPRF   := 'X' // Upper(AllTrim(GdFieldGet("D1_XCOD",a))) 
				SA5->(msUnLock())
EndIf`

**Comment by Herbert2122** [comment]
Consegui resolver o problema de fato era alguma coisa que o visual studio code estava salvando no computador, 
apaguei a pasta 
Fiz o backup do arquivo settings.json 
apaguei a pasta 
C:\Users\herbert.souza\AppData\Roaming\Code
e isso resolveu o problema , agora o debug ocorre normalmente,
fica a dica para caso alguém algum dia sofra com o mesmo problema 
Obrigado pelo apoio.
