### ISSUE TITLE
advpl.patch.apply - Aplicar somente pacotes atualizados

### ISSUE THREAD

**Issue by FRReinert** [totvs/advpl-vscode#380]
Bom dia,

É possível aplicar apenas os fontes atualizados por meio deste plugin, assim como é feito pelo Totvs Dev Studio?

Não achei nada específico sobre isso no Wiki
https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs

**Comment by eliandrocardoso** [comment]
Também tenho o mesmo problema. Só falta isso para o plugin ser perfeito.

**Comment by robsonrosilva** [comment]
Isso já foi implementado.
https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs#somente-atualizados

**Comment by killerall** [comment]
Implementado 0.14.2
