### ISSUE TITLE
Compilação com RPOCUSTOMIZATION não funciona

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/advpl-vscode#381]
Boa tarde,
Tentei realizar as configurações para utilização de dois RPO's conforme esse boletim https://tdn.totvs.com/display/tec/RPOs+Multiplos mas utilizando a extensão a compilação retorna 

Bridge Return:

SyntaxError: Unexpected end of JSON input
Compilação finalizada em Mon Nov 25 2019 15:51:50 GMT-0200 (Horário de Verão de Brasília) tempo consumido (3.234 segs.)

Anexei o log do bridge na issue.
[AdvplDebugBridge.log](https://github.com/totvs/advpl-vscode/files/3887942/AdvplDebugBridge.log)

**Comment by robsonrosilva** [comment]
Consegui ativando o alpha compile.

**Comment by delson-filho** [comment]
@robsonrosilva, tens como mostrar o appserver.ini?

Tentei usar e não consegui.
