### ISSUE TITLE
Ao tentar compilar é apresentado mensagem 'No Server Connected'

### ISSUE THREAD

**Issue by tigas360** [totvs/advpl-vscode#382]
Troquei de note e tive que adicionar uma nova chave de compilação, além de configurar o vscode para advpl. Ao selecionar o ambiente e tentar compilar é informado que não existe servidor para compilar. Podem me ajudar:
{
    "workbench.iconTheme": "advplIcons",
    "totvsLanguageServer.welcomePage": false,
    "advpl.environments": [
        {
            "name": "Local TP12-125",
            "environment": "TP12125",
            "server": "SPON019400628",
            "port": "5041",
            "serverVersion": "170117A",
            "user": "Admin",
            "passwordCipher": "ZGx3NUJCVFc3RGMzV0dSb2pEbEtEN1BaRmg2c0tqdDJIY2NQODhOVU40b2VKSXRoTHliOE1tSUcwSUNRV3lIWWhFT1BnbVZ4TEFuaThNM1REdkNPYm1uaWRnMTlqZGdOK091Q1FLYXBWS0xYd2Z3ZHpUSEN5Q0h4d0QycGRIUG4=",
            "smartClientPath": "c:\\WorkStation\\Protheus\\I_12125_MSQ_64\\Protheus\\Bin\\smartclient\\",
            "includeList": "c:\\WorkStation\\Protheus\\Include\\",
        }
    ],
    
    "files.encoding": "windows1252",

    "advpl.startProgram": "SIGAMDI",

    "advpl.authorization_code": "removi a chave",
    "advpl.authorization_permission": "1",
    "advpl.authorization_generation": "20191202",
    "advpl.authorization_validation": "20200301",
    "advpl.debug_multiThread": false,
    "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true,
    "advpl.debug_showTables": true,
    "advpl.debug_ignoreSourceNotFound": true,
    "editor.autoIndent": true,
    "editor.minimap.showSlider": "mouseover",
    "editor.minimap.enabled": false,
    "advpl.selectedEnvironment": "Local TP12-125",
    "totvsLanguageServer.clearConsoleBeforeCompile": true,
    "totvsLanguageServer.useReconnectionToken": false
}

**Comment by killerall** [comment]
Boa tarde,

Pelo que o que da pra ver na sua configuração, você tem as duas extensão instaladas de advpl?
Por que elas não trabalham em conjunto, é necessário estar com apenas 1 ativa.

**Comment by tigas360** [comment]
Opa...era isso mesmo. Valeu!!!
Estava com o pluging do TDS e do Advpl. Desabilitei o pluging do TDS e funcionou.
