### ISSUE TITLE
Falha de conexão Versão 25 

### ISSUE THREAD

**Issue by paolastekl** [totvs/advpl-vscode#383]
Não estou conseguindo conectar a versão 12.25 do Protheus no debuger do VS Code. Ele conecta ao servidor, consigo compilar e aplicar patch porém ao conectar para debugar não consigo avançar por falha de conexão. 
SmartClient está conectado normalmente.

**Comment by AlencarGabriel** [comment]
Boa tarde @paolastekl,

poderia mandar o JSON de configuração do ambiente que está tentando
conectar?

Em ter., 10 de dez. de 2019 às 13:17, paolastekl <notifications@github.com>
escreveu:

**Comment by paolastekl** [comment]
Segue launch.json:

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "%tds.package.totvs_language_debug%",
			"program": "${command:AskForProgramName}",
			"smartclientBin": "C:\\smartclient_P1225\\SmartClient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\smartclient_P1225\\SmartClient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "U_DVSMR090",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGAMDI",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}

**Comment by AlencarGabriel** [comment]
Pelo que percebi nas suas configurações, você não está usando esta
extensão. E sim a versão TDS-VsCode.

Poderia confirmar se está usando as duas ao mesmo tempo? Pois uma conflita
com a outra, mas se estiver usando apenas a outra, peço que reabra sua
issue no outro repositório.

https://github.com/totvs/tds-vscode

Em ter., 10 de dez. de 2019 às 13:34, paolastekl <notifications@github.com>
escreveu:

**Comment by paolastekl** [comment]
Gabriel estou usando a TDS-VSCode mesmo. Vou ver se conseguem me ajudar por lá! 
Obrigada.
