### ISSUE TITLE
Não compila na versão Alpha (Windows)

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#388]
Bom dia @killerall ,

estava vendo as notificações da extensão e me atentei que não estava usando mais a Alpha (pelo que me lembro estava usando, porem devo ter alterado a configuração e não percebi). Como será obrigatório para Build nova, fui configurar e percebi que agora não está mais compilando usando esse bridge.

Estou deixando aqui os Logs, configuração que utilizo e ressaldo desde já que não há erro no "Developer Tools" do VsCode.

> Tempo atras identifiquei que o Debug não funcionava quando a configuração `advpl.environments.smartClientPath` está sem o separador de diretório no final do caminho \\\\.

> A principio o problema está na compilação, pois ao startar o debug o Protheus executa corretamente.

> A chamada de compilação não chega no AppServer.

---

**Anexos:**

[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/3973032/AdvplDebugBridgeC_0.log)

[Workspace_json.txt](https://github.com/totvs/advpl-vscode/files/3973035/Workspace_json.txt)

![image](https://user-images.githubusercontent.com/10109480/70992219-f1686780-20a7-11ea-9ecf-ea3429ce645a.png)

**Comment by killerall** [comment]
Bom dia,

Não consigo reproduzir esse seu erro de jeito nenhum no windows usando o Alpha.

Você olhou se você não tem setting no seu Usuario que conflita com esse cara?

Pois para dar essa mensagem é feita a seguinte validação:

```
bool isValid(){
                    return (!server.empty() && !port.empty());
                }
```

Esta chegando ou o server ou a porta vazia.

**Comment by AlencarGabriel** [comment]
Isso só começou a acontecer depois que troquei para usar a Alpha. Quando voltei as configurações funcionou normalmente.

Dei uma conferida nas minhas configurações, e só tenho essas configurações de ambiente na Workspace mesmo, como sempre faço. 

Vou testar iniciando tudo do zero, sem essa workspace que ja utilizo.

**Comment by killerall** [comment]
Sim, pode ser a maneira que é lido o Json. 
Faz um favor, entre debugando dentro da extensão e pegue a linha inteira de comando que é enviado quando manda compilar, em especial  o parâmetro do json(compileInfo)

**Comment by AlencarGabriel** [comment]
``--compileInfo="`` completo: https://gist.github.com/AlencarGabriel/87d8ce7dfded68fe463b3967a4bfd1d7

Debug:
![image](https://user-images.githubusercontent.com/10109480/70999758-c6d2da80-20b8-11ea-842e-b0a20a01a794.png)

Vendo o tamanho do JSON aqui, acredito que talvez o problema pode ser o Buffer de string do C não? Lembra aquela vez que eu tive problema pra buscar o INI? Pode ser que está dando problema porque o conteúdo que está indo para o Bridge é muito grande.

**Comment by AlencarGabriel** [comment]
Fiz um teste em outra maquina com um Workspace novo, somente com as configurações básicas (arquivo bem menor), e compilou.

**Comment by killerall** [comment]
O ponto todo é o seguinte, o alpha não aceita // como escape do diretorio. Precisa os \

Substitua: 
C:\\Users\\Gabriel Alencar\\Documents\\Clientes\\Brametal\\Fontes\\Branches\\ProtheusClean\\src",

Por:

C:/Users/Gabriel Alencar/Documents/Clientes/Brametal/Fontes/Branches/ProtheusClean/src

**Comment by AlencarGabriel** [comment]
Estranho @killerall , pois no teste que eu fiz na outra maquina com apenas um ambiente, funcionou com "\\\\".

Mas vou testar aqui e respondo...

**Comment by AlencarGabriel** [comment]
@killerall ,

testei conforme me falou, e continuou a mesma coisa. 

Ai na outra máquina que uso no dia a dia, fiz uma limpeza nas configurações, deixei apenas um ambiente e tirei as configurações da minha extensão (que para padronizar, mantive com o prefixo `"advpl."` )

Compilou certinho!

Acho que realmente o problema pode estar relacionado ao fato do Bridge não estar processando todo o JSON das configurações `advpl.`

**Comment by killerall** [comment]
Encontrei o problema, ta difícil a solução.
Você tem caminhos com acentos nos seus valores.
A biblioteca utilizada para fazer o parser de JSON no alpha, não consegue efetuar o parser.

Estou estudando se consigo fazer algum tipo de conversão.

**Comment by AlencarGabriel** [comment]
Caminhos com acentos você diz ``smartClientPath`` e ``includeList`` ??

**Comment by killerall** [comment]
Em qualquer lugar.

**Comment by AlencarGabriel** [comment]
Caramba, realmente isso pode ocorrer em vários points da configuração mesmo. 

Agora, estranho pois quando desenvolvi a feature-server estava usando a Alpha, exatamente porque você tinha implementado inicialmente somente lá. E minhas configurações tinham caracteres especiais, e mesmo assim funcionava.

**Comment by killerall** [comment]
Corrigido e liberado na versão 0.14.2
