### ISSUE TITLE
Estou configurando o vscode e está dando erro NO SERVER CONNECTED

### ISSUE THREAD

**Issue by fabiopedroza** [totvs/advpl-vscode#389]
Settings
 
{
    "totvsLanguageServer.welcomePage": false,
    "advpl.environments": [
        {
            "environment": "P12_2",
            "name": "P12_2",
            "server": "LOCALHOST",
            "port": "7890",
            "serverVersion": "170117A",
            "passwordCipher": "WDl2UUxJLzVqMUtPM3ZreXZrbHltR0tuVmlManBPbmVmVmxKcEJ5T0hLRytXWGhFV1pmMXZDcWJyK3N6ejdBQUY4N2xHRE45eFZqVjNGeEozbXpLMlhsWkVnK0kySzBZT0hHRFJ3NHZOaVc2bzlNTkk3dzVHbFJaRUVCcW9Fam4=",
            "includeList": "d:\\Totvs\\TOTVSV1217\\Protheus\\Include\\",
            "user": "Admin",
            "smartClientPath": "d:\\Totvs\\TOTVSV1217\\Protheus\\Bin\\smartclient",
            "enable": true
        }
    ],
    "advpl.selectedEnvironment": "P12_2"
}

Launch
=====
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\Totvs\\TOTVSV1217\\Protheus\\Bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	]
}

**Comment by AlencarGabriel** [comment]
Boa tarde @fabiopedroza ,

pelo que pude observar em suas configurações, você parece estar usando duas extensões de suporte a Advpl, e você só pode utilizar uma, pois as duas acabam se conflitando.

**Comment by fabiopedroza** [comment]
Ao tentar conectar no servidor apresenta a mensagem - Could not connect to server e o log no diretório %temp% o arquivo está zerado

Launch
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\Totvs\\TOTVSV1217\\Protheus\\Bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	]
}

Settings
{
    "totvsLanguageServer.welcomePage": false,
    "advpl.environments": [
        {
            "environment": "P12_2",
            "name": "P12_2",
            "server": "LOCALHOST",
            "port": "7890",
            "serverVersion": "170117A",
            "passwordCipher": "WDl2UUxJLzVqMUtPM3ZreXZrbHltR0tuVmlManBPbmVmVmxKcEJ5T0hLRytXWGhFV1pmMXZDcWJyK3N6ejdBQUY4N2xHRE45eFZqVjNGeEozbXpLMlhsWkVnK0kySzBZT0hHRFJ3NHZOaVc2bzlNTkk3dzVHbFJaRUVCcW9Fam4=",
            "includeList": "d:\\Totvs\\TOTVSV1217\\Protheus\\Include\\",
            "user": "Admin",
            "smartClientPath": "d:\\Totvs\\TOTVSV1217\\Protheus\\Bin\\smartclient",
            "enable": true
        }
    ],
    "advpl.selectedEnvironment": "P12_2",
    "totvsLanguageServer.askEncodingChange": false
}

**Comment by killerall** [comment]
@fabiopedroza Boa noite, você verificou se esta com as 2 extensões instaladas?

Essa cfg:

"totvsLanguageServer.welcomePage": false,


Indica que você tem ou ja teve instalada a outra extensão. Caso ainda tenha instalada remova ela. e refaca o teste, pf.

**Comment by fabiopedroza** [comment]
Muito obrigado pela ajuda. Desinstalei o VS Code e comecei do zero e por enquanto deu certo
