### ISSUE TITLE
Consumo Excessivo de Memória RAM - Alpha

### ISSUE THREAD

**Issue by diogo-hsf** [totvs/advpl-vscode#401]
Boa noite, @killerall 

Estou utilizando a versão Alpha enviada pelo @AlencarGabriel, observei que nos breakpoints utilizando TcQuery está com consumo excessivo de memória RAM chegando a quase 100%  

![debug_alpha](https://user-images.githubusercontent.com/52430448/74095872-99f9dd00-4ad5-11ea-9a91-e86c430e3e98.jpeg)

**Comment by killerall** [comment]
Boa noite,

Você tem um exemplo de fonte advpl, que consigo reproduzir isso?

Obrigado.

**Comment by diogo-hsf** [comment]
Bom dia, 

Segue o fonte em anexo, o problema citado ocorreu na linha 345. 

[fonte.zip](https://github.com/totvs/advpl-vscode/files/4180635/fonte.zip)

**Comment by killerall** [comment]
Bom dia,

Não consigo rodar sua rotina, ela faz referencia a uma tabela RD4, que acredito ser customizada de vocês.
Você consegui me mandar os sxs dela? (Nao sei se tem algo custom no B1 tmb)

**Comment by diogo-hsf** [comment]
@killerall segue em anexo, caso necessite de algo mais me avise. 

> Utilizo a release 12.1.23

[SX's.zip](https://github.com/totvs/advpl-vscode/files/4181078/SX.s.zip)

**Comment by diogo-hsf** [comment]
Rodrigo, 

Fui debugar em um fonte diferente e apresentou o mesmo problema no breakpoint do TcQuery 

![debug 10-02](https://user-images.githubusercontent.com/52430448/74183960-a9d40700-4c24-11ea-96f8-7b5e10d5837a.jpg)

**Comment by killerall** [comment]
@diogo-hsf 
Eu consegui reproduzir algumas vezes, não consegui ainda identificar como exatamente, para conseguir debugar.

Para nao trabalhar o trabalho ai, desliga o table

"advpl.debug_showTables": false,

Acho que esta ligado a ele.

**Comment by diogo-hsf** [comment]
@killerall boa tarde, 

Após correção, fiz vários testes e não apresentou o problema de consumo excessivo. Obrigado!

**Comment by killerall** [comment]
Obrigado vc, em breve vou lancar a versão.

**Comment by AlencarGabriel** [comment]
@killerall acho que essa já pode ser fechada.
