### ISSUE TITLE
Running the contributed command: 'advpl.compile' failed.

### ISSUE THREAD

**Issue by RaulCapeleti** [totvs/advpl-vscode#405]
Olá,

Ao tentar compilar em ADVPL às vezes aparece a mensagem acima, daí só é possível recompilar um fonte se fechar e abrir o VSC novamente.  O que pode ser ?  Isto aconteceu após a última atualização.

Grato.

Raul

**Comment by killerall** [comment]
Boa tarde,
Não veio a imagem.

Consegue colocar ela?

**Comment by RaulCapeleti** [comment]
boa tarde;

Como eu consigo colocar um print ?

Grato.

Raul.

**Comment by RaulCapeleti** [comment]
![image](https://user-images.githubusercontent.com/61062349/74558283-c469f100-4f40-11ea-9e0d-fc0c3c45db53.png)

**Comment by killerall** [comment]
Não estou conseguindo reproduzir.
Você esta compilando 1 fonte so? Ou uma pasta. 

Você consegue reproduzir sempre?

**Comment by RaulCapeleti** [comment]
Apenas um fonte.
E o problema é intermitente. Na imagem abaixo acabei de compilar um mesmo fonte, e ao tentar compilar novamente gera a msg 

![image](https://user-images.githubusercontent.com/61062349/74560088-9090ca80-4f44-11ea-8557-a4b40b223c10.png)

**Comment by RaulCapeleti** [comment]
Versão: Commit de 1.42.1 (system setup): c47d83b293181d9be64f27ff093689e8e7aed054 Data: 2020-02-11T14:45:59.656Z elétron: 6.1.6 Chrome: 76.0.3809.146 node. js: 12.4.0 V8: 7.6.303.31-electron.0 OS: Windows_NT x64 10.0.18362

**Comment by killerall** [comment]
A ultima imagem que mandou, o vscode esta ignorado a compilação pois pra ele a primeira não acabou.
O problema está no primeiro failed, estou tentando reproduzir por aqui mais sem sucesso ainda.

**Comment by AlencarGabriel** [comment]
@RaulCapeleti , 

teria como fazer mais alguns testes até que seja exibido a mensagem: `Running the contributed command: 'advpl.compile' failed` ?

E quando esta aparecer, vá em `Help > Toggle Developers Tools` e reporte aqui os erros que aparecem no console (pode ser print)

**Comment by RaulCapeleti** [comment]
Bom dia,

Após a reinicialização do computador, logo após a atualização da versão, o problema não aconteceu mais. Acho que era o caso de reiniciar a máquina apenas, agora está compilando e debugando normalmente os fontes. Obrigado !
