### ISSUE TITLE
Erro ao gerar patch a partir de um arquivo txt

### ISSUE THREAD

**Issue by lucaskonradfranca** [totvs/advpl-vscode#406]
Bom dia.
Não estou conseguindo gerar patchs a partir do arquivo TXT. É apresentado o erro abaixo:

{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":-1,"Column":0,"Type":0,"Message":"Ocorreu um erro a fazer a leitura do ini do appserver:<unspecified file>(15): duplicate key name"},{"Line":-1,"Column":0,"Type":0,"Message":"Ocorreu um erro a fazer a leitura do ini do appserver:No such node (P12125MNTDB)"}]}]}

Não consegui identificar nenhum problema nas configurações. 

- "serverVersion": "191205P"
- "advpl.alpha_compile": true

**Comment by killerall** [comment]
Bom dia,

Olhe o ini do seu appserver na linha 15, Tem chave duplicada nele.

**Comment by lucaskonradfranca** [comment]
Obrigado, tinha chaves duplicadas mesmo. Resolvido!
