### ISSUE TITLE
Debugando em VSC 

### ISSUE THREAD

**Issue by RaulCapeleti** [totvs/advpl-vscode#407]
Olá,

Existe uma configuração do Debug do ADVPL onde não é preciso digitar o "SIGAMDI", ou o módulo que se quer entrar no Protheus, quando se entra em modo de Debug, ou seja, não preciso mais digitar "SIGAMDI" e clicar no "ENTER" para iniciar.

Onde, e como, eu coloco esta instrução nas configurações ?

Grato.

Raul.

**Comment by guilhermebigois** [comment]
Na configuração na perspectiva Run and Debug (Ctrl + Shift + D) há uma engrenagem, nela esão contidas as configurações do launchers SmartClient (no caso do Protheus).

Você pode colocar no parâmetro `program` o módulo que deseja que seja executado no F5:
![image](https://user-images.githubusercontent.com/22408258/75443434-244c9880-5940-11ea-8bad-c8023252a4f1.png)

Nesse meu exemplo eu criei duas configurações, uma para debug geral e outra para entrar direto no SIGAFAT:
![image](https://user-images.githubusercontent.com/22408258/75443523-58c05480-5940-11ea-9f86-f9e8030267d6.png)

Caso não queira utilizar o mouse para trocar as configurações, use `Ctrl + Shift + P`, selecione a opção `>Run and Debug: Focus on Start View`, de um `Tab` e use as setas para cima e para baixo do teclado para navegar entre os launchers.

**Comment by killerall** [comment]
@guilhermebigois Na realidade essa configuração que passou, não é desta extensão, e sim da TDS.
Para esta extensão, basta no launch.json trocar o programRun.
Por exemplo, a cfg a seguir chama o configurador direto.

```
 {
            "name": "Debug SIGACFG",
            "type": "advpl",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceRoot}",
            "programRun": "SIGACFG",
            //"programRun": "${command:AskForProgramName}",
            "stopOnEntry": false,
            "enviromentInfo": "${command:GetEnvInfos}",
            "workspace": "${workspaceFolder}/"
        },
```

**Comment by RaulCapeleti** [comment]
Valeu Rodrigo, funcionou corretamente, muito obrigado !

Abs.
