### ISSUE TITLE
Instalação VSCode !

### ISSUE THREAD

**Issue by JoelberGarcia** [totvs/advpl-vscode#412]
Boa tarde, alguém já passou por isso na instalação do VSCode ? Instalei o mesmo e quando vou add server ele gera a mensagem "Unexpected end of JSON input" e não deixa eu incluir. 
![vscode](https://user-images.githubusercontent.com/61033874/76249715-b434f100-6222-11ea-8db7-7717edacd16b.jpg)

**Comment by AlencarGabriel** [comment]
Boa tarde @JoelberGarcia  ,

pelo que pude observar no seu print, você não está usando esta extensão, e sim a https://github.com/totvs/tds-vscode.

**Comment by JoelberGarcia** [comment]
Bom dia Alencar, se observar no vídeo estou usando a extensão correta. Se observar quando clico para add o servidor teste ele gera a mensagem do "Unexpected end of JSON input" e não deixa eu salvar.
[vscode.zip](https://github.com/totvs/advpl-vscode/files/4312118/vscode.zip)

**Comment by AlencarGabriel** [comment]
Bom dia,

seu vídeo não abriu aqui, mas te garanto que essa visão TOVTS:SERVERS não pertence a esta extensão. Nesta existe o Gerenciador de Ambientes, porém na visão Explorer.

O que pode estar ocorrendo é que você tem duas extensões de suporte a AdvPL instaladas, e isso pode ocasionar em uma série de conflitos.

**Comment by JoelberGarcia** [comment]
O vídeo está zipado e gravei ele no CamStudio da TOTVS mesmo. Eu não tenho nenhuma outra extensão advpl. Tenho somente a que você enviou e o tradutor, mais nada. Já desinstalei e instalei, removi tudo nos registros do Windows e nada.

**Comment by killerall** [comment]
@JoelberGarcia Bom dia.
Consegui visualizar seu video, e de fato o que o Alencar comentou está correto.

Você tem instalada a extensão do TDS.
Para suporte no TDS abra uma issue [la](https://github.com/totvs/tds-vscode).
Ou remova essa extensão e instalei essa extensão aqui.
https://marketplace.visualstudio.com/items?itemName=KillerAll.advpl-vscode

Abraço

**Comment by JoelberGarcia** [comment]
Problema resolvido !
