### ISSUE TITLE
Compilar VsCode.

### ISSUE THREAD

**Issue by Vitorlps** [totvs/advpl-vscode#413]
Olá,

Após atualização do VsCode não estou conseguindo compilar, para todos os fontes aparecem as mesmas mensagens:

Compile finished.
One or more files have warnings and/or errors. See problems and logs for details.
Source f:/Clientes/Auster/Rdmake/ACD100RE.prw precompiled with warnings and/or errors.

Não tem nenhum erro no código.

Obs.: Já desinstalei a extensão, apaguei os arquivos da pasta .totvsls e não mudou nada.

**Comment by Vitorlps** [comment]
![image](https://user-images.githubusercontent.com/51929283/76325910-a5077f00-62c6-11ea-9816-1605257a61be.png)

**Comment by AlencarGabriel** [comment]
Boa tarde @Vitorlps ,

pelo que pude observar com base nas suas informações, você não está usando esta extensão, e sim a https://github.com/totvs/tds-vscode.
