### ISSUE TITLE
Erro ao Debugar

### ISSUE THREAD

**Issue by johnlblima** [totvs/advpl-vscode#414]
Quando pressiono F5 para debugar o VS Code dá uma mensagem "no debug adapter found" já desinstalei o VS Code completo e instalei de novo e problema não resolve.

**Comment by killerall** [comment]
Bom dia,

Você precisa na barra lateral da esquerda clicar no debug.
Na view de debug, vai ter um combo box, digite Add Configuration.

Escolha Advpl Debug

Vai criar um arquivo launch.json

**Comment by johnlblima** [comment]
Perdão, acredito que me expressei mal.
O ambiente já estava configurado e eu já estava trabalhando normalmente. Mas sem causa aparente começou a aparecer esse problema.

**Comment by killerall** [comment]
Cole aqui o conteudo do seu launch.json

**Comment by johnlblima** [comment]
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGACFG",
			"program": "SIGACFG",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "APSDU",
			"program": "APSDU",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGAMDI",
			"program": "SIGAMDI",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "EXECUTAR",
			"program": "${command:AskForProgramName}",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGAADV",
			"program": "SIGAADV",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGAADV LG",
			"program": "SIGAADV",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT_LG_X86\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGAMDI LG",
			"program": "SIGAMDI",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT_LG_X86\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SIGACFG LG",
			"program": "SIGACFG",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT_LG_X86\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "EXECUTAR LG",
			"program": "${command:AskForProgramName}",
			"smartclientBin": "D:\\OneDrive - mconsult.com.br\\SMARTCLIENT_LG_X86\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"serverItem": "SERVSAL EXTERNO 2",
			"environment": "COMPILA"
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "U_EXPMENU",
			"description": ""
		},
		{
			"args": [],
			"label": "U_F_ATUTAB",
			"description": ""
		},
		{
			"args": [],
			"label": "U_LTFMA003",
			"description": ""
		},
		{
			"args": [],
			"label": "U_LTXMA04A",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGAMDI",
			"description": ""
		},
		{
			"args": [],
			"label": "U_NDDCARGO",
			"description": ""
		}
	],
	"lastProgramExecuted": "U_NDDCARGO"
}

**Comment by killerall** [comment]
Você esta utilizando outra extensão, a do TDS. Esse git é da extensão advpl. Acredito que tenha mais sucesso na solução do seu problema por la.
