### ISSUE TITLE
Exclusão de fonte do RPO no binário 191205P

### ISSUE THREAD

**Issue by jerfweb** [totvs/advpl-vscode#416]
Prezados,
Atualizei minha base para o binário 191205P, consigo compilar e debugar normalmente, porem não estou conseguindo excluir fonte do RPO, ao tentar é exibida a mensagem abaixo no log:
the user must be logged in before start build
Can't connect to server with this user:jmenezes
Compilação abortada, verifique o log ou a aba Problemas!
Vocês teriam alguma dicas pra dá?

**Comment by jerfweb** [comment]
Esse é o log completo quando compilo e tento excluir o fonte:
Iniciando a compilação do fonte:c:\Users\jerffersonsilva\Documents\fontes_tess\JERF_DESENV\WebService\WSBRASSPRESS.prw

Compilação iniciada em Wed Mar 11 2020 16:52:12 GMT-0300 (Horário Padrão de Brasília)

Source WSBRASSPRESS.prw Skipped!
Compilação finalizada com sucesso.
Compilação finalizada em Wed Mar 11 2020 16:52:23 GMT-0300 (Horário Padrão de Brasília) tempo consumido (11.26 segs.)

Iniciando a exclusão dos fontes...WSBRASSPRESS.prw

the user must be logged in before start build
Can't connect to server with this user:jmenezes
Compilação abortada, verifique o log ou a aba Problemas!

**Comment by killerall** [comment]
Boa tarde,
Consegui reproduzir aqui, obrigado por avisar.
Como paliativo, se precisar deletar, antes de rodar o comando vai na sua pasta tem no windows (%TEMP%) ou /tmp no linux, e apaga o arquivo state_c.bin

Devo lança uma correção em breve.

**Comment by jerfweb** [comment]
Bom dia,
Valeu pela dica, fico no aguardo da correção!

**Comment by killerall** [comment]
Por favor verifique se está ok agora, na 0.14.4
