### ISSUE TITLE
Implementar Hover Inspect

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/advpl-vscode#417]
Implementar a nova API do VsCode disponibilizada na release 1.43.0 para registrar uma expressão a ser considerada no Hover Inspect Variables.

API: [registerEvaluatableExpressionProvider](https://code.visualstudio.com/updates/v1_43#_extension-authoring)

Sintaxes previstas para tratamento:

- [x] Field of Alias `(cAlias)->TB_FIELD` ou `TBL->TB_FIELD`
- [x] Atributo de classe `oClasse:oAtributo1:oAtributoFilho` 
- [x] ~Método de classe `oClasse:oAtributo1:Metodo()`~
- [x] Macro substituíção `&cNomeVar`
- [ ] Desconsiderar `%Exp:` da inspeção (estudar como tratar, pois as expressões feitas não atendem e estão conflitando com Atributo)

**Comment by AlencarGabriel** [comment]
> - [x] Método de classe oClasse:oAtributo1:Metodo()

Necessário uma atenção pois foi identificado que inspecionar métodos pode causar comportamentos inesperados, pois este será executado e nem sempre deve ser, exemplo: destrutores de classe.

**Comment by izacsc** [comment]
@AlencarGabriel , se me lembro bem a implementação de avaliação não foi feita propositalmente justamente por causa dos colaterais. 

Acredito que o melhor seja que retorne somente os conteúdos de propriedades e campos e não as execuções de métodos/ funções e macrosubstituições.

@killerall

**Comment by AlencarGabriel** [comment]
Olá @izacsc , essa API não existia até a versão anterior do VsCode, foi inclusive solicita por mim e alguns outros usuários. O Hover inspect que tem por Default, antes não permitia o desenvolvedor definir como será feita a inspeção, o VsCode simplesmente detectava palavras posicionadas e as inspecionava.

Quanto a inspeção de métodos, realmente eu identifiquei nos testes com alguns colegas que não seria uma boa. Função já não estava previsto a implementação.

Porém as macro-substituições eu discordo de você, mas acho importante nós discutirmos sobre. Visto que na maioria das vezes quando este recurso da linguagem AdvPL é utilizado, é para executar algum alias, field, variável, etc... Então vejo como uma vantagem.

**Comment by killerall** [comment]
Ola, eu acredito que que toda exec que pode alterar valor, não deva ser executada no hover, porque se pode alterar um debug de maneira não intencional.
É o caso da Macro, que pode ou não esta sendo usada para chamar função e não da para saber.

Neste caso, eu proponho que houve de macro seja parametrizada, caso o dev queira utilizar, saindo como padrão desativada, o que acham?

(Método ou função acredito que não faça nunca mesmo)

**Comment by AlencarGabriel** [comment]
> Neste caso, eu proponho que houve de macro seja parametrizada, caso o dev queira utilizar, saindo como padrão desativada, o que acham?

Esta pensando exatamente isso, deixar parametrizado e por default `false`.

@izacsc , de acordo?

**Comment by izacsc** [comment]
É uma alternativa melhor. 

Ou se tivesse alguma forma de confirmar em tempo de execução, algo como um botão no hover ou enviar para  o debug console também seria interessante, só não sei se é possível.

**Comment by AlencarGabriel** [comment]
@izacsc , confirmação em tempo de execução não daria, pois a API é uma promise, então ela não espera a execução da função.
