### ISSUE TITLE
PRJToVSCODE

### ISSUE THREAD

**Issue by mrbigjorge** [totvs/advpl-vscode#418]
Bom dia.
É possível enviar um exemplo de como deve ser usado o migrador de PRJ para VsCode, por favor
Estou preenchendo os campos, mostra como processo finalizado, mas não acontece nada...o processamento ocorre de maneira bastante rápida.

Ele deveria gerar uma nova pasta dentro do diretório da workspace, correto?

Grato

Jorge H

**Comment by killerall** [comment]
Boa tarde,
Para migrar basta configurar os campos conforme a interface, segue um exemplo que fiz aqui:
Neste caso estou migrando o old_project.PRJ que esta em D:\old_prj_project
Para uma pasta nova chamada D:\test_wk_vscode\ (Atente em colocar a \ no fim pois se usar o selecionador de pasta em não coloca)
P.s Lembrando que isso só importa projeto do IDE antigo em Delphi e não do TDS.

![image](https://user-images.githubusercontent.com/4764609/76646443-befcc800-6539-11ea-8315-aba2b8645831.png)

**Comment by mrbigjorge** [comment]
Boa tarde. Obrigado pelo retorno.
Descobri o problema.
O meu PRJ estava na Unidade E, e a diretório do VSCODE eu estava apontando para unidade D, e mesmo dando a mensagem de processo finalizado com sucesso, não acontecei nada.

Apontei o diretório do VSCODE para a mesma unidade onde está o PRJ e o processo funcionou.

Grato
