### ISSUE TITLE
Debug - Smartclient.exe em segundo plano

### ISSUE THREAD

**Issue by Bzll** [totvs/advpl-vscode#422]
Boa tarde,

Estou utilizando o binário 191205P e ao tentar debugar (F5) abre-se o smartclient.exe porém em segundo plano, não chega nem aparecer a Splash.

Se apenas executo (ctrl + F5), funciona normalmente.

Alguém já passou por isso?

**Comment by killerall** [comment]
Boa tarde, você seguiu a recomendação aqui descrita:

https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-bin%C3%A1rio-191205P
?
Consegue compilar neste ambiente 19?

**Comment by Bzll** [comment]
Segui sim, e também consigo compilar

Somente no debug, ele executa o smartclient porém em segundo plano.

**Comment by killerall** [comment]
quando vc da F5, o vscode mostra o Play e stop, os botoes de debug, esse cara aparece e some, ou ele fica aparecendo como se tive-se debugando?

**Comment by Bzll** [comment]
Sim, como se fosse um debug, ele mostra o controle do debug ativo e inclusive a bottom bar fica vermelha.

**Comment by killerall** [comment]
cole aqui o settings.json deste ambiente, pf.

**Comment by Bzll** [comment]
`{
            "smartClientPath": "C:\\P12\\",
            "environment": "amb04",
            "includeList": "C:\\Users\\ciro.chagas\\OneDrive - Agro Amazônia Produtos Agropecuários S.A\\dev\\ADVPL\\P12\\Trunk Leitura\\Includes\\",
            "server": "xxx",
            "serverVersion": "191205P",
            "ssl": true,
            "port": "1250",
            "user": "ciro.chagas",
            "passwordCipher":"xx=",
            "rpoType": "TOP",
            "name": "PRD 0.7 - 1250 AMB04"    
},`

**Comment by Herbert2122** [comment]
Estou com esse mesmo problema por aqui.. como ele fica em segundo plano não consigo abrir a parte visual

**Comment by killerall** [comment]
O usuário é esta no grupo de administrador?

**Comment by Herbert2122** [comment]
No meu caso sim, inclusive consigo aplicar patchs.

**Comment by Bzll** [comment]
sim, esta como admin.

**Comment by killerall** [comment]
habilite o "advpl.logger": true,
mande dbugar
vai no %temp%, vai ter gerado AdvplDebugBridgeC_.log

**Comment by Bzll** [comment]
segue em anexo

[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/4371638/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
Cara acho que tem algo a ver com o seu path
c:\Users\ciro.chagas\OneDrive - Agro AmazÃŽnia Produtos AgropecuÃ¡rios S.A\dev\ADVPL\P12"
Tenta tira os acentos, e fazer um teste.

**Comment by killerall** [comment]
Eu usei mesma pasta e não consegui reproduzir. Veja tambem o encode do seu settings.json se esta em utf8.

**Comment by Bzll** [comment]
Alterei o path, mesma coisa.

Meu encode está para utf8 no settings.json

**Comment by killerall** [comment]
vc esta com a ultima versao do smartclient?

**Comment by Bzll** [comment]
sim, 21/02/2020

**Comment by killerall** [comment]
No console do appserver da alguma msg?

**Comment by Bzll** [comment]
não, pois o smartclient chega executar, porém em segundo plano.

**Comment by killerall** [comment]
Sim, mais no server daria uma msg:
[INFO ][SERVER] [23/03/2020 17:31:22] Starting Program SIGAFAT Thread 6812 (Rodrigo,DESKTOP-LQQ1UC5)
Tipo essa acima.

Você consegue fazer um video?

@AlencarGabriel  Você já viu algo do tipo?

**Comment by AlencarGabriel** [comment]
Bom dia @killerall .

Ainda não estou utilizando o novo binário. Mas o pessoal aqui tinha instalado pra testar, configurei no meu ambiente e consegui usar de boa.

Inclusive o comportamento esperado da marcação de debug no console apareceu.

![SmartClient Version](https://user-images.githubusercontent.com/10109480/77422853-ee6aca80-6dac-11ea-9b1e-b832f4ad72a9.png)
![AppServer Version](https://user-images.githubusercontent.com/10109480/77422855-ef9bf780-6dac-11ea-85d7-e76007f07306.png)
![Console](https://user-images.githubusercontent.com/10109480/77422984-31c53900-6dad-11ea-9eb6-e1bf4a37aa6c.png)

@Bzll , teria como mandar seu launch.json tambem?

**Comment by Bzll** [comment]
Segue;

{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Advpl Debug",
			"type": "advpl",
			"request": "launch",
			"args": [],
			"cwd": "",
			"programRun": "${command:AskForProgramName}",
			"stopOnEntry": false,
			"enviromentInfo": "${command:GetEnvInfos}",
			"workspace": "${workspaceFolder}/"
		},
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}",
			"skipFiles": [
				"<node_internals>/**"
			]
		},
		{
			"timeout": 90000
		}
	]
}

**Comment by Bzll** [comment]
Segue vídeo:
https://drive.google.com/file/d/1v8gzS-d1cAVyDo2_mFZOD5ietYvbqti6/view

**Comment by robsonrosilva** [comment]
Já passei por isso quando estava debugando, parei em um breakpoint e depois compilei, só consegui resolver isso reiniciando o appserver.
Para não acontecer mais eu geralmente encerro o debug depois compilo.

**Comment by AlencarGabriel** [comment]
> "cwd": "",

Esse argumento das suas configurações está estranho, ele não fica vazio. 

Além das recomendações do @robsonrosilva , indico você refazer o launch.json

**Comment by killerall** [comment]
O cmd deveria estar:

"cwd": "${workspaceRoot}",

**Comment by killerall** [comment]
@Bzll 
Consegui reproduzir aqui.

Eu criei uma pasta chamada:

`D:\totvs\vscode\wk_full_acento\Amazonas Produção`

E abrindo dentro dasta pasta o vscode:
`D:\totvs\vscode\wk_full_acento\Amazonas Produção\code .`

O Debug não acha mesmo.

O teste que tinha feito anteriormente, a raiz aonde abrir o code era:

`D:\totvs\vscode\wk_full_acento\`

Ai nesse caso tinha a pasta dentro com acento e nao dava problema.

Vou ver para arrumar isso, mais por hora vc vai precisar renomear essas pastas.

**Comment by Bzll** [comment]
Mas tu conseguiu reproduzir abrindo em segundo plano?

**Comment by keinou** [comment]
Ciro, boa tarde, é Rafael da J2a, este problema está relacionado ao caminho do seu projeto que possui acentuação. E não expecificamente em ficar rodando em segundo plano, podemos nota isso quando ativamos o log (advpl.logger)

**Comment by killerall** [comment]
> Mas tu conseguiu reproduzir abrindo em segundo plano?

Sim,

**Comment by killerall** [comment]
@Bzll e @keinou   Acabei de subir uma correção no github aqui:
https://github.com/totvs/advpl-vscode/blob/master/bin/alpha/win/AdvplDebugBridgeC.exe
Faz donwload desse cara, salve esse cara na pasta:

C:\Users\SEU_USUARIO\.vscode\extensions\killerall.advpl-vscode-0.14.3\bin\alpha\win

Aqui resolveu pra mim, por favor, faço o teste com esse cara.

**Comment by Bzll** [comment]
resolveu!

**Comment by Herbert2122** [comment]
@killerall  aqui tbm resolveu, vc é fera.. obg
