### ISSUE TITLE
Caminho com Acentuação

### ISSUE THREAD

**Issue by keinou** [totvs/advpl-vscode#423]
Quando caminho possui acentuação o bridge acusa não achar o caminho especificado, provavelmente por encode.

Segue LOG.
[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/4376335/AdvplDebugBridgeC_0.log)

**Comment by AlencarGabriel** [comment]
Boa tarde,

qual a versão da extensão que está instalada? Pois esse problema foi resolvido versões passadas.

**Comment by killerall** [comment]
@keinou Acredito que seja o mesmo problema aqui: #422 , eu consegui reproduzir, e estou vendo pra arruamar.

**Comment by keinou** [comment]
Esse mesmo problema mesmo. Inclusive é relacionado a mesma empresa do usuário solicitante do 422
