### ISSUE TITLE
Debug - Alias does not exist

### ISSUE THREAD

**Issue by Phabyus** [totvs/advpl-vscode#425]
Boa noite!
VScode compila sem erros; cria-se o RPO normal; Executo o programa sem problemas;
Porem, quando executo via VSCode com debug apresenta o erro:
Alias does not exist 
Segue Launch
{
	"version": "0.2.0",
	"configurations": 
	[
			{
			"name": "Advpl",
			"type": "advpl",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"programRun": "${command:AskForProgramName}",
			"stopOnEntry": false,
			"enviromentInfo": "${command:GetEnvInfos}",
			"workspace": "${workspaceFolder}/",
		}
	]
}

Segue Settings
{
    "editor.fontSize": 13,
    "files.encoding": "windows1252",
    "advpl.environments":[  
    {  
        "smartClientPath":"C:\\Totvs\\P12PADRAOR14\\Protheus\\bin\\smartclient\\",
        "environment":"P12PADRAOR14",
        "includeList":"C:\\TOTVS\\P12PADRAOR14\\PROTHEUS\\INCLUDE\\",
        "serverVersion": "131227A",
        "server":"localhost",
        "port":"1214",
        "user":"admin",
        "language": "PORTUGUESE",
        "rpoType": "TOP",
        "passwordCipher":"K1Z3WDFrVnBDOW84dzMrYWQ1YTFBQXQ0SXNhaTVhQklFQ2hIMldqTUZvejFrMTNGQjlNcWpLZElZaXJFQzdYN3lxd01OWmxMWGNvS1dOU0JmMWJ0S1J6QW4rYkJDT2IyYW1hVk42anVIS0RQclBKVmFmc2N5ZVQwdUxGdGxlbzg="
    }
],
"advpl.selectedEnvironment": "P12PADRAOR14",
"advpl.compile_force_recompile": true,
"advpl.compile_threads": 4,
"advpl.startProgram": "SIGAADV",
"advpl.debug_multiThread" : true,
"advpl.debug_ignoreSourceNotFound" : true,
"advpl.debug_showTables" : true,
"advpl.debug_showPrivates" : true,
"advpl.debug_showPublic" : true,
"advpl.debug_showStatics": true,
"advpl.logger": true,
"totvsLanguageServer.clearConsoleBeforeCompile": true,
"mssql.connections": [
    {
        "server": "DESKTOP-FC3VF53\\SQLEXPRESS",
        "database": "",
        "authenticationType": "Integrated",
        "password": "",
        "emptyPasswordInput": false,
        "savePassword": false
    }
],
"workbench.iconTheme": "advplIcons",
"files.associations": {
    "*.prw": "advpl"
},
}

Segue PRW
#Include "Totvs.ch"
User Function zTst()
Local aAreaB1	:= SB1->(GetArea())
If Select("SB1") > 0
  MsgStop("Tabela SB1 já está aberta!", "Atenção")
Else 
   Alert("Tabela ok")
EndIf
Alert("Teste...")
Return

Segue erro
THREAD ERROR ([3324], usr, DESKTOP-FC3VF53)   27/03/2020 01:46:21
Alias does not exist SB1 on U_ZTST(TESTE.PRW) 27/03/2020 00:57:48

[TOTVS build: 7.00.131227A-20161110 NG]
Called from U_ZTST(TESTE.PRW) 27/03/2020 00:57:48 line : 5
Called from STATICCALL(TESTE.PRW) 27/03/2020 00:57:48 line : 5
Publicas
  Public 1: CPAISLOC(C) :BRA
  Public 2: ASX8(A) :

**Comment by AlencarGabriel** [comment]
Bom dia @Phabyus ,

você está executando a função `U_zTst()` diretamente no start do Debug no VsCode?

**Comment by Phabyus** [comment]
Bom dia! Obrigado pelo rápido retorno!
Sim, eu estou clicando F5...
Obrigado
P.S.: É possível enviar imagens pelo GitHub?

**Comment by AlencarGabriel** [comment]
Sim, só arrastar ou colar uma imagem em memória no box de mensagem.

Acredito que seu problema então não esteja relacionado ao debug em si, mas que você está executando diretamente uma função que acessa dados sem ter preparado o ambiente (PREPARE ENVIROMENT ou RPCSetEnv, etc...)

Por isso o erro "Alias Does not exists".

**Comment by Phabyus** [comment]
Eu fiz a seguinte alteração no script (não dá erro, mas não aparece nenhum mensagem):
#Include "Totvs.ch"
#Include "TBICONN.ch"

user function zTst1()
     Local cEmpAux := "99"
     Local cFilAux := "01"    
     
     PREPARE ENVIRONMENT EMPRESA cEmpAux FILIAL cFilAux
	 
	 MsgStop("Pare", "Atenção")
	 Alert("Pare novamente")

	zTst2()

Return

User Function zTst2()

	Local aAreaB1	:= SB1->(GetArea())

    If Select("SB1") > 0
		MsgStop("Tabela SB1 já está aberta!", "Atenção")
	Else 
		Alert("Tabela ok")
	EndIf

	Alert("Teste...")
	
	RestArea(aArea)

Return

**Comment by AlencarGabriel** [comment]
>PREPARE ENVIRONMENT EMPRESA cEmpAux FILIAL cFilAux
> 
> MsgStop("Pare", "Atenção")
> Alert("Pare novamente")
>
>zTst2()

aqui na chamada da função vc deve colocar o `U_`

**Comment by Phabyus** [comment]
kkkk Mil desculpas!
Eu coloquei e não acontece além de um som... Não aparece as mensagens!

**Comment by AlencarGabriel** [comment]
troca suas mensagens por Conout e veja o que é escrito no AppServer. 

Por estar fazendo prepare environment ele pode estar no modo Blind.

**Comment by Phabyus** [comment]
CARAI! PQP! Show...
Fiquei um tempão para resolver....
Obrigadão

Como posso fazer o display destas mensagens?

**Comment by AlencarGabriel** [comment]
Dá uma olhada depois nesse artigo: https://centraldeatendimento.totvs.com/hc/pt-br/articles/360022439332-MP-ADVPL-ERRO-JOB-THREADS-DOESN-T-SUPPORT-REMOTE-VISUAL-COMPONENTS Ele explica esse tipo de comportamento quando a rotina não é visual.

Em tese não apresentará a mensagem como se estivesse executando por uma rotina de dentro do Protheus.

Mas vc poderia testar usando RPCSetEnv(). Se não me engano iniciando o ambiente por essa forma apresenta os Alert().

**Comment by Phabyus** [comment]
Infelizmente, não funcionou com RPCSetEnv()...
Mas tudo bem! 
Valeu pela ajuda...
Abração

**Comment by robsonrosilva** [comment]
Já passei por isso por estar com o smartclient que está configurado no settings desatualizado.
Tinha atualizado o Appserver e o smartclient local não.

**Comment by AlencarGabriel** [comment]
@killerall acredito que essa possa ser fechada também. Não era problema relacionado a extensão.
