### ISSUE TITLE
Não aparece "ApMsgAlert" apos RpcSetType e RpcSetEnv

### ISSUE THREAD

**Issue by Phabyus** [totvs/advpl-vscode#426]
Boa noite!
A função ApMsgAlert não estão aparecendo depois da função RpcSetType e RpcSetEnv

Veja que no script abaixo, quando executo u_zMens("0") aparece, mas como u_zMens("1")  não:
#include "totvs.ch"
#include "tbiconn.ch"
#include "topconn.ch"
*****************************
User Function zMens(aparm)
*****************************
local a := aparm
if a = "1"
    RpcSetType(3)
    RpcSetEnv("99","01","admin"," ",'FAT')
endif

ApMsgAlert("1","Aviso")

Return

Obrigado

**Comment by killerall** [comment]
Boa noite.

Quando você faz um RpcSetEnv, a thread advpl fica no modo JOB, aonde ela não tem tela, E a função de alert que você esta usando, verifica esse tipo de coisa. Você pode usar a MsgAlert pura.

Acredito que aqui não seja o local ideal para você tirar duvidas de ADVPL, esse repositorio é para questões relacionada a extensão do vscode.
