### ISSUE TITLE
Problema em compilar File/Folder

### ISSUE THREAD

**Issue by mmateusmedeiros** [totvs/advpl-vscode#427]
Ao selecionar a opção File/Folder para compilar um "projeto" completo, o mesmo não é replicado no repositório do ambiente selecionado.

**Comment by AlencarGabriel** [comment]
Bom dia @mmateusmedeiros ,

poderia explicar melhor seu problema? Se possível com algum vídeo/GIF ou imagem que nos faça entender melhor?

**Comment by mmateusmedeiros** [comment]
Claro @AlencarGabriel. 

Fui realizar a compilação do projeto completo através da opção compilar files/folder, conforme abaixo. Após a finalização da compilação, acesso as rotinas após aplicação no ambiente compilado, e o mesmo retorna que a função não está compilada. Isso não ocorre se eu compilar funções individualmente. 

![vscode](https://user-images.githubusercontent.com/8399045/78031956-a1ea3680-733a-11ea-9227-5122621a960f.png)

**Comment by AlencarGabriel** [comment]
Obrigado pelas informações,

pelo que pude observar no seu print, você não está utilizando esta extensão, e sim a https://github.com/totvs/tds-vscode. Sendo assim peço que reabra essa issue lá no outro repositório para que os responsáveis possam te ajudar.

**Comment by mmateusmedeiros** [comment]
Ah, Ok! 
Obrigado!
