### ISSUE TITLE
Problema ao fazer Debug

### ISSUE THREAD

**Issue by fapetrini** [totvs/advpl-vscode#429]
Bom dia pessoal !

Quando estou fazendo o Debug está aparecendo uma mensagem e a tela do Protheus não é chamada. Alguem já pegou esse erro ?

![image](https://user-images.githubusercontent.com/62894011/78150358-93208400-740d-11ea-8e08-833eb8e0bf6f.png)

**Comment by killerall** [comment]
Boa tarde,
Você  tem acentos na sua pasta aonde esta os fontes?

**Comment by fapetrini** [comment]
Killerall

Estou vendo as pastas e não tenho acentos, olha como está

![image](https://user-images.githubusercontent.com/62894011/78157116-f9110980-7415-11ea-959e-22b3e03a9525.png)

**Comment by AlencarGabriel** [comment]
Boa tarde @fapetrini ,

seu problema talvez não é porque você está tentando debugar no serviço master do balance?

https://centraldeatendimento.totvs.com/hc/pt-br/articles/360018622292-MP-ADVPL-Error-loading-debug-thread-First-BALANCE-

**Comment by fapetrini** [comment]
@AlencarGabriel Boa tarde !

Vou dar uma olhada nesse artigo, eu estava debugando normal da forma que está hoje, acredito que está no master, a não ser que mudou alguma coisa com as atualizações.

Vou fazer aqui e ver o que vai dar, eu posto aqui se deu certo.

**Comment by fapetrini** [comment]
Boa tarde Pessoal !

Eu ainda não cheguei a montar o ambiente mas verificando um outro servidor onde tenho VSCODE está com o software atualizado e também apontando para o master, Debug funcionando 100%

**Comment by AlencarGabriel** [comment]
Boa tarde,

mas as configurações para aceitar a conexão estão conforme o artigo que te enviei? Chegou a testar DEBUG em algum slave para garantir?

**Comment by fapetrini** [comment]
@AlencarGabriel Minha configuração não está igual, mas eu cheguei a criar a conexão do SLAVE1 e dá uma outra mensagem, vou gerar aqui e postar.

**Comment by fapetrini** [comment]
Obrigado @AlencarGabriel  e a todos pela ajuda. Descobri o que estava errado, estava passando uma informação errada quando ele chama a tela para adicionar o ambiente. Mas pelo que estou vendo agora tem mesmo que fazer o DEBUG pelo SLAVE1 e não direto ao master, agora não me pergunte o porque minha outra base está dando certo.

Valeu a Todos !

**Comment by AlencarGabriel** [comment]
Fico feliz em ter ajudado.

Quanto a funcionar no outro ambiente, pode ser por conta da configuração do INI ou da versão dos binários.

**Comment by fapetrini** [comment]
Entendi, vou tentar ver o mistério quando tiver um tempo rsrs.

Valeu Brother !
