### ISSUE TITLE
configuração advpl.alpha_compile esteja habilitada

### ISSUE THREAD

**Issue by lfmonteiro** [totvs/advpl-vscode#431]
Será que algum poderia me dar uma ajuda?
Atualizei o binário da TOTVS "191205P"
E quando realizo as configurações no VSCODE e tento realizar uma aplicação de pacote essa mensagem é apresentada.
"Para aplicar somente arquivos do patch atualizados é necessário que a configuração advpl.alpha_compile esteja habilitada."
entrei no link
Saiba mais em: https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs
realizei as verificações mas mesmo assim não consegui.
algumas das mensagens.
Iniciando aplicação de patch...
"{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":-1,"Column":-1,"Type":0,"Message":"Para utilizar SSL na conexao ou binario superior ao 170117A, utilize o alpha compile. Maiores info. em: https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-bin%C3%A1rio-191205P "}]}]}"

Será que alguém poderia me auxiliar?

**Comment by killerall** [comment]
Boa tarde,
Vc seguiu a orientação daqui para configurar o binario 19?
https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-bin%C3%A1rio-191205P

**Comment by lfmonteiro** [comment]
sim.... mesmo assim ele não funciona....
não sei se fiz algo errado....

segue meu settings.json
se puder dar uma olhada..
{
    "advpl.environments": [
        {
            "environment": "Protheusv27",
            "name": "TOTVS_Protheus_Protheusv27",
            "server": "localhost",
            "port": "2020",
            "serverVersion": "191205P",
            "passwordCipher": "ZC95Ti81b0ZnaCtVWTMzbTVTcUlIb1kwUU9UT0YrWCtDbFo3ZGxhN2hJUm9RRGRYVTBhTEpiRGJiTUhDMXZlODF3Zkh5K2ZLNURveTFCVkRISkNqYTZKRFZOeFBrL0NDR1JQNkQ1WFpIMUd5K0p5NFFVVTJNUXdPK01qRHk1aUE=",
            "includeList": "c:\\Users\\Luiz Fernando\\Documents\\Includes\\",
            "user": "admin",
            "smartClientPath": "c:\\TOTVSP12\\Protheus1227\\Protheus12\\BIN\\Smartclient",
            "enable": true,
            "ssl": false
        }
    ],
    "advpl.selectedEnvironment": "TOTVS_Protheus_Protheusv27",
    "startProgram": "SIGAMDI",
	"authorization_generation": "",
	"authorization_validation": "",
	"authorization_permission": "",
	"authorization_code": "",
	"compileFolderRegex": ".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl|tlpp|4gl|per|msg|ahu)",
    "pathPatchBuild": "C:\\Pacotes\\",
    "alpha_compile": true,
	"debug_multiThread": false,
	"debug_ignoreSourceNotFound": true,
	"debug_showTables": true,
	"debug_showPrivates": true,
	"debug_showPublic": true,
	"debug_showStatics": false,
	"compile_force_recompile": false,
	"logger": true,
    "compile_threads": 4,
    "advpl.workspaceFolders": "c:\\Users\\Luiz Fernando\\Documents\\Protheus_1227;",
	
}

**Comment by AlencarGabriel** [comment]
@lfmonteiro , você está olhando em quais configurações? (Workspace ou de usuário)

O VsCode considera por ordem de precedência primeiro as da workspace e depois as de usuário. Veja se as suas não estão conflitando uma com a outra. 

Pois para ambas mensagens sugerirem você habilitar a configuração `alpha_compile`, é possível que alguma configuração esteja negando este parâmetro.

**Comment by killerall** [comment]
E outra coisa, vc desligou o SSL no  ini do appserver?

**Comment by lfmonteiro** [comment]
n"o possuo configura,c"ao SSL no Appserver

**Comment by lfmonteiro** [comment]
consegui ajustar e configurar....
realmente  não estava configurado nas configurações o alpha compile
ajustei também no Appserver.ini  a configuração SSL
consegui compilar
Muito Obrigado

**Comment by AlencarGabriel** [comment]
Acabei de identificar uma coisa nas suas configurações ai. 

Está faltando o prefixo `advpl.` nelas. Não tinha me atentado antes. 

Mas que bom que resolveu!
