### ISSUE TITLE
Exclusão de fontes

### ISSUE THREAD

**Issue by lafelvr** [totvs/advpl-vscode#433]
Ao tentar excluir um fonte do RPO na versão 27, é apresentada a mensagem abaixo:

Iniciando a exclusão dos fontes...TESTE.PRW

the user must be logged in before start build
Can't connect to server with this user:XXXPT
Compilação abortada, verifique o log ou a aba Problemas!

Log AdvplDebugBridgeC_0.log só registra:
[0x000032e0][28-04-2020 10:49:35] - Start AdvplDebugBridge
[0x000032e0][28-04-2020 10:49:35] - Compile key empty.
[0x000032e0][28-04-2020 10:49:35] - End AdvplDebugBridge

Compilação é feita normalmente, assim como listagem de fontes.
Somente exclusão apresenta inconsistência.

Att.,

**Comment by lafelvr** [comment]
![image](https://user-images.githubusercontent.com/42899193/80495850-d1429200-893e-11ea-965b-966663b32f70.png)

**Comment by AlencarGabriel** [comment]
Bom dia @lafelvr ,

poderia tentar o procedimento do seguinte link: https://github.com/totvs/advpl-vscode/issues/416#issuecomment-597865521 ?

Nos reporte aqui se funcionou ou não, pois esse mesmo problema ocorreu na issue #416 e foi contornado assim.

Em breve sairá uma versão com isso corrigido.

**Comment by lafelvr** [comment]
@AlencarGabriel 

Obrigado pela ajuda.
Resolveu, só tenho que ficar excluindo ele toda vez que for excluir um fonte.

Fico no aguardo da versão corrigida e mais uma vez obrigado.

**Comment by killerall** [comment]
Deve estar corrigido na 0.14.4, por favor consegue verificar?
