### ISSUE TITLE
Geração de Patch

### ISSUE THREAD

**Issue by andersongonca** [totvs/advpl-vscode#437]
Alguem pode me ajudar, não estou conseguindo gerar um patch!

Comando 'Advpl - Patch - Build - Cria um patch Patch(PTM) da lista de arquivo.' resultou em um erro (Running the contributed command: 'advpl.patch.build' failed.)

{
    "advpl.workspaceFolders": "d:\\Totvs12\\Protheus\\my projects\\AGM System;",
    "advpl.startProgram": "SIGAMDI",
    "advpl.pathPatchBuild": "c:\\patchs\\",
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.environments": [
        {
            "name": "AGMSystem",
            "smartClientPath": "D:\\Totvs12\\Protheus\\bin\\smartclient",
            "environment": "AGMSystem",
            "includeList": "D:\\Totvs12\\Protheus\\include\\",
            "server": "192.168.0.20",
            "port": "9070",
            "user": "admin",
            "passwordCipher": "1"
        }
    ],
    "advpl.debug_multiThread": true,
    "files.encoding": "windows1252",
    "advpl.selectedEnvironment": "AGMSystem",
    "advpl.projectActive": "AGM System",
    "totvsLanguageServer.welcomePage": false,
    "totvsLanguageServer.askEncodingChange": false,
    "advpl.alpha_compile": true
}

**Comment by AlencarGabriel** [comment]
Olá @andersongonca ,

o diretório `c:\patchs\` existe? Conforme indicado na documentação https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs ele precisa existir.

Caso exista e ainda sim não esteja conseguindo gerar o patch, você está também com a extensão TDS VsCode instalada?
