### ISSUE TITLE
Organizar os Server em pastas

### ISSUE THREAD

**Issue by douglasbergamo** [totvs/advpl-vscode#438]
Em alguns temos mais de um ambiente de acesso, para visualmente nao ficar poluido, seria interessante  poder organizar os server dentro de pastas, exemplo:

- Cliente1
  - Producao
  - Homologacao
- Cliente2
  - Producao
  - REST
  - Schedule

**Comment by AlencarGabriel** [comment]
Olá @douglasbergamo ,

no gerenciador de ambientes da visão Explorer, já é possível renomear os servidores, serviços e ambientes conforme sua necessidade.

![image](https://user-images.githubusercontent.com/10109480/81705635-a0398580-9445-11ea-9463-7bb2b686dc2b.png)

Sugiro tambem utilizar a extensão [AdvPL Project Manager](https://marketplace.visualstudio.com/items?itemName=AlencarGabriel.advpl-switch-project) criada pensando exatamente nos analistas que trabalham com vários clientes/ambientes. Melhorando tanto a organização dos projetos quanto a dos ambientes.

**Comment by fabricioereche** [comment]
> Olá @douglasbergamo ,
> 
> no gerenciador de ambientes da visão Explorer, já é possível renomear os servidores, serviços e ambientes conforme sua necessidade.

Este gerenciador de ambientes, na visão de explorer, não existe, foi feita alguma alteração nas ultimas versão do VSCode?

**Comment by AlencarGabriel** [comment]
Olá @fabricioereche , será que você não está usando a extensão versão TDS?

**Comment by fabricioereche** [comment]
Desculpe, estava vendo uma isseu do plugin do TDS e achei que estava falando por lá. Mas o plugin do TDS não é o oficial? Ambos podem ser utilizados?

**Comment by AlencarGabriel** [comment]
> Desculpe, estava vendo uma isseu do plugin do TDS e achei que estava falando por lá. Mas o plugin do TDS não é o oficial? Ambos podem ser utilizados?

Ambas extensões (TDS ou esta) são oficiais da TOTVS. 

Porém foram desenvolvidas em cima de premissas um pouco diferentes. 

Em suma, ambas funcionam.
