### ISSUE TITLE
Configuração de um novo servidor

### ISSUE THREAD

**Issue by GersonBelini** [totvs/advpl-vscode#439]
Ao finalizar a configuração de um novo servidor, quando salvo, recebo a mensagem:

Cannot read property 'length' of undefined

**Comment by AlencarGabriel** [comment]
Poderia fazer um vídeo/GIF demonstrando como está sendo feito a configuração até que o erro seja apresentado?

**Comment by GersonBelini** [comment]
[ScreenHunter 128.zip](https://github.com/totvs/advpl-vscode/files/4617315/ScreenHunter.128.zip)

**Comment by AlencarGabriel** [comment]
@GersonBelini, assisti seu vídeo, e percebi que você não está usando esta extensão aqui. Esse repositório é da extensão AdvPL Vscode, e você está usando a [TDS VsCode](https://github.com/totvs/tds-vscode).

Peço por gentileza que encerre esta issue, e reabra no outro repositório.

**Comment by GersonBelini** [comment]
Chamado aberto em lugar errado.
