### ISSUE TITLE
Debug via Webapp

### ISSUE THREAD

**Issue by jerfweb** [totvs/advpl-vscode#440]
Prezados,
Estou necessitando realizar um debug via webapp, já configurei no launch a chamada do webapp, ele  abri o navegador, porem passando a url com https://, tem alguma configuração pra ele passar a url com http://?

**Comment by killerall** [comment]
Boa tarde,

Dentro do Env, coloca ssl : false.
Ele vai chamar a url com http.

**Comment by jerfweb** [comment]
Rodrigo, bom dia!

Estou trabalho com o appserver na build 191205P, se colocar FALSE no ssl, não consigo compilar.

**Comment by killerall** [comment]
A configuração ficou meio vinculada, se usa ssl, ele acha que vai usar https.
Se quiser vc pode desligar o SSL da porta.

https://tdn.totvs.com/pages/viewpage.action?pageId=538506132

Att.
