### ISSUE TITLE
Erro Generate Ws Protheus

### ISSUE THREAD

**Issue by williamsrcosta** [totvs/advpl-vscode#441]
Boa Noite, estou tentando fazer uma geração de WebService Protheus no VSCODE.
E agora começou a aparecer essa mensagem, isso antes não acontecia, não precisava ter o token para gerar client de WebService.

Conseguem me ajudar por favor?

Segue o erro abaixo:

One or more validations errors detected:
- Authorization token was not informed.

**Comment by AlencarGabriel** [comment]
Boa noite @williamsrcosta

Poderia postar aqui o Json das configurações do seu ambiente?

**Comment by williamsrcosta** [comment]
Segue conforme solicitado

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Users\\william.costa\\OneDrive\\Adoro\\totvs\\adoro\\teste\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Debug_MultiThread",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Users\\william.costa\\OneDrive\\Adoro\\totvs\\adoro\\teste\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAMDI",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_ADGPE024P",
			"description": "()"
		},
		{
			"args": [
				" ()"
			],
			"label": "U_ADGPE024P",
			"description": " ()"
		},
		{
			"args": [],
			"label": "U_ADGPE024P",
			"description": ""
		},
		{
			"args": [],
			"label": "U_ADFIN083R",
			"description": ""
		},
		{
			"args": [],
			"label": "u_xxx",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "u_ADGPE055P",
			"description": "()"
		},
		{
			"args": [
				" ()"
			],
			"label": "u_ADGPE055P",
			"description": " ()"
		},
		{
			"args": [],
			"label": "u_adlog017",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "u_TESTEWILL",
			"description": "()"
		},
		{
			"args": [
				" ()"
			],
			"label": "u_TESTEWILL",
			"description": " ()"
		},
		{
			"args": [],
			"label": "u_adlog003p",
			"description": ""
		},
		{
			"args": [],
			"label": "u_adlog007p",
			"description": ""
		},
		{
			"args": [],
			"label": "u_adlog006p",
			"description": ""
		},
		{
			"args": [],
			"label": "U_TESTEWILL",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_ADVEN002P",
			"description": "()"
		},
		{
			"args": [],
			"label": "U_ADVEN002P",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_QGBLOQCLI",
			"description": "()"
		},
		{
			"args": [],
			"label": "U_QGBLOQCLI",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "_TESTEWILL",
			"description": "()"
		},
		{
			"args": [],
			"label": "_TESTEWILL",
			"description": ""
		},
		{
			"args": [],
			"label": "u_adven",
			"description": ""
		},
		{
			"args": [],
			"label": "u_adlog",
			"description": ""
		},
		{
			"args": [],
			"label": "u_adlog017p",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}

**Comment by AlencarGabriel** [comment]
@williamsrcosta , verifiquei suas configurações, e percebi que você não está usando esta extensão aqui. Esse repositório é da extensão AdvPL Vscode, e você está usando a [TDS VsCode](https://github.com/totvs/tds-vscode).

Peço por gentileza que encerre esta issue, e reabra no outro repositório.
