### ISSUE TITLE
Nao consigo deugar vscode com rotina web ADVPL

### ISSUE THREAD

**Issue by felipomelo** [totvs/advpl-vscode#442]
Tenho rotinas web a debugar, porem apesar de configurar o vscode para multithread, o mesmo nao para no ponto de interrupçõ selecionado. o que posso fazer

**Comment by AlencarGabriel** [comment]
Olá @felipomelo ,

Vc está tentando depurar um serviço WEB (Webservice, REST, etc, ...) ou WebApp?

**Comment by felipomelo** [comment]
Ola Gabriel

 

É um WebApp

 

grato

 

De: Gabriel Alencar <notifications@github.com> 
Enviada em: quarta-feira, 20 de maio de 2020 13:55
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: felipomelo <felipo.melo@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Nao consigo deugar vscode com rotina web ADVPL (#442)

 

Olá @felipomelo <https://github.com/felipomelo>  ,

Vc está tentando depurar um serviço WEB (Webservice, REST, etc, ...) ou WebApp?

**Comment by AlencarGabriel** [comment]
Dê uma olhada então na wiki: https://github.com/totvs/advpl-vscode/wiki/Utilizando-WebAPP Nela há instruções para configuração correta para debugs com WebApp.

**Comment by felipomelo** [comment]
Te explicando Gabriel

 

Aqui usamos o Protheus e temos um sistema (base Protheus) que udesenvolvemos com diveras rotinas web, as quais são desenvolvidas em html tl++ e asp, estou querendo debyugar uma destas rotinas. Não se trata e smartcliente web.

 

Eu criei uma configuração de debug onde aponto para o appserver exclusivop deste sistema(SIS) apontei tb o smartclient para a mesma porta deste app.

 

Quandod ebugo olho no sole que ambos esta usando o mesmo server, so que o debug so para se eu tentar debugar uma rotina pelo smartclient, se eu tentar debugar acessando o Smart e executando a rtoina dentro do app, ele não para . 

 

No eclipse isto não acontecia. No vs-code acontece

 

Não sei se deu para entender

 

 

De: Gabriel Alencar <notifications@github.com> 
Enviada em: quarta-feira, 20 de maio de 2020 15:41
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: felipomelo <felipo.melo@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Nao consigo deugar vscode com rotina web ADVPL (#442)

 

Dê uma olhada então na wiki: https://github.com/totvs/advpl-vscode/wiki/Utilizando-WebAPP Nela há instruções para configuração correta para debugs com WebApp.

**Comment by AlencarGabriel** [comment]
@felipomelo ,

entendi o cenário. E é basicamente assim mesmo para depurar esse tipo de serviço. Estar conectado no mesmo AppServer da aplicação e habilitar o multi-thread.

Pergunta, você está usando realmente esta extensão aqui? Ou está usando a https://github.com/totvs/tds-vscode? Pois teve um momento onde você falou da porta do debug aparecer no console, porém essa extensão aqui não mostra essa informação.

**Comment by felipomelo** [comment]
Tanto o vs-code como o tds-vscode estão atualizados coma ultima versõ.

 

 

De: Gabriel Alencar <notifications@github.com> 
Enviada em: quarta-feira, 20 de maio de 2020 16:48
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: felipomelo <felipo.melo@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Nao consigo deugar vscode com rotina web ADVPL (#442)

 

@felipomelo <https://github.com/felipomelo>  ,

entendi o cenário. E é basicamente assim mesmo para depurar esse tipo de serviço. Estar conectado no mesmo AppServer da aplicação e habilitar o multi-thread.

Pergunta, você está usando realmente esta extensão aqui? Ou está usando a https://github.com/totvs/tds-vscode? Pois teve um momento onde você falou da porta do debug aparecer no console, porém essa extensão aqui não mostra essa informação.

**Comment by felipomelo** [comment]
De: Gabriel Alencar <notifications@github.com> 
Enviada em: quarta-feira, 20 de maio de 2020 16:48
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: felipomelo <felipo.melo@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Nao consigo deugar vscode com rotina web ADVPL (#442)

 

@felipomelo <https://github.com/felipomelo>  ,

entendi o cenário. E é basicamente assim mesmo para depurar esse tipo de serviço. Estar conectado no mesmo AppServer da aplicação e habilitar o multi-thread.

Pergunta, você está usando realmente esta extensão aqui? Ou está usando a https://github.com/totvs/tds-vscode? Pois teve um momento onde você falou da porta do debug aparecer no console, porém essa extensão aqui não mostra essa informação.

**Comment by AlencarGabriel** [comment]
Então, esse aqui não é o repositório da extensão TDS-VSCODE, por isso não consegui entender seu cenário.

Peço por gentileza que reabra essa issue no outro repositório: https://github.com/totvs/tds-vscode, lá eles poderão te ajudar, pois nessa aqui o debug multi-thread está funcionando.
