### ISSUE TITLE
Compilar arquivos remotos 

### ISSUE THREAD

**Issue by AlexandreBeh** [totvs/advpl-vscode#443]
Olá,

estou tendo problemas para compilar os fontes no VSCode com os arquivos que ficam em um endereço remoto. Eu consigo editar eles e salvar normalmente, mas quando vou compilar, a extensão traz um retorno que o arquivo não foi encontrado.

> File file://192.168.2.200/Totvs/Totvs12/Microsiga/Protheus/my_projects/Tr_25/faturamento/atualizacoes/Itens.prw not found.

Quando eu copio o arquivo para a maquina local ocorre a compilação sem erros. 
Não é possível compilar arquivos remotos?

**Comment by killerall** [comment]
Boa tarde
A extensão não foi desenvolvida pensando neste tipo de uso. 
Hoje não é possivel.
Se você esta utilizando o windows, mapeie no explorar o ip apara uma unidade ( tipo z:) e utilizei como unidade, ai vai funcionar.

**Comment by AlexandreBeh** [comment]
Fiz isto e funcionou, muito obrigado pela ajuda.
