### ISSUE TITLE
Command 'Add new environment' resulted in an error 

### ISSUE THREAD

**Issue by lucaslopezvr** [totvs/advpl-vscode#444]
Boa tarde!

Estou tendo um problema onde ao tentar adicionar um ambiente de conexão no vscode este problema é manifestado.

Windows 10 64 bits
Vscode 1.45.1
Extensão do vscode mais recente baixada no dia 28/05

Segue os prints....

Desinstalei o vscode, realizei a instalação separado e desinstalei e removi todos as extensões os arquivos temporários porém sem sucesso.

![Erro](https://user-images.githubusercontent.com/66091301/83191560-97fe6d00-a10a-11ea-82a6-9f2e0f010656.jpg)
![Erro1](https://user-images.githubusercontent.com/66091301/83191563-98970380-a10a-11ea-8f61-9e615e796df6.jpg)

**Comment by killerall** [comment]
Boa noite,
Tente abrir um fonte antes, de mandar adicionar o ambiente.

**Comment by lucaslopezvr** [comment]
Muito obrigado! Funcionou  @killerall
