### ISSUE TITLE
Debug não para no Breakpoint

### ISSUE THREAD

**Issue by WFilhocompany** [totvs/advpl-vscode#449]
Olá à todos,

    Estou com uma situação que não consigo resolver, já desinstalei e instalei o VSCode umas 10 vezes e o problema ainda persiste. O que ocorre ?
    Eu abro um Fonte e coloco um Breakpoint no mesmo e no Debug o VSCode não respeita o ponto de parada, em algumas situações ele passa pelo breakpoint e depois volta, seria mais ou menos como estar debugando fonte na versão errada, eu sei que passou direto e depois voltou por causa das variáveis que não deveriam conter valor naquele momento e estão com valores atribuídos.
    É um situação bastante estranha, pois como eu disse depende de onde sei breakpoint está no fonte ele para e depois volta ou então passa direto, nunca respeitando o momento correto do debug.

    Alguém já passou por algo semelhante ou teria um norte para me ajudar ?

**Comment by AlencarGabriel** [comment]
Olá @WFilhocompany ,

somente para confirmar, qual extensão para desenvolvimento você está usando? TDS-Vscode ou Advpl-VsCode?

**Comment by WFilhocompany** [comment]
@AlencarGabriel ,

    Estou utilizando a totvs.tds-vscode.

**Comment by AlencarGabriel** [comment]
Então, este repositório é da extensão AdvPL VsCode. 

Estranhei sua solicitação, pois esta está funcionando normalmente. E lembro-me de ter visto algumas reclamações sobre isso na outra.

Peço por gentileza que reabra sua issue no repositório da https://github.com/totvs/tds-vscode

**Comment by WFilhocompany** [comment]
@AlencarGabriel , eu posso utilizar as duas extensões ??? Ou corro risco de mais problemas.

**Comment by AlencarGabriel** [comment]
Não é possível ter duas extensões de suporte a uma linguagem no VsCode. 

Isso causa uma série de conflitos por conta das configurações. Recomendo utilizar apenas uma.
