### ISSUE TITLE
Erro ao aplicar patch's

### ISSUE THREAD

**Issue by alexandroale77** [totvs/advpl-vscode#450]
Bom dia, pessoal

Estou trabalhando home office e utilizo uma VPN o meu servidor fica em um endereço 192.168.xx.xxx e na minha maquina eu executo VSCODE no meu servidor tenho appserver com a ultima versão 19 com ssl e tanto componente TOTVS e com l Love ADVPL  não consigo aplicar patch's algum erro apresentado abaixo

TOTVS
"FILE COULD NOT BE COPIED TO THE SERVER"

I LOVE ADVPL
Iniciando aplicação de patch...
{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't connect to server:check if appserver use SSL"}]}]}

Segue também o log do appserver

**Comment by alexandroale77** [comment]
[alexandro_server.log](https://github.com/totvs/advpl-vscode/files/4836651/alexandro_server.log)

**Comment by AlencarGabriel** [comment]
Olá @alexandroale77 ,

o seu patch está em um caminho de rede, ou local?

**Comment by alexandroale77** [comment]
Oi, sim o patch eu deixo em minha maquina.

Grato

**Comment by killerall** [comment]
Pela mensagem, ele não conseguiu nem conectar no server, você tentou compilar neste ambiente?

**Comment by alexandroale77** [comment]
Então se eu coloco na versão 17 appserver eu consigo aplicar os patchs

**Comment by alexandroale77** [comment]
Compilando eu consigo
![Screenshot_12](https://user-images.githubusercontent.com/29817613/85860360-0f203300-b795-11ea-9722-101a1a5b9080.png)
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85860365-10516000-b795-11ea-8161-63f5404eca88.png)

**Comment by killerall** [comment]
Lembrando que no 19 tem que habilitar o alpha, e gerar o cipher novo (https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-bin%C3%A1rio-191205P)
Se ja fez isso, faz o seguinte.
No setting, adiciona o advpl.logger :true

Vai gerar no seu temp (%TEMP%) o arquivo, AdvplDebugBridgeC.log, cole ele aqui.

Att.

**Comment by AlencarGabriel** [comment]
> Compilando eu consigo
> ![Screenshot_12](https://user-images.githubusercontent.com/29817613/85860360-0f203300-b795-11ea-9722-101a1a5b9080.png)
> ![Screenshot_11](https://user-images.githubusercontent.com/29817613/85860365-10516000-b795-11ea-8161-63f5404eca88.png)

@killerall , esses logs são da versão TDS VsCode.

**Comment by alexandroale77** [comment]
Sim

**Comment by killerall** [comment]
Bem se esta utilizando a extensão do TDS, precisa entrar em contato com a extensão deles.
Lembrando que as 2 não funciona junto.

**Comment by AlencarGabriel** [comment]
@alexandroale77 , este repositório é referente a extensão AdvPL VsCode.

Gostaria de testar utilizando esta aqui ao invés da versão TDS? Se sim, peço que desinstale a versão TDS para evitar conflitos, e siga as configurações destas Wikis: https://github.com/totvs/advpl-vscode/wiki/Criação-de-ambiente-facilitada, https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-binário-191205P e https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs

Caso tenha alguma dificuldade estamos aqui para ajudá-lo.

**Comment by alexandroale77** [comment]
Oi, você quer que eu deixo apenas I LOVE ADVPL e tire o TDS?

Grato

**Comment by AlencarGabriel** [comment]
Isso, as duas não são compatíveis. Não é possível usar duas extensões que dão suporte ao AdvPL ao mesmo tempo.

**Comment by alexandroale77** [comment]
Só
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85870153-13ebe380-b7a3-11ea-8f39-ada73f0a41f0.png)
 estou com Extensão do Rodrigo e não foi

**Comment by AlencarGabriel** [comment]
Pode colocar aqui o arquivo `AdvplDebugBridgeC.log` que está no seu %temp% ?

**Comment by alexandroale77** [comment]
Sim claro
[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/4837596/AdvplDebugBridgeC_0.log)

**Comment by AlencarGabriel** [comment]
Não teve erro no Bridge.

Vamos as perguntas:
 - Teu AppServer é realmente a versão 19?
 - Teu AppServer realmente está rodando em SSL mode?

**Comment by alexandroale77** [comment]
Appserver log
[alexandro_server.log](https://github.com/totvs/advpl-vscode/files/4837611/alexandro_server.log)
[appserver.txt](https://github.com/totvs/advpl-vscode/files/4837638/appserver.txt)

**Comment by AlencarGabriel** [comment]
Obrigado pelos logs.

Dei uma olhada e achei dois possíveis problemas:
 - Teu server não está configurado para ser SSL, sendo assim altere no Json do VsCode a propriedade `"SSL"`do ambiente para `false`
 - Outra coisa é que no teu appserver está dando esse erro, como se o RPO estivesse vazio, poderia confirmar se teu RPO não está corrompido acessando o Protheus via smartclient SIGAMDI/SIGADAV?
 ![image](https://user-images.githubusercontent.com/10109480/85871669-1fd8a500-b7a5-11ea-9461-241bd1ce5746.png)

**Comment by AlencarGabriel** [comment]
Mais um detalhe, teu ambiente no INI está com o nome: ALEXANDRO

Porém no VsCode você colocou ENERGY-ALEXANDRO. Tem que estar igual ao INI.

**Comment by alexandroale77** [comment]
É ENERGY-ALEXANDRO

Eu apenas eliminei o ENERGY

![Screenshot_11](https://user-images.githubusercontent.com/29817613/85872313-efddd180-b7a5-11ea-93a6-c3f464ed0783.png)

**Comment by alexandroale77** [comment]
Nem com SSL = False não vai

**Comment by killerall** [comment]
Gere o Cipher da senha denovo, pelo seu print, ele esta muito grande, que é o modelo antigo.

**Comment by alexandroale77** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85872967-db4e0900-b7a6-11ea-97a4-c7ad106a1a50.png)

**Comment by killerall** [comment]
O usuario alexandre.oliveira é administrador?

**Comment by alexandroale77** [comment]
Boa tarde, Kill

Sim é

Grato

**Comment by alexandroale77** [comment]
Acabei de aplicar o patch mais na versao anterior 17 appserver

**Comment by killerall** [comment]
Pelo que vi no seu INI anexado acima, não foi desabilitado o ssl no server, (O uso do SSL é padrão no 19) 
Ative o ssl na configuração do ambiente no vscode.

Ou desabilite:

https://tdn.totvs.com/pages/viewpage.action?pageId=538506039

e

https://tdn.totvs.com/pages/viewpage.action?pageId=538506132

Ambas para 0 ( neste caso o ssl, no ambiente do vscode fica com false.)

**Comment by alexandroale77** [comment]
Inclui no ini

![Screenshot_11](https://user-images.githubusercontent.com/29817613/85885863-6cc77600-b7bb-11ea-814b-4b84d14e04da.png)

**Comment by killerall** [comment]
Habilitou o ssl no vscode tambem?
Funcionou?

**Comment by alexandroale77** [comment]
Vou testar, 

Estou testando o Inspetor de objeto ele finaliza, mais não traz nada no RPO, mais o patch vou testar

**Comment by killerall** [comment]
Limpa o console do server, e testa novamente, anexa ele aqui( de preferencia apaga a parte em branco final do arquivo) fica muito grande o anexo. pf

**Comment by alexandroale77** [comment]
Veja encaminhando
[alexandro_server.log](https://github.com/totvs/advpl-vscode/files/4838787/alexandro_server.log)

![Screenshot_11](https://user-images.githubusercontent.com/29817613/85890071-08101980-b7c3-11ea-841c-9e734646d83c.png)

**Comment by killerall** [comment]
Cara esse imagem é do TDS

**Comment by alexandroale77** [comment]
Sim eu retornei com ele,

O que vc queria KILL?

Grato

**Comment by killerall** [comment]
Não que não estou entendendo. Esse repositório é da I Love Advpl. E não do TDS

Pelo que estou vendo, você esta tentando misturar as duas e isso não vai funcionar.

**Comment by alexandroale77** [comment]
Certo e seu deixar apenas TDS?

**Comment by killerall** [comment]
Ai você precisa falar com o pessoal de la.
Não consigo dar suporte a extensão que não fiz e não uso.

**Comment by alexandroale77** [comment]
Tá deixarei o do Rodrigo certo

Qual comando na paleta para inspetor de objeto

Grato

**Comment by killerall** [comment]
Aperta F1.
Advpl - Env - Prints out all the sources and dates of the rpo.

**Comment by alexandroale77** [comment]
Veja
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85894748-c041c000-b7cb-11ea-8859-771e9e62a40c.png)

**Comment by killerall** [comment]
Esta meio claro que não esta conectando. 

Não tenho ideia do pode estar acontecendo.

Tenta refazer o teste:
NO INI DO SERVER:

[drivers]
MultiProtocolPort=0
MultiProtocolPortSecure=0

DENTRO DO VSCODE

"ssl": false //Case é importante

Mata o log do protheus, e do advpldebugbridgec.log do temp. 

Tenta compilar um fonte simples.
Cole o console do protheus e advpldebugbridgec.log

Att.

**Comment by alexandroale77** [comment]
Iniciando a leitura do RPO. Aguarde.
Informações criadas com sucesso.
Iniciando a compilação do fonte:f:\TOTVS\GitResource\tags\Projetos - ENERGY\Contabilidade Gerencial\LP532001.PRW

Compilação iniciada em Fri Jun 26 2020 16:56:04 GMT-0300 (Horário Padrão de Brasília)

Can't connect to server:check serverVersion settings.
Compilação abortada, verifique o log ou a aba Problemas!
Compilação finalizada em Fri Jun 26 2020 16:56:05 GMT-0300 (Horário Padrão de Brasília) tempo consumido (0.717 segs.)
[AdvplDebugBridgeC_0.log](https://github.com/totvs/advpl-vscode/files/4838988/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
Anexo o log do server do protheus e o seu settings.json

**Comment by alexandroale77** [comment]
Segue, Kill!
[settings.txt](https://github.com/totvs/advpl-vscode/files/4839021/settings.txt)
[console (2).log](https://github.com/totvs/advpl-vscode/files/4839027/console.2.log)

**Comment by killerall** [comment]
O server esta dando Access Violation na hora de verificar a senha e usuário.
Tenta atualizar esse binário, ele é de abril


2020-06-26T15:33:23.786000-03:00 57028|//=====================================================
2020-06-26T15:33:23.786000-03:00 57028|Thread 57028
2020-06-26T15:33:23.786000-03:00 57028|Exception code: C0000005 ACCESS_VIOLATION

**Comment by killerall** [comment]
Se possivel tambem anexe o ini do server aqui,

**Comment by alexandroale77** [comment]
estou com esta versão
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85897811-778d0580-b7d1-11ea-9864-187e6f583620.png)

**Comment by alexandroale77** [comment]
Outra
![Screenshot_11](https://user-images.githubusercontent.com/29817613/85897922-adca8500-b7d1-11ea-9442-eb8bfb072b03.png)

**Comment by killerall** [comment]
Acabei de testar aqui com esse mesmo binario e foi normal.
O Ini do seu server, consegue anexar?

**Comment by alexandroale77** [comment]
Sim claro
[appserver.txt](https://github.com/totvs/advpl-vscode/files/4839223/appserver.txt)

**Comment by killerall** [comment]
Fiz uma copia de todas as cfg possíveis do seu server e não consigo reproduzir esse cara.
O Appserver esta na sua maquina o num servidor? Como esta com IP acredito que seja um servidor. Se sim tente subir o localmente na sua maquina o server para testar se tem algo na rede.

**Comment by alexandroale77** [comment]
Como coloquei aqui, estou trabalhando VPN o servidor fica em outro endereço, mais o acesso ao protheus eu tenho de boa.

Grato

**Comment by killerall** [comment]
Não tinha me atentado pra questão da VPN, pode ser isso que esta gerando problema.
Não tenho como testar isso agora, mais  tentaria remover a seguinte cfg do appserver e testar:

[TDS]
allowapplyPatch=*
allowEdit=*
GuestKillUser=1
ENABLEDISCONNECTUSER=*
ENABLESENDMESSAGE=*
ENABLEBLOCKNEWCONNECTION=*
ENABLESTOPSERVER=192.168.*

Removendo toda e qualquer trava do Server.
