### ISSUE TITLE
Problema ao aplicar Patch (Caminho Invalido)

### ISSUE THREAD

**Issue by RobValentim** [totvs/advpl-vscode#452]
Após realizar a atualização para a versão "191205P" não estou mais conseguindo aplicar Patch, caminho original do Arquivo

"D:\Patch\lib.ptm"

Ao tentar aplicar o Patch recebo a seguinte mensagem

Iniciando aplicação de patch...
{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't validPatch:Patch file E:\SERVIDOR\Microsiga\protheus_data\tmptdsmeu-pc\lib.ptm not found"}]}]}

porém se copiarmos o arquivo lib.ptm para essa pasta "tmptdsmeu-pc" dentro do protheus_data e informando o ptm do "D:\Patch\lib.ptm" funciona normalmente....

Existe alguma configuração para ele pegar o arquivo da pasta que estamos informando e não da pasta "tmptds*" ?

**Comment by killerall** [comment]
O Binário 19 na ultima versão alterou o comportamento de aplicação de patch.
Já fiz o ajuste, na próxima versão, já estará corrigido.

**Comment by killerall** [comment]
Corrigido na versão 0.14.4.
