### ISSUE TITLE
Erro tds-monitor.connect

### ISSUE THREAD

**Issue by vitormds22** [totvs/advpl-vscode#454]
Bom dia, 

Estou tentando acessar o monitor pelo VSCode, mas ele me mostra essa mensagem quando eu tento me conectar com o servidor:

![image](https://user-images.githubusercontent.com/33588882/88398073-34578f80-cd9b-11ea-8736-37aa509d1731.png)

Como eu posso resolver esse problema ? 

At.te

**Comment by AlencarGabriel** [comment]
Olá @vitormds22 ,

peço por gentileza que reabra sua issue no repositório do Monitor https://github.com/totvs/tds-monitor. 

Este aqui é o repositório da extensão de desenvolvimento Advpl-Vscode.
