### ISSUE TITLE
erro ao compilar um unico fontes

### ISSUE THREAD

**Issue by fabiomparra** [totvs/advpl-vscode#455]
ao tentar compilar um unico fonte pelo comando CTRL + F9 me apresenta o seguinte erro:
Iniciando a compilação do fonte:c:\TSS\my_projects\Cascavel_PR_31072020\src\NFSE\WS Client\WSGERARNFE016.PRW

Compilação iniciada em Fri Jul 31 2020 16:49:22 GMT-0300 (Horário Padrão de Brasília)

Erro no WSGERARNFE016.PRW Can't read appre return.
Compilação finalizada com erros, verifique a aba problemas!
Compilação finalizada em Fri Jul 31 2020 16:49:23 GMT-0300 (Horário Padrão de Brasília) tempo consumido (0.324 segs.)
--------------------------------------------------------------------------
porem se eu compilo a pasta toda o fonte compila normalmente
[INFO ][SERVER] [Thread 8508] Env [SPEDLG] using alternative Encoding/Decoding behavior.
WSGERARNFE016.PRW:249
ja revisei todo json .. nao encontrei nada alterado .. e estava normal até a alguns dias

alguem ja viu?
segue settins.json:
{
    "advpl.environments": [
        {
            "serverVersion": "131227A",
            "server": "localhost",
            "port": "5060",
            "smartClientPath": "c:\\totvs\\tss\\totvssped\\bin\\smartclient\\",
            "environment": "SPED17",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "VHRvSFJoQXptb3RGSjNiNXI1ejVmRnBuQkRwcHZCVjhHTXU3T0txckJPOU9aZG9aOHduMnkwdGJJZDBZcUpYYzloQkJXdFN5dnpiLzArYkVaZTIrMzBUSnBwdFowcmcxZ1NmNm9PUlRqbVl6aVNWcDdTR2RiQVMxTTlpaGE5ZkM=",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "serverVersion": "131227A",
            "server": "localhost",
            "port": "5060",
            "smartClientPath": "C:\\totvs\\tss\\TOTVS11\\totvssped\\bin\\smartclient\\",
            "environment": "SPED11",
            "includeList": "C:\\totvs\\tss\\TOTVS11\\totvssped\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "UVI4eVI3L0VoUjgvUnZNQmhzYVpuNGRUZ1Z0T3ppTjZCWjFnYXNhKzZZRGdoTFRFOGdETUFodkxVWFJldXBQQjZWb1NvNzBiNStGMExKaDhLaHk5OEZ2dHozS0VUVUs2bk5RMDlBejVXdk5SQy9ZakZXeU16NVBXYUNlbDE1WEE=",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "serverVersion": "170117A",
            "server": "127.0.0.1",
            "port": "5065",
            "smartClientPath": "C:\\totvs\\tss\\totvssped1225\\bin\\smartclient\\",
            "environment": "SPEDLG",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "1GM22D2h++3HmlsGlPt1BYEuf0HYeirr3N0vRqg4WM8B1ZEPgTgp8xgTdjNsPbPxAAC4jhv0mdhOdH+HqMXMoEhY=",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "serverVersion": "191205P",
            "server": "127.0.0.1",
            "port": "5067",
            "smartClientPath": "C:\\totvs\\tss\\TSS_27\\bin\\smartclient\\smartclient\\",
            "environment": "SPEDLG27",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "m6KcvUgBo25ChIbR282Hq1CKQWsV4OahjHVvtFSNlKJo7t1gUGqdVhlqW2Ndps3/AACbsY8/isqbc7qImoqAnUjC=",
            "language": "PORTUGUESE",
            "ssl": true,
            "rpoType": "TOP"
        },
        {
            "serverVersion": "170117A",
            "server": "10.172.22.203",
            "port": "5061",
            "smartClientPath": "C:\\totvs\\tss\\totvssped1225\\bin\\smartclient\\",
            "environment": "SPED",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "m6KcvUgBo25ChIbR282Hq1CKQWsV4OahjHVvtFSNlKJo7t1gUGqdVhlqW2Ndps3/AACbsY8/isqbc7qImoqAnUjC=",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "serverVersion": "131227A",
            "server": "localhost",
            "port": "1234",
            "smartClientPath": "C:\\TOTVS\\Protheus\\P12127\\Protheus\bin\\smartclient\\",
            "environment": "P12117",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "UVI4eVI3L0VoUjgvUnZNQmhzYVpuNGRUZ1Z0T3ppTjZCWjFnYXNhKzZZRGdoTFRFOGdETUFodkxVWFJldXBQQjZWb1NvNzBiNStGMExKaDhLaHk5OEZ2dHozS0VUVUs2bk5RMDlBejVXdk5SQy9ZakZXeU16NVBXYUNlbDE1WEE=",
            "language": "PORTUGUESE",
            "rpoType": "TOP"
        },
        {
            "serverVersion": "191205P",
            "server": "127.0.0.1",
            "port": "12125",
            "smartClientPath": "\\TOTVS\\Protheus\\smartclient181219\\",
            "environment": "P12125",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "RMjE2m/IqJ1coEaHm+P4lddDkg38YB92JUEcjx9mpTWMlVyJ/BZqoxMygdfJmdXKAACaDPwleZDQ/PtHxvXLhtLq=",
            "language": "PORTUGUESE",
            "ssl": true,
            "rpoType": "TOP"
        },
        {
            "serverVersion": "191205P",
            "server": "127.0.0.1",
            "port": "12127",
            "smartClientPath": "\\TOTVS\\Protheus\\P12127\\Protheus\\bin\\smartclient\\",
            "environment": "P12127",
            "includeList": "c:\\totvs\\includes\\",
            "startProgram": "",
            "user": "Admin",
            "passwordCipher": "P6BmG5yQ+7iC2dApDr7SansUQ3aTLjm/UekQAYOQ1DEHp1jWE6dgMQjSmBHBAPLCAAATD+hnVp7TJG0B/Na2W7TX=",
            "language": "PORTUGUESE",
            "ssl": true,
            "rpoType": "TOP"
        }

    ],
    "window.zoomLevel": 0,
    "files.encoding": "windows1252",
    "editor.fontFamily": "Consolas, 'Courier New', monospace",
    "editor.fontSize": 12,
    "advpl.authorization_generation": "20200618",
    "advpl.authorization_validation": "20200916",
    "advpl.authorization_permission": "1",
    "advpl.authorization_code": "033LHT039BLBB74A1E7671266",
    "advpl.pathPatchBuild": "C:\\TOTVS\\paths\\",
    "advpl.debug_multiThread": true,
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.debug_showTables": true,
    "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true,
    "advpl.selectedEnvironment": "SPEDLG27",
    "advpl.workspaceFolders": "c:\\TSS\\my_projects\\;",
    "workbench.iconTheme": "advplIcons",
    "workbench.colorTheme": "Monokai",
    "explorer.confirmDelete": false,
    "files.autoSave": "afterDelay",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "advpl.alpha_compile": true,
    "java.configuration.checkProjectSettingsExclusions": false
    
}

**Comment by killerall** [comment]
Esse cara só da com esse fonte?
Vi que sua pasta tem um space em branco no meio, tenta fazer os seguintes testes:
- Limpa sua temp (%TEMP%) e tenta novamente.
Se não der:
- Renomeia a pasta para sem espaço.

**Comment by fabiomparra** [comment]
limpei o TEMP do Windows deu certo .. 
só completando .. dava erro com qualquer fonte

**Comment by fabiomparra** [comment]
obrigado

**Comment by killerall** [comment]
Obrigado por avisar.
Att.
