### ISSUE TITLE
User not authenticated debug advpl

### ISSUE THREAD

**Issue by fabricioprete** [totvs/advpl-vscode#456]
Ola!
Alguem ja teve problema ao tentar debugar via vscode usando a extensão da totvs?
Estou com problema onde ocorre essa mensagem ao clicar no botão para "play" no debug ou no F5.

[Content]
User not authenticated. Please connect/reconnect to a server.
[Open launch.json] 

Eu compilo normal em qualquer ambiente, tiro inspetor de objetos, apenas debugar que ocorre isso.
![USER_not_Auth](https://user-images.githubusercontent.com/70180911/91114745-047ffe00-e65f-11ea-9e54-92ee039cb302.png)

**Comment by AlencarGabriel** [comment]
Olá @fabricioprete , 

ambas extensões são da TOTVS. Porém este repositório aqui é da extensão Advpl-VsCode, e você parece estar usando a [tds-vscode](https://github.com/totvs/tds-vscode).

Favor reabrir sua issue no outro repositório, pois lá a equipe da outra extensão irá te ajudar melhor.

**Comment by brodao** [comment]
Ola @fabricioprete 

Favor verificar o tópico (Problemas em depuração)[https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#problemas-em-depura%C3%A7%C3%A3o]. 

Caso continue com a ocorrência, favor proceder conforme (Gerando Informações sobre o Problema)[https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema].

A disposição.
