### ISSUE TITLE
Erro ao compilar fonte

### ISSUE THREAD

**Issue by rastolfi** [totvs/advpl-vscode#458]
Boa tarde!
Estou com erro ao compilar um fonte, alguém já teve esse problema.
[Error - 11:29:42] [FATAL] Aborting: BENEFARQ.PRW(495)
invalid constant STR0057
invalid constant STR0058
invalid constant STR0059
[Info - 11:29:42] Aborting end build (rollback changes).
[Error - 11:29:42] One or more files have errors and/or warnings. See problems and logs for details.
[Info - 11:29:42] Recompile finished.

**Comment by AlencarGabriel** [comment]
Boa tarde @rastolfi .

Pela estrutura do log que você passou, acredito que não esteja usando esta extensão aqui (Advpl-VsCode), e sim a versão TDS-VsCode.

Caso esteja realmente usando a outra, peço que reabra sua issue lá, para que a outra equipe possa te ajudar melhor.

https://github.com/totvs/tds-vscode

**Comment by rastolfi** [comment]
Obrigado Gabriel.

**Comment by killerall** [comment]
@rastolfi  O Que o Gabriel falou está correto. A Msg é da outra extensão
Para te ajudar, esse erro que esta dando, é porque no seu .prw tem STRXXXX (XXXX aqui é o numero) diferente do que tem no .CH

Att.
