### ISSUE TITLE
Não consigo efetuar um calculo, no VScode, com 9 casas decimais.

### ISSUE THREAD

**Issue by rafaelgama** [totvs/advpl-vscode#462]
Olá,

Hoje eu consigo criar um campo com 16,9 casas decimais, na tela, as 9 casas decimais aparece perfeitamente, mas quando eu vou pegar o valor para efetuar um calculo, o ADVPL está arredondando as casas para 8, e mesmo se eu fixar o valor em uma variável, a própria ferramenta arredonda para 8 decimais. 
Existe uma forma de utilizar 9 casas decimais?

Desde já agradeço.

**Comment by killerall** [comment]
Bom dia,
Da uma olha na documentação, que vai ficar mais facil de entender.:
https://tdn.totvs.com/pages/viewpage.action?pageId=6063071


Att.
