### ISSUE TITLE
Problema recorrente: https://github.com/totvs/advpl-vscode/issues/20

### ISSUE THREAD

**Issue by saldanha85** [totvs/advpl-vscode#465]
![debug](https://user-images.githubusercontent.com/48651289/96722799-26a6ab80-1384-11eb-9010-1ba6acd60f80.JPG)

Não retorna o valor do array no debug...

**Comment by killerall** [comment]
Boa tarde, 
Você esta utilizando a extensão do TDS. Esse repositorio é destinado a primeira extensão de Advpl feita. Entre em contato com o repositorio da extensão.
