### ISSUE TITLE
Como usar o LogProfile

### ISSUE THREAD

**Issue by ronaldaraujob** [totvs/advpl-vscode#467]
Alguém poderia me dar uma mão de como usar o LogProfile no VSCode ate coloquei o enableProfile como true mas nao sei onde vejo o quadro de dados das rotinhas para ver o tempo e o numero de chamadas.

**Comment by killerall** [comment]
Ola, esta extensão não tem suporte a leitura de LogProfiler, talvez você esteja usando a extensão do TDS.
