### ISSUE TITLE
Debug não para no breakpoint

### ISSUE THREAD

**Issue by lucaslopezvr** [totvs/advpl-vscode#468]
Muito boa tarde!

Estou com um problema onde após limpar todos os breakpoints e adicionar novos, o debug não está mais parando nos breakpoints estou usando  F5 ou indo no menu Run->Start Debugging, poderia me ajudar ? O debug é iniciado normalmente só não para nos breakpoints.

**Comment by killerall** [comment]
Boa tarde,
Que versão ta extensão você ta usando?

**Comment by andersontoledo** [comment]
Boa tarde.

Aconteceu após a atualização do VSCODE.

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic

**Comment by lucaslopezvr** [comment]
Muito boa tarde!

Aconteceu do nada, porém da mesma maneira que parou de funcionar.... voltou a funcionar, não consegui identificar o motivo.

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by killerall** [comment]
A minha duvida é quanto a versão da extensão, e não a do vscode

**Comment by lucaslopezvr** [comment]
Boa tarde!

Desculpe-me, segue abaixo.

![advpl](https://user-images.githubusercontent.com/66091301/98400498-e1040700-2042-11eb-9826-69b53b3fb7cb.png)

**Comment by killerall** [comment]
@lucaslopezvr Se você compila uma user function simples tipo
```
user function teste()
conout("teste")
return
```
e poem um breakpoint no conout, e chama debugando, não para?

**Comment by lucaslopezvr** [comment]
Muito bom dia!

Voltou a funcionar agora, só não sei dizer o que mudou, pois não atualizei nada, nem desinstalei e instalei nada novamente....
mas caso volte a acontecer interajo nesta issue novamente...

Agradeço pela ajuda e sigo a disposição caso queiram algum log etc...

**Comment by LyndaCosta** [comment]
Prezados, esse erro aconteceu comigo após atualizar para nova versão do VS Code, e reparei que o erro só acontecia quando tentava debugar utilizando o comando CRTL+F5, mas se eu fizesse através do botão existente, o debug funcionava corretamente. Não sei se será útil, mas fica ai uma opção de teste.

**Comment by LyndaCosta** [comment]
Prezados, esse erro aconteceu comigo após atualizar para nova versão do VS Code, e reparei que só acontecia quando tentava debugar utilizando o comando CTRL+F5, mas se eu fizesse através do botão existente, o debug funcionava corretamente. Não sei se será útil, mas fica ai uma opção de teste.

**Comment by robsonrosilva** [comment]
Boa tarde, @LyndaCosta no VSCODE CTRL+F5 é para executar SEM DEBUG. Execução com debug tem que ser só F5.

**Comment by LyndaCosta** [comment]
Boa tarde, @robsonrosilva. Obrigada pela correção, mas mesmo utilizando apenas o F5 não funcionou.
