### ISSUE TITLE
Erro ao conectar no server com Vscode

### ISSUE THREAD

**Issue by alexandroale77** [totvs/advpl-vscode#473]
Bom dia,

Estou enfrentando a seguinte situação.

Estou fazendo a configuraçao no Vscode do novo servidor e ao fazer isso a seguinte mensagem me aparece

"An error ocurred while connection.\n\Server:IP:1.206"

Verifiquei e o mesmo esta colocando "." ou "," no numero da porta.
Notei também que na versão 7.00.191205P eu consegui conectar, mais na versao que me apresenta no server.json 7.00.170117A esta acontecendo isso.

Como posso corrigir isso?
![MENSAGEM](https://user-images.githubusercontent.com/29817613/99955244-bd3f0180-2d62-11eb-9034-4ed0cd941635.png)

**Comment by killerall** [comment]
Bom dia,
Você está utilizando qual extensão? Pela mensagem de erro parece que não é está.

**Comment by alexandroale77** [comment]
Killerall, 

Bom dia ,veja o que eu fiz.
1 - RPO estava com read-ony ticado, tirei o tick
2 -  O mesmo para pasta
E ai consegui conectar.
3 - Para aplicar o patch aonde tb estava com dificuldade no ini do appserver deixei dessa forma.
[TDS]
AllowApplyPatch=*
AllowEdit=*

E funcionou...

Vlw pela ajuda.
