### ISSUE TITLE
Please, select an environment!

### ISSUE THREAD

**Issue by vherrmannqgsa** [totvs/advpl-vscode#474]
Estou tentando compilar um fonte pelo vsCode e agora está aparecendo a mensagem: Please, select an environment!
Porém já estou conectada em um servidor/ambiente.
Até ontem, essa mensagem não aparecia. Hoje, de uma hora para outra, para compilar, começou a aparecer essa mensagem. Alguém sabe o que pode ser isso?

**Comment by killerall** [comment]
Boa noite,
Qual a versão da extensão que você esta utilizando?

**Comment by eduardovicente-silva** [comment]
Estou utilizando a v0.14.7 e essa mensagem ocorre quando não tenho a propriedade "advpl.selectedEnvironment": "JUSPODIVM_DEV" na minha workspace. Porém declarando essa propriedade o fonte é compilado apenas nesse Ambiente mesmo alterando o ambiente na opção Enviroment do VSCode.

**Comment by AlencarGabriel** [comment]
> Estou utilizando a v0.14.7 e essa mensagem ocorre quando não tenho a propriedade "advpl.selectedEnvironment": "JUSPODIVM_DEV" na minha workspace. Porém declarando essa propriedade o fonte é compilado apenas nesse Ambiente mesmo alterando o ambiente na opção Enviroment do VSCode.

@eduardovicente-silva , verifique se suas configurações de ambientes não estão nas configurações da Workspace. 

Por padrão o VsCode busca as configurações da workspace e depois as de usuário. Por isso quando vc usa a opção de alterar ambiente no VsCode, ele automaticamente joga as configurações para a Workspace e ignora as de usuário.
