### ISSUE TITLE
Como compilar arquivo html no vscode

### ISSUE THREAD

**Issue by Crisrud** [totvs/advpl-vscode#475]
Ao tentar compilar, acusa a mensagem:
is not in the allowed extensions list.

**Comment by marciokatsumata** [comment]
Crirud,

É só ir no menu File ->Preferences->Settings->Extensions->TOTVS -> Totvs Language Server ->Folder: Extesions Allowed

E depois edite o JSON adicionando a extensão.

![image](https://user-images.githubusercontent.com/66393204/103409430-891ae580-4b45-11eb-8905-e381d2efef78.png)

![image](https://user-images.githubusercontent.com/66393204/103409434-8cae6c80-4b45-11eb-8b01-ae699cec59ec.png)

Espero ter ajudado.

Abraços!

**Comment by Crisrud** [comment]
Excelente!
Muito Obrigado.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Marcio Shigueru Katsumata<mailto:notifications@github.com>
Enviado:quinta-feira, 31 de dezembro de 2020 08:53
Para: totvs/advpl-vscode<mailto:advpl-vscode@noreply.github.com>
Cc:Crisrud<mailto:cristiano.scarlat@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Como compilar arquivo html no vscode (#475)


Crirud,

É só ir no menu File ->Preferences->Settings->Extensions->TOTVS -> Totvs Language Server ->Folder: Extesions Allowed

E depois edite o JSON adicionando a extensão.

[image]<https://user-images.githubusercontent.com/66393204/103409430-891ae580-4b45-11eb-8905-e381d2efef78.png>

[image]<https://user-images.githubusercontent.com/66393204/103409434-8cae6c80-4b45-11eb-8b01-ae699cec59ec.png>

Espero ter ajudado.

Abraços!
