### ISSUE TITLE
Suporte novo Binario

### ISSUE THREAD

**Issue by keinou** [totvs/advpl-vscode#476]
Bom dia,
Gostaria de ver se tem previsão para contemplar suporte ao novo binario? (13.2.3.51)

**Comment by killerall** [comment]
Bom dia, desconheço essa versão que você colocou, consegue copiar as primeiras linhas do console.log quando o appserver inicia?
Essas infos:
 * TOTVS - Build 7.00.191205P - Jan 31 2020 - 21:01:04 
 * Build: 64 bits
 * SVN Revision: 25958
* Build Version: 19.3.0.1_RC12

**Comment by keinou** [comment]
Pode finalizar a Issue, não reparei na versão, obrigado.

Build 7.00.131227A - Nov  6 2020 - 21:57:40 NG
