### ISSUE TITLE
Recompilar editores aberto 

### ISSUE THREAD

**Issue by Brunomaia877** [totvs/advpl-vscode#477]
Frequentemente quando vamos compilar vários fontes usando o (ctrl+F10) ele pula alguns fontes e precisamos recompilar varias vezes até que realmente todos sejam compilados,

**Comment by robsonrosilva** [comment]
@Brunomaia877 pela documentação o atalho não seria ctrl+f10 e sim ALT + F9.

[Documentção de Atalhos](https://github.com/totvs/advpl-vscode#teclas-de-atalho-padr%C3%B5es)

**Comment by Brunomaia877** [comment]
CRTL + SHIFT +F10 compila todos os fontes abertos, escrevi o atalho errado 
![image](https://user-images.githubusercontent.com/40870526/101205800-edcd4800-364c-11eb-972e-755df5bec8d0.png)

**Comment by robsonrosilva** [comment]
Se usar o ALT + F9  tbm não funciona?

**Comment by killerall** [comment]
@Brunomaia877 Pela a imagem que mandou, você esta usando a extensão do TDS e não essa daqui.
