### ISSUE TITLE
.prw not found

### ISSUE THREAD

**Issue by rflfnds** [totvs/advpl-vscode#478]
Para alguns projetos ao compilar o vscode está retornando a mensagem:

[Error - 7:38:38 PM] File /Users/rafaelfernandes/Documents/Totvs/VS Code/producao/05 - Faturamento/A - Atualizações/COT05A01.prw not found.

Notei que removendo os espaços dos diretórios ele compila. Mas gostaria de configurar de modo que aceitasse os caracteres

![Screen Shot 2020-12-07 at 7 27 55 PM](https://user-images.githubusercontent.com/37883768/101414388-c08acf00-38c4-11eb-87e6-7441172e2ab2.png)

**Comment by AlencarGabriel** [comment]
Olá @rflfnds ,

percebi que não está usando esta extensão aqui, e sim a [versão TDS](https://github.com/totvs/tds-vscode).

Favor direcionar sua issue para o outro repositório, para que a equipe do TDS possa te auxiliar.
