### ISSUE TITLE
O fonte Client WS gerado está vazio

### ISSUE THREAD

**Issue by Drovisk2020** [totvs/advpl-vscode#479]
Ola, 
o fonte client ws que gero no vscode está vazio, o que estou fazendo de errado para isso acontecer?
obrigado

**Comment by Drovisk2020** [comment]
Parece que a url que estou usando está errada:

[Error - 13:43:00] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : http://XX.XXX.XX.XXX:1200/Protheus_data/web/ws
-------------------------------------------------------------------------------
WSCERR017 / [HTTP] Requisi��o retornou NIL. ( 10060 : Connection timed out. )
ADVPL WSDL Client 1.120703 / TOTVS Sa�de Tmtst_dev3 on 20201208 13:46:21
-------------------------------------------------------------------------------

**Comment by killerall** [comment]
Pelo erro no server, não esta conseguindo nem fechar a conexão entro appserver e o vscode.

**Comment by Drovisk2020** [comment]
Verdade ! 
Estou conectado no ambiente de Teste e o endereço que estou colocando na "URL Web Service/WSDL FIle" do Generate WS é o mesmo endereço que esta na "URL Location" do WS...... http://XX.XXX.XX.XXX:84/ws/WSINDEX.apw  
Não é assim que se faz ?

**Comment by killerall** [comment]
o cliente você deve gerar de um serviço, a url completa vai ser maior do que essa que passou e tem um ?WSDL no fim, se não estou enganado.

**Comment by Drovisk2020** [comment]
Matou @killerall  !!
Cliquei em cima do WS que precisava atualizar na pagina principal( http://XX.XXX.XX.XXX:84/ws) que abriu a pagina do método do serviço e no cabeçalho dessa pagina cliquei no link da "Descrição do serviço" que abriu outra pagina e no link 
continha no final WSDL como você mencionou : http://XX.XXX.XX.XXX:84/ws/XYZ02.apw?WSDL
Copiei esse link e colei no campo "URL Web Service/WSDL FIle" do Generate WS no VSCode  e gerou o fonte !!
Vlw mesmo pela dica!!
Brigadão

**Comment by leandromarcelino** [comment]
Olá Rodrigo! 
Na verdade esta é fictícia. Mas entendi, porém a Totvs tá quebrando a cabeça. Disseram que eu tenho que reescrever meus fontes com classes mais atuais... blablabla. Dizendo que o VsCode não suporta as que estou usando. Piada né? Este fontes foram feitos no VSCode e já utilizo faz 3 anos.

**Comment by killerall** [comment]
Se você consegue da sua maquina Local , bater no WSDL via browse, um appserver na sua maquina local vai conseguir bater tambem.
Agora se você estiver usando o servidor que esta no Cloud, ele pode não ter acesso a essa URL, dessa maneira.
Por isso recomendo fazer com appserver local.

**Comment by leandromarcelino** [comment]
Esse caminho acima é do appserver do TCloud
