### ISSUE TITLE
Geração de pacote de atualização (patch) a partir do RPO (From RPO)

### ISSUE THREAD

**Issue by jerfweb** [totvs/advpl-vscode#484]
Prezados,

Existe essa opção disponível na extensão? Caso não, tem alguma pretensão ou previsão de disponibilização?

**Comment by AlencarGabriel** [comment]
Olá @jerfweb , 

acredito que esta WIKI atenda a sua necessidade.

https://github.com/totvs/advpl-vscode/wiki/Trabalhando-com-Patchs

**Comment by killerall** [comment]
Boa tarde, você quer gerar via diferença de rpo?
Ter um base e gerar a diferença do que tem de um para outro?

**Comment by jerfweb** [comment]
@killerall, boa tarde!

A necessidade é gerar um PATCH de um fonte que está no RPO, essa função existia no finado TDS, onde ele lia os dados do RPO e possibilitava a geração de patchs dos fontes selecionados. A extensão da TOTVS tem essa funcionalidade, segue link abaixo:

https://github.com/totvs/tds-vscode/blob/master/docs/build-patch.md

**Comment by killerall** [comment]
De fontes selecionados você pode gerar.
Basta criar u, .txt com os nomes dos fontes que deseja 1 por linha ( se quiser uma lista do que tem no rpo, tambem tem comando pra isso).
assim:
fonte1.prw
fonte2.prw

**Comment by jerfweb** [comment]
No caso necessito gerar um patch do fonte padrão GPEM015.PRX que está no RPO, do modo que você está detalhando, basta criar um fonte como o mesmo em uma pasta e a extensão gera o PTM do arquivo que está no RPO?

**Comment by killerall** [comment]
Criar um .txt, não um fonte.Com apenas o nome dos fontes que você quer (no seu caso so o GPEM015.PRX)
O Link que o Gabriel passou tem o passo a passo.

Att.
