### ISSUE TITLE
Erro no vscode: Authentication error: Server returned a non numeric value.

### ISSUE THREAD

**Issue by to811649** [totvs/advpl-vscode#485]
O Erro é apresentado no vscode>>  Authentication error: Server returned a non numeric value, na tentativa de conexão ao server/RPO (RPO DO WORKFLOW DE COMPRAS), para compilação de alteração realizada em um ponto de entrada.

**Comment by killerall** [comment]
Boa tarde, Acredito que não esteja utilizando essa extensão e sim a TDS . Acredito que seja melhor entrar em contato com eles, por la.
