### ISSUE TITLE
VSCODE não conecta

### ISSUE THREAD

**Issue by frangrupi** [totvs/advpl-vscode#488]
Após atualização geral do protheus não não consigo me conectar ao ambiente aparece a mensagem "An error ocurred while connection.\n\rServer: 192.168.0.105:1.236 [Conexoes]", pelo smartcliente conecta normalmente. Envio o console para analise.
[console.log](https://github.com/totvs/advpl-vscode/files/6002712/console.log)

**Comment by AlencarGabriel** [comment]
Olá @frangrupi , 

Poderia enviar aqui o teu settings dos ambientes?

**Comment by frangrupi** [comment]
Bom dia, 

eu deletei o server e adicionei novamente e deu certo.

Obrigada.

**Comment by PedreirasBahia** [comment]
Olá Alencar,

Estou passando pelo mesmo problema mas nem recriando o ambiente resolve

Omeu ambiente 12.1.25 (REST), funciona tranquilo mas no 12.1.33 (APPTESTE12133) não carrega.

Poderia nos ajudar?

{
	"version": "0.2.0",
	"includes": [
		"D:\\TOTVS 12\\ADVPL\\include"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": [
		{
			"id": "j8xibruqmgrkuscqlb5lr25ggp8wsg",
			"type": "totvs_server_protheus",
			"name": "REST",
			"port": 1240,
			"address": "192.168.0.200",
			"buildVersion": "7.00.191205P",
			"secure": false,
			"includes": [
				"D:\\TOTVS 12\\ADVPL"
			],
			"environments": [
				"REST"
			],
			"environment": "REST",
			"token": "djM6ajh4aWJydXFtZ3JrdXNjcWxiNWxyMjVnZ3A4d3NnOjE6MTkyLjE2OC4wLjIwMDoxMjQwOjA6Ny4wMC4xOTEyMDVQOjM=:djE6UkVTVDpub3VzZXI6cTVVMGdwYXVKYzBEQ0JuSTBZVExBZnhqejJFaWN3ak9IcnNMQ2tua1FMTT0=|djI6MTYzNjA0NjQ2OToyOjE6MA==.T2GOKI5uQS9oABvLb4i/Tpbh1oRz7uqj4kDqB1pxCsnoZDs/Cmpy/fO6Z+3eFllVTBKOE1mn3jIaPmHpktSXSz5M3mnh6crG57luYs+FZw3A+UCSfbL+xxsWWboZ5D+jyk8LpczPiLlG4+Wox3LRDSxsBpdnFNWFdYAkbA/jI2zSYVj7a6FVzRVnQbwuufgTSHC/1ltQtEIEci0tNmmCzaLIN/TA5n4SKKaQIyn82oGeESUT3X/Owq6DNGhHwEieBwKC3sxdwHCbVnvTpzN4fW5k6Jk6+xkeTfJqOuypQVmpSUEoLPEAkW2upRm59jFoUVGEt5PbefITDKhqAYI/7A=="
		},
		{
			"id": "wt1hymt6twkvh73li1uoes4yzvsmi",
			"type": "totvs_server_protheus",
			"name": "APPTESTE12133",
			"port": 1201,
			"address": "192.168.0.200",
			"buildVersion": "7.00.210324P",
			"secure": 1,
			"includes": [
				"D:\\TOTVS 12\\Microsiga\\Protheus\\include"
			]
		}
	],
	"savedTokens": [
		[
			"u2dkr5uufbhke3200kp69tvnw0pbky:TESTE",
			{
				"id": "u2dkr5uufbhke3200kp69tvnw0pbky",
				"token": "djM6dTJka3I1dXVmYmhrZTMyMDBrcDY5dHZudzBwYmt5OjE6MTkyLjE2OC4wLjIwMDoxMjAxOjE6Ny4wMC4xOTEyMDVQOjM=:djE6VEVTVEU6YWRtaW46cGlFME9Td0RIdi9MZmNSbXAzQ1hWQ2Vnbkh4WmdYQWhXejd6Y0o2UGJIdz0=|djI6MTYzMjczOTg3NTowOjE6MQ==.o11ikJ9HAeM1TjAVzvnLhjwdkc/NEENILWXObJ/9sbBK06cwSiJI36tfgSF0Rtc1MZpGbkj9Z8zQiFEV0ZNM4zcIalet8cyiE7/rYZLcpHqcbj8P6NRNmle6jliJcOITnBWiyTGVTZvKoa3EW0H0gL9dC4v4Ca4MYEFFdTua0HVEsc62sVJvzm3emFC/dv8+hI3ZzBon9VOPmWwcYHmUFsgiPQbYOhTXK/Jkoc15N0SdMRneHqJGI6BHAiYGrcGIEFVJY98X2bOvjoJZBpgxC5k3klRHCDzYa768MrKh4NihuMiY1rda7yYC1Ilh9DLeyd2lbSzcEXpi+1bNh6Ee2Q=="
			}
		],
		[
			"ugnwa7ulpl9keoy84b4k0avgn8p65k:REST",
			{
				"id": "ugnwa7ulpl9keoy84b4k0avgn8p65k",
				"token": "djM6dWdud2E3dWxwbDlrZW95ODRiNGswYXZnbjhwNjVrOjE6MTkyLjE2OC4wLjIwMDoxMjQwOjE6Ny4wMC4xOTEyMDVQOjM=:djE6UkVTVDpBRE1JTjpibHNvQXBXanl0YnE5L3BjQWYzeEJ0c0tDOThWNGVBQkIrRG9OaU5MTk9RPQ==|djI6MTU5OTI2NjkzOTowOjE6MQ==.V4jaDu4K7sUkrt8NSwsQwS9Eaz7qxvctOVNbseKimq1aGtfHavBQZi4r2vJpNuObpOVtbfITB93jVLopLr509g60dQeusEd6h90T3KNE2Boe4xCzNuvP++4uV2KXXIzztMDNdlFqIN+R5rhunm1pIOXs1gI1C3eLXSwElEgqvr5+uP6TgupSBmD+QMTHFL/1NRgmU6vtSqcgHe8jz49S5+TGxINCMF+MeZgG5PVSm8ClU1vYEjDlgVNAIF9AzHNIrkQ7G3rAHSkIT2oq22N7hVsMFZ7+O/Ue7cXjgoqoAhSzDLqSLJG1yYXqwM3ILkIVNcDx1FYZuvkYvXiyfHcTFw=="
			}
		],
		[
			"p115durz62rkuscgce8gcs5dxiectf:TESTE",
			{
				"id": "p115durz62rkuscgce8gcs5dxiectf",
				"token": "djM6cDExNWR1cno2MnJrdXNjZ2NlOGdjczVkeGllY3RmOjE6MTkyLjE2OC4wLjIwMDoxMjAxOjA6Ny4wMC4xOTEyMDVQOjM=:djE6VEVTVEU6YWRtaW46Q3RQSDE5YTBnVjZNRDFENjJQaWFlZG5ObG42cW1pdHZ3SUVMSlE0Q3hDST0=|djI6MTYzNDMwMTQ0ODowOjE6MQ==.o8DmWzBpzLLsl+AYteYP0/QWxY4BHsWvqAJvCoDXuxuDp/gqBjkDiFv0ek+1/iyRgihP2DU8SxgU5M7ORIlfRzPk72P+IqWhOqsx7LEa1FNyHTjgkEUFqZQei4BM2KfeKBXqQFOrxFvHmqDMDCXK96FTkiGNqzHM7fsiF4dliRKnIAxh93LfF9u+OBI2x7eN1V6Hzu3kOhSLJhpEt+fUYsEWkCLNiXi2SBwd98eCzLZiGiSfrmjDy/dRE7jUULVTj/e6dm9PjeCE58h4RtVVK8A3cBVHN25ImkRWxn813QF2lvA8juylKJD8cBJCD2qtkc+d05bDTZaYXOVYxlZcCg=="
			}
		],
		[
			"j8xibruqmgrkuscqlb5lr25ggp8wsg:REST",
			{
				"id": "j8xibruqmgrkuscqlb5lr25ggp8wsg",
				"token": "djM6ajh4aWJydXFtZ3JrdXNjcWxiNWxyMjVnZ3A4d3NnOjE6MTkyLjE2OC4wLjIwMDoxMjQwOjA6Ny4wMC4xOTEyMDVQOjM=:djE6UkVTVDpub3VzZXI6cTVVMGdwYXVKYzBEQ0JuSTBZVExBZnhqejJFaWN3ak9IcnNMQ2tua1FMTT0=|djI6MTYzNjA0NjQ2OToyOjE6MA==.T2GOKI5uQS9oABvLb4i/Tpbh1oRz7uqj4kDqB1pxCsnoZDs/Cmpy/fO6Z+3eFllVTBKOE1mn3jIaPmHpktSXSz5M3mnh6crG57luYs+FZw3A+UCSfbL+xxsWWboZ5D+jyk8LpczPiLlG4+Wox3LRDSxsBpdnFNWFdYAkbA/jI2zSYVj7a6FVzRVnQbwuufgTSHC/1ltQtEIEci0tNmmCzaLIN/TA5n4SKKaQIyn82oGeESUT3X/Owq6DNGhHwEieBwKC3sxdwHCbVnvTpzN4fW5k6Jk6+xkeTfJqOuypQVmpSUEoLPEAkW2upRm59jFoUVGEt5PbefITDKhqAYI/7A=="
			}
		]
	],
	"lastConnectedServer": ""
}

**Comment by AlencarGabriel** [comment]
Olá @PedreirasBahia ,

pelo que vejo no JSON que você colocou aqui, você não está usando essa extensão aqui, e sim a [TDS-VSCode](https://github.com/totvs/tds-vscode/). 

Teria que abrir uma issue nesse outro repositório e se possível detalhar melhor o problema para eles conseguirem te ajudar.
