### ISSUE TITLE
Exportação de problemas na compilação por diretório

### ISSUE THREAD

**Issue by thiagomeschiatti** [totvs/advpl-vscode#489]
Bom dia. 

Há alguma maneira de exportar ou gerar em arquivo os resultados de compilação contidos na aba **PROBLEMS** do vs code?

Obrigado.

**Comment by AlencarGabriel** [comment]
Olá @thiagomeschiatti ,

a aba problems é controlada por uma API padrão do VsCode que hoje não possui nenhuma forma visual pra exportar essas informações. Teria que ser implementado essa feature por extensão.

Porém se você usa esta extensão (I Love AdvPL), sempre que uma compilação é feita, os resultados de warning/error são mostrados na aba output > Advpl, e lá é possível copiar as informações.
