### ISSUE TITLE
Compiler Auth ID

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#490]
Boa tarde, 

acabei de instalar em um hd novo e o comando para coletar o Volume não consegue pegar o VolumeId do drive c e retorna em branco, poderia me orientar em como é coletado o valor pra que eu possa tentar descobrir o motivo do Code não ter acesso ao valor?

**Comment by killerall** [comment]
Boa tarde, 
Va na sua pasta:
Sem alpha:
```
C:\Users\SEU_USUARIO\.vscode\extensions\killerall.advpl-vscode-0.14.8\bin
e rode:
AdvplDebugBridge.exe --getId
```
Com alpha:
```

C:\Users\SEU_USUARIO\.vscode\extensions\killerall.advpl-vscode-0.14.8\bin
AdvplDebugBridgeC.exe --getId
```

E veja qual o resultado apresentando. Quando retornar em branco, normalmente tem algo de errado com o DotNet da sua maquina se for a versao sem ser o alpha. Mais diga oque esta usando e o resultado do comando acima.

**Comment by viniciusgati** [comment]
Valeu mano deu certo
