### ISSUE TITLE
Erro Debug

### ISSUE THREAD

**Issue by fabiopedroza** [totvs/advpl-vscode#491]
Hoje o meu vscode começou a dar erro. Percebi quando fui debugar

1a coisa é que sumiu os itens do debug e depois começou dar o erro de memória (seguem os anexos)

![erro_vscode](https://user-images.githubusercontent.com/59176849/110960290-59e6d880-832d-11eb-9cf9-6d5c797b301b.PNG)
![VSCODE_DEBUG](https://user-images.githubusercontent.com/59176849/110960297-5b180580-832d-11eb-9e6d-3ec1a7107075.PNG)

**Comment by AlencarGabriel** [comment]
Olá @fabiopedroza, pelo que vi vc não está usando esta extensão aqui, e sim a [versão TDS](https://github.com/totvs/tds-vscode).

Favor reabrir sua issue lá, para que a equipe da TDS possa verificar se é problema na extensão ou no seu ambiente.

→ Sobre os ícones de navegação do Debug, eles só ficam disponíveis quando o VsCode está parado em um breakpoint.

**Comment by fabiopedroza** [comment]
Na computador que estou nunca teve TDS! Inclusive tentei atualizar  o VsCode com o VSCodeUserSetup-x64-1.54.2.
Então como faço para desinstalar o VS e instalar do zero.
Pois tenho demanda para entregar e estou parado.
![image](https://user-images.githubusercontent.com/59176849/110968731-a551b480-8336-11eb-99a9-5a36cf9f4dee.png)

**Comment by AlencarGabriel** [comment]
Olá @fabiopedroza , acredito que não tenha acessado o Link que eu coloquei na ultima mensagem.

Existem duas extensões do VsCode que dão suporte a AdvPL:

A I Love AdvPL:
![image](https://user-images.githubusercontent.com/10109480/110976055-33319d80-833f-11eb-9ff3-aa35319ec93d.png)

e a TDS for VsCode:
![image](https://user-images.githubusercontent.com/10109480/110976077-39c01500-833f-11eb-896f-e6e61671d146.png)

Este repositório aqui é referente a extensão **I Love AdvPL**, e você está usando a **TDS for VsCode**.

Por isso pedi para reportar seu problema no outro projeto: https://github.com/totvs/tds-vscode

Espero ter esclarecido.

**Comment by fabiopedroza** [comment]
Agora entendi.. me desculpe
