### ISSUE TITLE
Erro ao Salvar Icones

### ISSUE THREAD

**Issue by danielmontagna** [totvs/advpl-vscode#496]
Quando defino os icones ele fica no vscode mas ao reiniciar ele volta para os anteriores 

Não é possível gravar nas configurações do usuário. Abra as configurações do usuário para corrigir erros/avisos e tente novamente.

Mensagem que dá ao aplicar

**Comment by AlencarGabriel** [comment]
Isso é um erro padrão do VsCode.

Bem provável que o JSON das suas configurações de usuário está "quebrado". Na aba de problemas é possível identificar o que está errado. 

Depois que você acertar o problema no settings json, vai ser possível definir as configurações.
