### ISSUE TITLE
Patch - Aplicar somente os atualizados

### ISSUE THREAD

**Issue by paulocwb** [totvs/advpl-vscode#500]
Na versão .33 ele primeiro valida os patchs e dai gera um erro pedindo para selecionar apenas os mais novos ou todos.
Existe como deixar somente os novos por padrão? para que não fique pedindo isso sempre?
Igual havia nas versões anteriores

**Comment by paulocwb** [comment]
é necessario validar, marcar patch por patch que deseja apenas fontes atualizados, validar novamente para só depois aplicar...
Demora demais pra aplicar patchs
![image](https://user-images.githubusercontent.com/69217964/122644782-5792d800-d0ed-11eb-8f67-4a964327ed76.png)

**Comment by AlencarGabriel** [comment]
@paulocwb Você está usando a extensão tds-vscode. E este repositório é da advpl-vscode. 

Peço por gentileza reabrir essa issue no repositório da tds-vscode pra equipe de lá avaliar seu problema.
