### ISSUE TITLE
Cipher password em branco no MacOS

### ISSUE THREAD

**Issue by crevilari** [totvs/advpl-vscode#508]
Olá!

Ao tentar gerar o password no MacOS, está retornando em branco. O openssl 1.1 está instalado.

O openssl está na pasta padrão /opt/homebrew/Cellar/openssl@1.1/1.1.1k/lib, fiz uma cópia para o caminho em que está fazendo a busca e também não funcionou.

<img width="1740" alt="image" src="https://user-images.githubusercontent.com/31827503/127725589-47539921-5fe4-4f8b-9705-a1714e3c3559.png">

Obrigado.

**Comment by killerall** [comment]
O problema é a versão do seu openssl
Esse cara so roda x86, vc ta usando que versao de MacOS?

**Comment by killerall** [comment]
Estou na fila para testar um opção que o pessoal liberou, em breve teremos novidades.

**Comment by fhfavaretto** [comment]
@killerall, alguma progresso nessa melhoria ?

**Comment by killerall** [comment]
Ja testei, precisou de ajustes, assim que estiver ok eu implemento aqui tambem

**Comment by fhfavaretto** [comment]
@killerall 
Boa noite, tem previsão de liberação dessa grande melhoria aos usuarios de macOS ?

**Comment by crevilari** [comment]
@fhfavaretto o plugin oficial da Totvs está funcionando normal no MacOS. Pode ser uma alternativa.

**Comment by killerall** [comment]
> @killerall Boa noite, tem previsão de liberação dessa grande melhoria aos usuarios de macOS ?

Bom dia, estou trabalhando nisso agora, acredito que mais alguns dias eu consigo liberar.

**Comment by killerall** [comment]
Pessoal liberei agora a v0.15.1, que volta a ter suporte ao Mac OS
