### ISSUE TITLE
Cipher em Branco - VsCode 1.59.0

### ISSUE THREAD

**Issue by snlacerda89** [totvs/advpl-vscode#510]
versao 0.14.10 nao gera Cipher no Vscode 1.59.0

**Comment by snlacerda89** [comment]
Nao gera quando ativa o alpha.compile

**Comment by killerall** [comment]
Boa tarde,
Va na pasta temp:
 %TEMP% e  apague o arquivo: state_c.bin

Depois, va na sua pasta do vscode, algo como :
C:\Users\SEU_USUARIO\.vscode\extensions\killerall.advpl-vscode-0.14.10/bin/alpha/win

e rode e veja se gera o ID da chave de compilação:
AdvplDebugBridgeC.exe --getId

**Comment by viniciusgati** [comment]
![image](https://user-images.githubusercontent.com/60268/190724373-81d49035-38f1-4146-8695-27b3d5267e58.png)

nada aqui

**Comment by viniciusgati** [comment]
Faltava instalar o compilador c++ , resolveu https://www.microsoft.com/en-gb/download/details.aspx?id=48145
