### ISSUE TITLE
Compilar arquivo .app

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#511]
Fala Godinho bom dia beleza? 

não estou conseguindo não sei se existe suporte a compilar arquivos .app, só consegui pelo da totvs mesmo... sabe se vamos ter suporte ou jeito de compilar esses resources?

att.

**Comment by AlencarGabriel** [comment]
Opa @viniciusgati ,

para compilar resources, por hora você precisar fazer via compilação de pasta (clicando com direito na pasta onde há o resource desejado):

![image](https://user-images.githubusercontent.com/10109480/130063770-567a6100-6608-4e45-b034-bbfa5bac9f85.png)

**Comment by viniciusgati** [comment]
Show de bola obrigado
