### ISSUE TITLE
Erro Linter na primeira linha

### ISSUE THREAD

**Issue by BrunoSingelo** [totvs/advpl-vscode#512]
Ao abrir um fonte,  acusa o seguinte erro na primeira linha do código:

Systax Error Linter

Já realizamos a configuração dos includes para ter certeza que não havia nenhum problema, porém o erro persiste, também foi feito a reinstalação da extensão, sem sucesso também.

![erroLinter](https://user-images.githubusercontent.com/71949549/132698466-82b9cdef-e223-4439-996b-2d3a4cb89f81.PNG)
É necessário realizar alguma configuração adicional para que não apresente mais esse erro?

Desde já, agradeço a atenção.

**Comment by AlencarGabriel** [comment]
Olá @BrunoSingelo ,

poderia verificar por gentileza se realmente está usando essa extensão aqui, ou se está utilizando a [tds-vscode](https://github.com/totvs/tds-vscode)? 

Pergunto isso porque essa extensão aqui não implementa nenhum linter na linguagem, ou talvez você utilize outra que faça isso.
