### ISSUE TITLE
compilacao de relatorio customizado

### ISSUE THREAD

**Issue by Veronicadourado** [totvs/advpl-vscode#513]
estou compilando um relatoro customizado devido a uma atualizacao do protheus e deram alguns erros na compilação.
W0003 Local variable CSTRING never used
W0003 Local variable WNREL never used
W0004 For variable is not Local. This warning may be an error in future version.
W0004 For variable is not Local. This warning may be an error in future version.

**Comment by AlencarGabriel** [comment]
Olá @Veronicadourado ,

pelo que vejo na verdade há avisos (warnings) não erros. 

Sendo assim se apenas foi exibido essas mensagens na compilação, seu relatório está compilado.

**Comment by Veronicadourado** [comment]
obrigada

**Comment by Veronicadourado** [comment]
Boa tarde 
nao estou conseguindo conectar o servidor de produção.
preciso desconectar o teste que esta conectado?

**Comment by Veronicadourado** [comment]
ja consegui
para compilar um relatorio customizado no ambiente de produção me mandaram promover o rpo produçao para teste e compilar o relatorio no amnbiente teste configurado no vscode onde eu ja tinha compilado e funcionado. compilei . derpois promovi o inverso mas nao funcionou a função
