### ISSUE TITLE
Compilar função padrão no harpia

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#519]
Ola pessoal, vai ter suporte a compilar função padrão no harpia? por enquanto recebo mensagem falando que só função de usuário é permitida.

**Comment by killerall** [comment]
Boa tarde,

Esta compilando normal, para compilar função do padrão no harpia você precisa do Token de compilação.
A chave muda.
https://github.com/totvs/advpl-vscode/wiki/Chave-de-compila%C3%A7%C3%A3o

**Comment by viniciusgati** [comment]
obrigado
