### ISSUE TITLE
Debug ou Run parou de funcionar - MacOS 12.1

### ISSUE THREAD

**Issue by alexandreeffting** [totvs/advpl-vscode#522]
Olá Boa noite,

O debug e o Run via VSCODE não está mais funcionando. Após iniciar o Debug ele solicita o Programa a ser executado (SIGAMDI, por exemplo, a barra de progresso roda e finaliza sem nenhum tipo de mensagem, log ou coisa do gênero na interface do VS-CODE.

A compilação está ocorrendo normalmente.

Smartclient Instalado: 21-10-15-P12-SMARTCLIENT_BUILD-19.3.1.7_MAC_X64.DMG

Dados do VSCODE Instalado
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0 (MacOs Monterey - Apple M1)

Dados-- Lauch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/Applications/smartclient.app/Contents/MacOS/smartclient",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		}
	],
	"lastProgramExecuted": "sigamdi"

**Comment by AlencarGabriel** [comment]
Olá @alexandreeffting , pelo que pude observar nas suas configurações, parece que você não está utilizando essa extensão aqui e sim a [tds-vscode](https://github.com/totvs/tds-vscode).

Favor reabrir sua issue no outro repositório para que a outra equipe possa te ajudar a resolver seu problema.
