### ISSUE TITLE
Atualizacao de Lib

### ISSUE THREAD

**Issue by bviniciusilva** [totvs/advpl-vscode#528]
Bom dia!

Estou tentando atualizar uma LIB em um cliente, porém o VsCode sempre aborta o processo, até pensei que poderia ser por diferença de versão de binário( cliente está no harpia), mas baixei uma lib do lobo, e quando tento a mesma ele já barra na hora e fala explicitamente que é diferença de versão, no caso da correta simplesmente aborta, até o básico que poderia ser a falta do acesso exclusivo também, mas assim que dá o erro eu compilo um fonte e vai normal.

Info  - 09:04:58] User 'admin' authentication finished.
[Info  - 09:05:11] Starting patch validate.
[Info  - 09:05:11] Patch file: c:/Users/bvini/Downloads/harpia.PTM
[Info  - 09:05:11] Starting build for environment LIBQ3M.
[Info  - 09:05:16] Starting build using RPO token ...
[Info  - 09:05:40] Patch validated without structure problems.
[Info  - 09:05:40] Aborting end build (rollback changes).
[Info  - 09:05:41] Patch validate finished.
[Info  - 09:05:41] Starting apply patch.
[Info  - 09:05:41] Starting build for environment LIBQ3M.
[Info  - 09:05:45] Starting build using RPO token ...
[Info  - 09:05:45] Applying patch file: c:/Users/bvini/Downloads/harpia.PTM
[Info  - 09:06:19] Aborting end build (rollback changes).
[Info  - 09:06:19] Apply patch finished.
[Error - 09:06:19] Patch validate could not be executed.

**Comment by killerall** [comment]
Bom dia,pelo Log, vocêe esta com a extensão da TDSVscode, esse repositório é do I Love Advpl.

Por favor, abra issue no outro repositorio.
