### ISSUE TITLE
Erro de conexão do servidor TSS

### ISSUE THREAD

**Issue by pedrojlima** [totvs/advpl-vscode#530]
Bom dia, quando estou tentando conectar o servidor TSS exibe a mensagem abaixo. segue os logs também
![TSS](https://user-images.githubusercontent.com/85879332/170497622-619ad8c0-03bf-445f-861c-85e4a41cf574.PNG)
[totvsls.log](https://github.com/totvs/advpl-vscode/files/8779321/totvsls.log)
[totvsls_in.log](https://github.com/totvs/advpl-vscode/files/8779322/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/advpl-vscode/files/8779323/totvsls_out.log)

**Comment by AlencarGabriel** [comment]
Olá @pedrojlima ,
você está usando a extensão TDS-VsCode, e não esta aqui.

Favor reabrir sua issue no outro repositório: https://github.com/totvs/tds-vscode
