### ISSUE TITLE
Não consigo extrair fontes padrão do RPO para geração de PATCH

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/advpl-vscode#531]
Boa tarde,

Gerei um TXT com o seguinte conteúdo:

`
GPER040.PRX
GPER106.PRW
`

Mas ele não consegue gerar o patch.

![image](https://user-images.githubusercontent.com/26228097/171717175-c4c0c9e4-83a1-466e-8f1b-892440d6bec4.png)

**Comment by robsonrosilva** [comment]
Não sabia que tinham mudado esse comportamento.
Obrigado.

**Comment by AlencarGabriel** [comment]
> Não sabia que tinham mudado esse comportamento. Obrigado.

Opa @robsonrosilva , só complementando. Você até consegue, mas só dos seus fontes customizados, fontes padrão não.
