### ISSUE TITLE
VSCode gerando arquivos em branco sozinho

### ISSUE THREAD

**Issue by snlacerda89** [totvs/advpl-vscode#532]
Apos a atualizacao de Maio, meu VSCode passou a gerar inumeros arquivos AP_ em branco na pasta.

<img width="1433" alt="Captura de Tela 2022-06-13 às 17 19 24" src="https://user-images.githubusercontent.com/89091217/173438822-dc7dcbe2-b13e-4c94-b51d-3b9599b73b44.png">

**Comment by fhfavaretto** [comment]
sigo com o mesmo problema.

**Comment by killerall** [comment]
Opa, qual versão da extensão vocês estão usando?

**Comment by snlacerda89** [comment]
1.3.14

**Comment by killerall** [comment]
Eu acredito que vcs estao utilizando a extensao do TDS, e não essa I Love ADVPL. Melhor abrir um issue no repo deles.
