### ISSUE TITLE
A103NFISCAL

### ISSUE THREAD

**Issue by Miqueiasfer** [totvs/advpl-vscode#536]
Bom Dia, apos compilar o ultimo pacote do backoffice na release 12.1.33 estou tendo problema para usar a funcao A103NFISCAL para visualizar notas, esta dando o erro log abaixo:

array out of bounds  on { | U | IF( PCOUNT() == 0, AINFADIC[18], AINFADIC[18] := U ) }(MATA103X.PRX) 29/06/2022 17:32:46 line : 12415

Alguem sabe se mudou a forma de chamar o A103NFISCAL?

**Comment by robertovalentim** [comment]
@Miqueiasfer, bom dia!

Aqui também estava dando esse mesmo erro, foi só atualizar os fontes do MATA103 baixando os pacotes na centrla de atualizações que tudo foi normalizado.
