### ISSUE TITLE
Erro ao aplicar patch com as ultimas versões do binário

### ISSUE THREAD

**Issue by caiocrol** [totvs/advpl-vscode#537]
Ao tentar aplicar algum patch com a opção "only newest files?" igual a não é apresentado um erro no console (erro abaixo)

esse problema está acontecendo apenas com a ultima versão do binário, até a build 20.3.0.8 do harpia o erro não acontece,
com a extensão oficial da totvs o erro tb não ocorre mesmo nas versões mais recentes do binário.

Starting Patch Application...
{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't apply patch:Patch file C:\TOTVS\totvs_harpia\Protheus_data_dic_in_db\tmptdsspon010116596\correção eai preparein tttm120.ptmtmptdsspon010116596\correção eai preparein tttm12001-08-2022-08-26-41.ptm not found"}]}]}

**Comment by killerall** [comment]
Opa, se essa opcao, o patch aplicou normal?

**Comment by caiocrol** [comment]
boa tarde, 
isso mesmo, com a opção "only newest files?" igual a sim o patch é aplicado normalmente, apenas com a opção igual a N que não é aplicado 

me parece algo semelhante dessa issue aqui?
https://github.com/totvs/advpl-vscode/issues/452

o caminho que mostra no erro é o caminho do meu rootpath, sendo que eu selecionei um patch que está em outro diretório.

com a extensão da totvs o patch aplica das duas formas.

**Comment by killerall** [comment]
Achamos aqui uma mudança de comportamento do binario, estamos tratando aqui, ja ia liberar uma versao para mac, aproveito e coloco esse ponto, obrigado por avisar.

**Comment by killerall** [comment]
Corrigido na versão v0.15.1
