### ISSUE TITLE
Descrições do menu de contexto mudaram depois da atualização do vscode

### ISSUE THREAD

**Issue by caiocrol** [totvs/advpl-vscode#538]
Depois da ultima atualização do vscode,  as descrições referente a essa extensão não estão mostrando corretamente, está mostrando o nome real no lugar da descrição anterior.

![image](https://user-images.githubusercontent.com/17690093/183159756-b88f4c7b-3ae9-4d9c-adfd-afda981e948f.png)
![image](https://user-images.githubusercontent.com/17690093/183159796-5a5778d6-b3f0-4c8e-8428-add87a1876f1.png)
![image](https://user-images.githubusercontent.com/17690093/183159826-5856fe3d-4dc8-47b5-88a9-b4e50ab412d1.png)

**Comment by robsonrosilva** [comment]
Estou com esse mesmo problema.

**Comment by AlencarGabriel** [comment]
Estamos avaliando o problema aqui.

**Comment by killerall** [comment]
Corrigido na versão v0.15.1
