### ISSUE TITLE
O Meu vs code solicita os fontes padrões sempre que debug.

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/advpl-vscode#539]
De um tempo o me VS Code esta sempre informando que não encontrar os fontes padrões da Totvs.
Alguém pode me orientar como desativar???
Obrigado
![image](https://user-images.githubusercontent.com/72528922/189986836-35c33759-9fc6-43a0-8673-1be24e25010b.png)

**Comment by AlencarGabriel** [comment]
Olá @ofnerjulio ,

acredito que definir a seguinte configuração resolva seu problema: `advpl.debug_ignoreSourceNotFound: true`.

**Comment by ofnerjulio** [comment]
Bom dia AlencarGabriel,
Não consegui encontrar esse opção, refiz a minha configuração e resolveu o problema.

![image](https://user-images.githubusercontent.com/72528922/190646131-5070e632-baba-498e-b36f-3a1b9fb2718a.png)

**Comment by AlencarGabriel** [comment]
@ofnerjulio, essas configurações ai são de outra extensão, a https://github.com/totvs/tds-vscode.

Nessa extensão aqui é nos settings da workspace, não no launch como você mandou.

Como pelo visto você utiliza a outra extensão como principal, recomendo abrir essa issue lá no outro repositório.

**Comment by ofnerjulio** [comment]
Pior que não uso outra.
![image](https://user-images.githubusercontent.com/72528922/193065745-d01c8777-7500-4d91-87f0-6cc7a98cee11.png)
