### ISSUE TITLE
Organizar servers por pasta

### ISSUE THREAD

**Issue by danielblaia** [totvs/advpl-vscode#540]
Bom dia
Queria abrir uma solicitação de melhoria pra poder agrupar os servers por pasta, na seção TOTVS:SERVIDORES
Tenho muitos clientes aqui e é um caos
Obrigado
Daniel

**Comment by AlencarGabriel** [comment]
Olá @danielblaia ,

esta extensão aqui já permite realizar agrupamentos de servidores/ambientes:  https://github.com/totvs/advpl-vscode/wiki/Gerenciador-de-Ambientes

Mas pelo que entendi você deseja fazer isso na outra extensão, a TDS-VSCode. 

Se não desejar utilizar esta, peço que reabra sua issue lá no outro repositório: https://github.com/totvs/tds-vscode

**Comment by danielblaia** [comment]
oi Gabriel,

não sei onde você configurou isso
olha como fica meu VS
[image: image.png]
As extensões que tenho são:
[image: image.png]

Em sex., 23 de set. de 2022 às 11:27, Gabriel Alencar <
***@***.***> escreveu:

**Comment by AlencarGabriel** [comment]
Respondendo via e-mail não chegam anexos.

Mas eu enviei o link da documentação dessa feature nessa extensão aqui.

**Comment by danielblaia** [comment]
oi Gabriel
as extensões que eu tenho são:
TOTVS Developer Studio for VsCode
Numbered Bookmarks

só essas

e não consigo fazer o que você falou
tem o nome correto dessa extensão?
procurei por gerenciador de ambientes e não achei

Em sex., 23 de set. de 2022 às 11:33, Gabriel Alencar <
***@***.***> escreveu:

**Comment by AlencarGabriel** [comment]
A extensão é essa:

![image](https://user-images.githubusercontent.com/10109480/191988198-f639b15e-018b-48b5-9984-54ccf06208a2.png)

**Comment by danielblaia** [comment]
essa extensão é oficial da Totvs?

Em sex., 23 de set. de 2022 às 11:46, Gabriel Alencar <
***@***.***> escreveu:

**Comment by AlencarGabriel** [comment]
Mas se deseja este recurso na extensão TDS, abra uma issue no outro repositório que lhe passei.

**Comment by danielblaia** [comment]
entendi
obrigado
instalei a ADVPL aqui, mas me obriga a cadastrar todos os servers novamente

eu abri outra issue lá

obrigado

Em sex., 23 de set. de 2022 às 11:52, Gabriel Alencar <
***@***.***> escreveu:

**Comment by AlencarGabriel** [comment]
Sim, porque é outra extensão pra desenvolvimento AdvPL, com funcionamento diferente.
