### ISSUE TITLE
Não consigo abrir um prw pela função.

### ISSUE THREAD

**Issue by thelucasx** [totvs/advpl-vscode#541]
Fiz um código básico , estou tentador rodar ele dentro de um menu que fiz no protheus e nao consigo , o que pode ser ?
qual é o procedimento a ser feito ?
![image](https://user-images.githubusercontent.com/54607037/192274716-52cb7302-d8e2-4f3a-a333-7e4ec182c61e.png)

**Comment by AlencarGabriel** [comment]
@thelucasx , parece que você cadastrou no menu o nome do arquivo, e não da função.

Lembrando que se sua função for `user function` você deve informar isso também no tipo de função do menu.
