### ISSUE TITLE
ADVPL - Relacionamento das tabelas de menu - MPMENU_MENU

### ISSUE THREAD

**Issue by 3713750n** [totvs/advpl-vscode#545]
Estou desenvolvendo um relatório de usuário x acessos e não localizei documentação TDN sobre o relacionamento das tabelas abaixo.

SYS_GRP_MODULE
MPMENU_MENU
MPMENU_FUNCTION
MPMENU_I18N
FROM MPMENU_ITEM

Em testes, o relacionamento abaixo gera réplicas de registros indevidos no JOIN MPMENU_ITEM com a MPMENU_MENU por falta de algum critério ou porque deveria ser relacionada com outras tabela que não identifiquei.

SELECT *
FROM SYS_USR
INNER JOIN SYS_USR_GROUPS ON (SYS_USR_GROUPS.USR_ID = SYS_USR.USR_ID AND SYS_USR_GROUPS.D_E_L_E_T_ = '')
INNER JOIN SYS_GRP_GROUP ON (SYS_GRP_GROUP.GR__ID = SYS_USR_GROUPS.USR_GRUPO AND SYS_GRP_GROUP.D_E_L_E_T_ = '')
LEFT JOIN SYS_USR_MODULE ON (SYS_USR_MODULE.USR_ID = SYS_USR.USR_ID AND SYS_USR_MODULE.USR_ACESSO = 'T' AND SYS_USR_MODULE.D_E_L_E_T_ = '')
LEFT JOIN SYS_GRP_MODULE ON (SYS_GRP_MODULE.GR__ID = SYS_GRP_GROUP.GR__ID AND SYS_GRP_MODULE.GR__ACESSO = 'T' AND SYS_GRP_MODULE.D_E_L_E_T_ = '')
LEFT JOIN MPMENU_MENU MPMENU_MENU_USR ON (MPMENU_MENU_USR.M_ID = SYS_USR_MODULE.USR_ARQMENU AND MPMENU_MENU_USR.D_E_L_E_T_ = '')
LEFT JOIN MPMENU_MENU MPMENU_MENU_GRP ON (MPMENU_MENU_GRP.M_ID = SYS_GRP_MODULE.GR__ARQMENU AND MPMENU_MENU_GRP.D_E_L_E_T_ = '')
LEFT JOIN MPMENU_ITEM MPMENU_ITEM_USR ON (MPMENU_ITEM_USR.I_ID_MENU = MPMENU_MENU_USR.M_ID AND MPMENU_ITEM_USR.I_MODULE = MPMENU_MENU_USR.M_MODULE AND MPMENU_ITEM_USR.D_E_L_E_T_ = '')
LEFT JOIN MPMENU_ITEM MPMENU_ITEM_GRP ON (MPMENU_ITEM_GRP.I_ID_MENU = MPMENU_MENU_GRP.M_ID AND MPMENU_ITEM_GRP.I_MODULE = MPMENU_MENU_GRP.M_MODULE AND MPMENU_ITEM_GRP.D_E_L_E_T_ = '')
--LEFT JOIN MPMENU_I18N MPMENU_I18N_USR ON (MPMENU_I18N_USR.N_PAREN_ID = MPMENU_ITEM_USR.I_ID AND MPMENU_I18N_USR.N_LANG = '1' AND MPMENU_I18N_USR.D_E_L_E_T_ = '')
--LEFT JOIN MPMENU_I18N MPMENU_I18N_GRP ON (MPMENU_I18N_GRP.N_PAREN_ID = MPMENU_ITEM_GRP.I_ID AND MPMENU_I18N_GRP.N_LANG = '1' AND MPMENU_I18N_GRP.D_E_L_E_T_ = '')
WHERE SYS_USR.D_E_L_E_T_ = ''

Se alguém puder orientar, agradeço

abc.
Eli

**Comment by viniciusgati** [comment]
Meu amigo aqui não é o lugar pra isso, aqui é relacionado ao plugin do vscode...

conheça o http://devforum.totvs.com.br/
lá é pra dúvidas em geral referente a protheus, fluig, etc!
