### ISSUE TITLE
Erro Debug VsCode x Smarclient

### ISSUE THREAD

**Issue by edvaldo3p** [totvs/advpl-vscode#547]
Prezados, Boa tarde.

Ao executar o debug no VsCode, depois da tela de login ao carregar o smarclient pelo debug, o smart simplesmente fecha tudo, alguem está passando por essa situação?
Algumas horas entra e outras vezes não, 98% das vezes ele cai.

1 - Ja atualizei Smarclient e Appserver não deu certo.
2 - Já testei outras versões do VsCode também nao deu certo.
3 - Já fiz o procedimento de copiar a dll opengl32sw também nao funcionou

Minha versão é a 12.1.33 segue abaixo o erro na tela do VSCode.
SmartClient closed. ExitCode=-2147483645 ExistStatus=CancelExit

Abaixo segue dados do Console.log
[INFO ][SERVER] [Thread 4464] INACTIVETIMEOUT changed from [0] seconds to [3600] seconds.
2022-12-07T12:20:12.365000-03:00 8788|[VDRPORT] 221207_122012 2254 BPC2069 E x 04 ctx:031 error 64 (operacao em conexao fechada remotamente) in receive from client 10.10.1.8:53324
2022-12-07T12:20:12.366000-03:00 4464|
[WARN ][SERVER] [THROW][Thread  4464] tConnnErrorException (8:Erro de comunicacao: Erro de sincronismo) on C:\bamboo\xml-data\build-dir\TP11-OF20310-TECXWIN64\lib_comm\msgmanager.cpp:472
2022-12-07T12:20:12.368000-03:00 4464|
[WARN ][SERVER] [Thread 4464] [07/12/2022 12:20:12] Error ending thread (administrador, SRVPROTHEUS) Erro de comunicacao: Erro de sincronismo
2022-12-07T12:20:12.368000-03:00 2824|
[INFO ][SERVER] [[Thread  2824][07/12/2022 12:20:12] Debugger finished ( (administrador, SRVPROTHEUS)
2022-12-07T12:20:13.019000-03:00 4920|
[INFO ][SERVER] [Thread  4920] JOB Thread finished [-FINEXECFKS]
2022-12-07T12:20:17.461000-03:00 11136|
[INFO ][SERVER] [Thread 11136] JOB Thread finished [-FINEXECFKS]
2022-12-07T12:20:17.782000-03:00 10208|
[INFO ][SERVER] [Thread 10208] JOB Thread finished [-FINEXECJOB]
2022-12-07T12:20:21.319000-03:00 10460|

Please type Ctrl-C or Ctrl-Break to terminate! (evt: 2)

**Comment by xluc4s11** [comment]
Estou com o mesmo problema, alguem pode ajudar?

**Comment by xluc4s11** [comment]
Bom dia,
O problema esta depois que atualizei o smartclient.
Voltei o backup e funcionou.

O backup o smartclient.exe esta com data 12/04/2022.
Já o atualizado estava com data 13/10/2022.
