### ISSUE TITLE
No linux tenho invalid json input

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#548]
olã no linux estou tendo 

SyntaxError: Unexpected end of JSON input
Compilation finished at Wed Jan 04 2023 23:24:09 GMT-0300 (Brasilia Standard Time) Elapsed (0.017 secs.)

de que json se refere? o que posso fazer para identificar?

No linux tbm não gera o cipher, tem alguma coisa que precisa instalar pra gerar? -> esse já resolvi instalando uma lib conforme: https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di

**Comment by killerall** [comment]
Sim vc precisa ter instalado o openssl.
Para ver se falta alguma lib no terminal, no seu home:
 $ cd .vscode/extensions/killerall.advpl-vscode-0.15.1/bin/alpha/linux/
$ ldd AdvplDebugBridgeC

**Comment by viniciusgati** [comment]
no caso a sua utiliza isso também pra validar as chaves de compilação? ou não?

**Comment by killerall** [comment]
Sobre a chave de compilcao:
https://github.com/totvs/advpl-vscode/wiki/Chave-de-compila%C3%A7%C3%A3o

**Comment by viniciusgati** [comment]
gerei cipher novo, coloquei corretamente os dados da chave e mesmo assim tenho erro de que é invalido


Invalid Compile Key
Invalid passwordCipher
Compilation aborted, check the log or the Problems tab!
Compilation finished at Thu Jan 05 2023 09:31:42 GMT-0300 (Brasilia Standard Time) Elapsed (0.357 secs.)

existe algum log que posso ver se tem algo de errado em alguma outra coisa?

**Comment by killerall** [comment]
Cole aqui seu settingl.json

**Comment by viniciusgati** [comment]
`{
    "workbench.iconTheme":"material-icon-theme",
    "advpl.environments":[
       {
          "name":"M12_33_SRVW01_VINICIUS",
          "environment":"R33-VINICIUS",
          "smartClientPath":"/home/vinicius/Work/smartclient-19319/",
          "includeList":"/home/vinicius/Work/includes/INCLUDES_M11/;/home/vinicius/Work/includes/m12-include;/home/vinicius/Work/includes/m12-include-mil/;/home/vinicius/Work/includes/m12-include-tlpp/",
          "server":"srvw01.itmil.com.br",
          "port":"10706",
          "user":"admin",
          "passwordCipher":"BMtYQA3n1t2hy6PLx0ag1gd7Qiele0I+87Z/g0KBQCGdbrnsb9RaJXg5IZj4bFX6AAGlW9yodiXdStkZzu2EsErf=",
          "serverVersion":"210324P",
          "rpoType":"TOP",
          "language":"PORTUGUESE",
          "totvs_language":"advpl",
          "ssl": true
       },
       {
         "name":"srvw01 CEV",
         "environment":"M12R127_MOBILE",
         "smartClientPath":"/home/vinicius/Work/smartclient-19319/",
         "includeList":"/home/vinicius/Work/includes/INCLUDES_M11/;/home/vinicius/Work/includes/m12-include;/home/vinicius/Work/includes/m12-include-mil/;/home/vinicius/Work/includes/m12-include-tlpp/",
         "server":"srvw01.itmil.com.br",
         "port":"10500",
         "user":"admin",
         "passwordCipher":"LoPCuopYJmDSBV4y0WNg9oiX6m/YZyekZJaiMX53qJDXcMqvFgQyr+1W4pxTaGyLAADQdrKseR9IUQKi1MceqM2f=",
         "serverVersion":"191205P",
         "ssl": false
      }
    ],
    "editor.fontFamily": "'Ubuntu Mono', monospace",
    "advpl.selectedEnvironment": "M12_33_SRVW01_VINICIUS",
    "advpl.debug_multiThread": true,
    "editor.selectionHighlight": true,
    "editor.insertSpaces": false,
    "editor.folding": true,
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "selection",
    "editor.rulers": [
       100,
    ],
    "files.exclude":{
       "**/*.git":true,
       "**/*.bak":true,
       "**/*.orig":true,
       "**/*.ppx_prw":true,
       "**/*.ppx_PRW":true,
       "**/*.svn":true,
       "**/*.hg":true,
       "**/CVS":true,
       "**/*.DS_Store":true,
       "**/.classpath":true,
       "**/.project":true,
       "**/.settings":true,
       "**/.factorypath":true
    },
    "workbench.editor.enablePreview": false,
    "workbench.tree.renderIndentGuides": "always",
    "workbench.editor.wrapTabs": true,
    "advpl.authorization_generation":"20221108",
    "advpl.authorization_validation":"20230206",
    "advpl.authorization_permission":"1",
    "advpl.authorization_code":"012LEA034QSUQ74A1E7671292",
    "advpl.startProgram":"SIGAADV",
    "advpl.debug_showTables": false,
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.logger": true,
    "advpl.enableCoverage": false,
    "advpl.compile_force_recompile": true,
    "vsintellicode.modify.editor.suggestSelection":"automaticallyOverrodeDefaultValue",
    "workbench.colorTheme":"Visual Studio Light",
    "redhat.telemetry.enabled": true,
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "git.confirmSync": false,
    "[typescript]":{
       "editor.formatOnSave": false,
       "editor.codeActionsOnSave":{
          "source.fixAll.eslint": true
       }
    },
    "[typescriptreact]":{
       "editor.formatOnSave": false,
       "editor.codeActionsOnSave":{
          "source.fixAll.eslint": true
       }
   },
   "editor.accessibilitySupport": "off",
   "esp.mainAdvplExtension":"KillerAll.advpl-vscode",
 }`

**Comment by killerall** [comment]
Seu log ta ativo,
Va no /tmp e apague o AdvplDebugBridgeC_0.log 
Ai mande compilar denovo, vai gerar denovo o log, ai coloca aqui pf.

**Comment by viniciusgati** [comment]
[0x00007f6f16c91c80][05-01-2023 09:54:28.383487] - Start AdvplDebugBridge
[0x00007f6f16c91c80][05-01-2023 09:54:28.412374] - Fim->keyvalid
[0x00007f6f16c91c80][05-01-2023 09:54:28.412407] - Error on keyValid
[0x00007f6f16c91c80][05-01-2023 09:54:28.412412] - IDSE-RIAL
[0x00007f6f16c91c80][05-01-2023 09:54:28.412416] - 20221108
[0x00007f6f16c91c80][05-01-2023 09:54:28.412419] - 20230206
[0x00007f6f16c91c80][05-01-2023 09:54:28.412422] - 1
[0x00007f6f16c91c80][05-01-2023 09:54:28.412428] - 012LEA034QSUQ74A1E7671292
[0x00007f6f16c91c80][05-01-2023 09:54:28.412436] - End keyValid
[0x00007f6f16c91c80][05-01-2023 09:54:28.928810] - Invalid passwordCipher
Error on Cipher.
[0x00007f6f16c91c80][05-01-2023 09:54:28.928880] - [SEND][START
[0x00007f6f16c91c80][05-01-2023 09:54:28.928916] - [SEND][END]
[0x00007f6f16c91c80][05-01-2023 09:54:29.111409] - End AdvplDebugBridge

deu isso

**Comment by viniciusgati** [comment]
[0x00007f6f16c91c80][05-01-2023 09:54:28.383487] - Start AdvplDebugBridge
[0x00007f6f16c91c80][05-01-2023 09:54:28.412374] - Fim->keyvalid
[0x00007f6f16c91c80][05-01-2023 09:54:28.412407] - Error on keyValid
[0x00007f6f16c91c80][05-01-2023 09:54:28.412412] - IDSE-RIAL
[0x00007f6f16c91c80][05-01-2023 09:54:28.412416] - 20221108
[0x00007f6f16c91c80][05-01-2023 09:54:28.412419] - 20230206
[0x00007f6f16c91c80][05-01-2023 09:54:28.412422] - 1
[0x00007f6f16c91c80][05-01-2023 09:54:28.412428] - XXXXXXXXXXXXXXXXXX
[0x00007f6f16c91c80][05-01-2023 09:54:28.412436] - End keyValid
[0x00007f6f16c91c80][05-01-2023 09:54:28.928810] - Invalid passwordCipher
Error on Cipher.
[0x00007f6f16c91c80][05-01-2023 09:54:28.928880] - [SEND][START
[0x00007f6f16c91c80][05-01-2023 09:54:28.928916] - [SEND][END]
[0x00007f6f16c91c80][05-01-2023 09:54:29.111409] - End AdvplDebugBridge

**Comment by killerall** [comment]
Verifica se vc tem instalado o udevadm

**Comment by viniciusgati** [comment]
vinicius@vinicius-probook:~/.vscode/extensions/killerall.advpl-vscode-0.15.1/bin/alpha/linux$ udevadm
Command verb required.

acredito que sim

**Comment by viniciusgati** [comment]
nvme0n1     259:0    0 465,8G  0 disk

**Comment by killerall** [comment]
Não consegui identificar nada de errado,
Eu tentaria gerar uma nova chave de compilacao, e gerar uma nova Cipher da senha.

**Comment by viniciusgati** [comment]
Sabe me dizer se as chaves de compilação agora são geradas tbm usando o SO destino?
Pois se for isso acho que esse é o problema, essa chave é do meu computador antigo no windows.

**Comment by killerall** [comment]
As chaves sao geradas baseado no ID, ele muda se trocar o SO, ou mesmo o mesmo SO so que uma nova instalação.

**Comment by viniciusgati** [comment]
mudei pra 33 e não precisa mais desse esquema mas possívelmente o problema foi mudar de maquina e precisava gerar outra chave.
