### ISSUE TITLE
Alterar machineid

### ISSUE THREAD

**Issue by viniciusgati** [totvs/advpl-vscode#549]
no linux onde consigo alterar o volume id?

![image](https://user-images.githubusercontent.com/60268/210692093-3dc7c204-2b1b-4dc6-957d-0701baeec52b.png)

esse que aparece na imagem, como consigo ele?

**Comment by killerall** [comment]
Essa imagem é da extensão TDS(https://github.com/totvs/tds-vscode)
Mais facil você ter ajuda sobre isso la.
