### ISSUE TITLE
Não roda de forma correta o ponto de entrada 

### ISSUE THREAD

**Issue by thelucasx** [totvs/advpl-vscode#550]
Gente estou fazendo um ponto de entrada, onde ele é alerta quando o usuário, alterar dados do produto e salva em um campo que criei, quantas vezes foi alterado o produto. 

Quando uso a função do A010TOK, o programa executa somente no botão de incluir no cadastro de produto, Não funciona no Botão Alterar.

e quando uso a função MT010ALT o programa não esboça reação. 

Alguem poderia me dar um luz?

#INCLUDE "protheus.ch"

User Function A010TOK()
Local aArea := GetArea()

If M->B1_VALID $ 1 .And. Empty(M->B1_CUSTOM)
	MsgStop("Produto Cadastrado com Sucesso!!!")
	B1_VALID++

Endif

If M->B1_VALID $ 2 .And. Empty(M->B1_CUSTOM)
	MsgAlert("Este Produto sofreu alterações!")
	MsgStop("Para Mudanças neste campo, Por Favor preencha o campo alterações !")
	B1_VALID++
	Return (.f.)

Endif

If M->B1_VALID $ 3 .And. Empty(M->B1_CUSTOM)
	MsgAlert("Este produto sofreu Alterações 2 Vezes !!")
	MsgStop("Para Mudanças neste campo, Por Favor preencha o campo alterações !!")
	B1_VALID++
	Return (.f.)
Endif

If M->B1_VALID >= 4 .And. Empty(M->B1_CUSTOM)
	MsgAlert("Este produto sofreu" + (B1_VALID - 1) + "Alterações!!")
	MsgStop("Para Mudanças neste campo, Por Favor preencha o campo alterações !!")
	B1_VALID++	
	Return (.f.)
Endif

RestArea(aArea)
Return (.t.)

**Comment by thelucasx** [comment]
Consegui fazer ele rodar no botão de alterar, mas ele não acrescenta nenhum dado e nem consulta.

**Comment by AlencarGabriel** [comment]
Olá @thelucasx ,

Este aqui não é o canal adequado para esse tipo de dúvida. Aqui cuidamos dos problemas relacionados a extensão de debug e compilação AdvPL. Recomendo o canal de suporte da TOTVS, ou a comunidade: https://devforum.totvs.com.br

Mas para não sair de mãos vazias, acredito que seu problema esteja relacionado ao fato de você estar manipulando os campos de uma tabela, sem fazer o devido lock ([RecLock()](https://tdn.totvs.com/pages/releaseview.action?pageId=24347041)) para alteração do registro posicionado.

Espero ter ajudado!
