### ISSUE TITLE
Breakpause , no advpl

### ISSUE THREAD

**Issue by thelucasx** [totvs/advpl-vscode#551]
Estou fazendo um codigo de ponto de entrada, que uso um DO WHILE , mas já certo ponto do codigo onde o usuario precisa inserir os dados , é o DO WHILE  fica no loop , Gostaria de saber se existe um pause para essa situação. onde o sistema permaneça no estado atual, para o usuario inserir o dados mas sem sair da condição

**Comment by AlencarGabriel** [comment]
@thelucasx , novamente vou te pedir para migrar de canal. Dúvidas de programação AdvPL/TLPP favor tirar no fórum: https://devforum.totvs.com.br ou via suporte TOTVS.

**Comment by AlencarGabriel** [comment]
Uma observação, fazer uso de APIs ou chamada de interface dentro de loop viola boas práticas de desenvolvimento, e de regras do ADvPL. 

Veja regra CA1003: https://sonar-rules.engpro.totvs.com.br/menu/rules

![image](https://user-images.githubusercontent.com/10109480/218551101-0ee756a1-537e-4a8f-92a8-eef021585c70.png)

**Comment by thelucasx** [comment]
Olá, Comecei a usar o DevForum, ainda estou aguardando alguem de bom coração lá para me auxiliar.
não estou usando APIs ou chamada de interface, É Somente uma verificação que se o produto foi alterado. se sim o usuario terá que preencher o campo alterações .
Eu tentei fazer com IF só que a função executa uma ultima vez e permite que o produto seja salvo. por isso estou fazendo com o while, para que ele não deixe que o produto seja salvo sem preencher o campo alterações.

**Comment by AlencarGabriel** [comment]
> Olá, Comecei a usar o DevForum, ainda estou aguardando alguem de bom coração lá para me auxiliar. não estou usando APIs ou chamada de interface, É Somente uma verificação que se o produto foi alterado. se sim o usuario terá que preencher o campo alterações . Eu tentei fazer com IF só que a função executa uma ultima vez e permite que o produto seja salvo. por isso estou fazendo com o while, para que ele não deixe que o produto seja salvo sem preencher o campo alterações.

Mesmo assim não é uma boa prática vc travar um loop para aguardar uma ação do usuário, principalmente via interface gráfica.

**Comment by thelucasx** [comment]
Poderia me recomendar alguma solução para este meu problema, sem usar nenhuma estrutura de repetição. 
Não posso deixar esse campo como obrigatório, pois ele inicia nulo.

**Comment by AlencarGabriel** [comment]
Acredito que no seu caso vc precisa olhar outro tipo de ponto de entrada, que talvez impeça ele de confirmar ou seguir com a operação se não estiver com esse campo preenchido. Talvez algum P.E. que receba um boleano pra continuar ou não a alteração.
