### ISSUE TITLE
RPO in use - AppMap - Ao abrir protheus

### ISSUE THREAD

**Issue by RodolfoTrevisolSchumann** [totvs/advpl-vscode#553]
Boa tarde.

Estou com um problema que acontece pelo menos uma vez por dia.
Utilizo o Protheus em modo debug durante o dia, sem problemas.
Ai do nada, ao iniciar um programa via debug (SIGAMDI ou SIGAADV) fica apresentando as seguintes mensagens:
![image](https://user-images.githubusercontent.com/84867276/228621876-926a3e42-f544-41a0-835e-ed2da8e99e64.png)
e
![image](https://user-images.githubusercontent.com/84867276/228623070-04430d9d-1275-4998-b16d-5fc1a01532c9.png)

No log do console apresenta:
![image](https://user-images.githubusercontent.com/84867276/228622519-2175872f-edf0-4bf1-9e21-a8b6d6f37d92.png)

Solução é reiniciar o appserver até que volte a funcionar.
O caso também ocorre sem o modo debug.
Percebi que meus colegas que utilizam a extensão da [TOTVS ](https://github.com/totvs/tds-vscode) no vscode não tem esse problema.

Alguém já passou por isso?

**Comment by AlencarGabriel** [comment]
Qual versão do AppServer e Smartclient que está usando?

**Comment by RodolfoTrevisolSchumann** [comment]
> Qual versão do AppServer e Smartclient que está usando?


![image](https://user-images.githubusercontent.com/84867276/228856745-14a22f62-c29a-4259-a532-a076a43d15c6.png)

**Comment by AlencarGabriel** [comment]
@RodolfoTrevisolSchumann , fiz vários testes com esses artefatos em minha base. Mas não consegui reproduzir. 

Poderia nos encaminhar seu INI para tentar reproduzir o cenário melhor?

**Comment by RodolfoTrevisolSchumann** [comment]
Segue INI do serviço

[appserver.txt](https://github.com/totvs/advpl-vscode/files/11121178/appserver.txt)

**Comment by AlencarGabriel** [comment]
Recebemos outros relatos de pessoas usando a TDS VsCode, então problema não parece estar relacionado a extensão utilizada.

Recomendo atualizar a versão do appserver para a última liberada: **20.3.1.4**. 

Persistindo, recomendo também atualizar o arquivo tlpp.rpo do seu appserver que pode ser obtido aqui: https://tdn.totvs.com/display/tec/Downloads

As outras recomendações que eu daria você já usa:

```ini
[APP_MONITOR]
enable=0

[General]
BuildKillUsers=1
```

Como observação apenas, vi que seu INI possui seções duplicadas, para evitar problemas futuros ou conflitos recomendo revê-las.
