### ISSUE TITLE
Incompatible types between C and U - Não compila fonte .tlpp

### ISSUE THREAD

**Issue by renato-calabro** [totvs/advpl-vscode#557]
Olá!

Estou tentando compilar um fonte que está gerando erro de sintaxe, por ser tlpp.

Os erros gerados são:
**Error: Incompatible types between C and U (778) Error: Incompatible types between N and U (779) Error: Incompatible types between C and U (780) Error: Incompatible types between N and U (781) Error: Incompatible types between C and U (782) Error: Incompatible types between C and U (783) Error: Incompatible types between L and U **

Verificando o trecho do fonte, estão os seguintes conteúdos:

L.778 default uValCom    := 0
L.779 default uDescLog   := ""
L.780 default nOperation := 3
L.781 default uNumPed    := ""
L.782 default uObsPed    :=  ""
L.783 default lAdiantamento := .f.

Contudo, um colega que utiliza o TDS compilou o mesmo fonte e não gerou erros.

**Comment by AlencarGabriel** [comment]
@renato-calabro , dá uma olhada nos teus includes. 

Veja se está usando tlpp-core.th e/ou se o protheus.ch é o mais atualizado.

**Comment by renato-calabro** [comment]
Olá @AlencarGabriel!

Durante as tentativas e erros, instalei o TDS e o erro persistiu.
Cheguei nessa conclusão dos CHs.
Atualizei o protheus.ch e ele aceitou a compilação.

Vou deixar no histórico para futuras consultas de outros que tiverem o mesmo problema. 

Obrigado por retornar.

**Comment by AlencarGabriel** [comment]
Sim, as extensões são diferentes mas a compilação é no appserver, e esse erro quando associado aos `Default` é sempre por conta de include desatualizado.

Uma obs. fontes tlpp tem que usar o tlpp-core.th ok?

**Comment by renato-calabro** [comment]
Sim, esse th eu já estou usando!
Obrigado mais uma vez 😉
