### ISSUE TITLE
Debugar no VSCODE

### ISSUE THREAD

**Issue by jacksoncapelato** [totvs/advpl-vscode#558]
Meu Vscode nao debuga, nao apresenta erro e tambem nao abre o protheus na chamada do f5.

![image](https://github.com/totvs/advpl-vscode/assets/144359595/90eb1eb3-8c90-4634-b25c-88745f4b17e8)
![image](https://github.com/totvs/advpl-vscode/assets/144359595/cecce4dc-bf13-4a61-97b9-5d0f66a2b5d3)

ja desinstalei e reinstalei varias vezes.

alguem poderia me ajudar com isso

**Comment by AlencarGabriel** [comment]
Olá @jacksoncapelato .

Pelo que pude ver nas suas configurações, você não utiliza essa extensão, e sim a [TDS-VSCode](https://github.com/totvs/tds-vscode). Recomendo que reabra essa issue lá no outro repo.
