### ISSUE TITLE
ErrorLog Ao Iniciar o Debug via VsCode

### ISSUE THREAD

**Issue by WesleyOFranca** [totvs/advpl-vscode#559]
Estou tentando realizar um debug realizando a abertura do do smartcliente  porém está aprenserando o errorlog abaixo.

Alias does not exist SB1 on U_BANCO001(BANCO001.PRW) 16/01/2024 22:01:25 line : 17

**Comment by AlencarGabriel** [comment]
Olá @WesleyOFranca , 

provavelmente você está chamando o fonte e ele não tem um ambiente com conexão ao banco/dbaccess aberto, ou não fez a abertura desse alias em memória. 

Esse problema não me parece ter a ver com o debug em si.
