### ISSUE TITLE
Alerta do Symantec Antvirus 

### ISSUE THREAD

**Issue by renatocunha** [totvs/advpl-vscode#80]
O antvirus Symantec está identificando o plugin como um virus
![mensagem_antvirus](https://cloud.githubusercontent.com/assets/5938391/24407507/7f93d696-13a1-11e7-974e-ca2814385da4.JPG)

**Comment by killerall** [comment]
Ola Renato,

Eu abri um chamado uma vez na Symantec, e eles colocaram na white list.
Porem cada vez que atualizo o vscode, o chksum do arquivo muda.

Quando deixar uma versão estavel, vou refazer o processo la.

Por hora recomendo você trocar pelo Sophos...
