### ISSUE TITLE
Depuração de Objetos JsonObject

### ISSUE THREAD

**Issue by izacsc** [totvs/advpl-vscode#86]
A classe JsonObject é nova:
http://tdn.totvs.com/display/tec/Classe+JsonObject

o código abaixo funciona corretamente, porém não é possível inspecionar a variável work corretamente durante o debug. O mouse hover apresenta "J" ( talvez pelo tipo retornado pelo Valtype da variável).

A sintaxe wrk['Fabrica'] no debug console também não é aceita.

```

#include "protheus.ch"
 
user function tstJsonObject()
    local wrk
    wrk := JsonObject():new()
    wrk['FABRICA']  := 'Wemagete' //cria automaticamente uma propriedade de nome FABRICA
    wrk['NOME']     := 'Fissori' //cria automaticamente uma propriedade de nome NOME
     
    Conout(wrk['FABRICA'])
    Conout(wrk:nome) 
    FreeObj(wrk)
return

```

Qualquer problema pra reproduzir me avisa

Abraço

**Comment by izacsc** [comment]
Na verdade a sintaxe wrk['FABRICA'] funciona sim, mas só é possível trocando as aspas simples por duplas.

**Comment by killerall** [comment]
@izacsc 
Consegue ver se já foi resolvido esse cara?

**Comment by izacsc** [comment]
Não foi não. Ao passar o mouse sobre um objeto Json visualizamos o tipo "objeto" mas não é possível verificar as propriedades. Para isso é necessário saber o nome da propriedade e acessá-la ou serializar o objeto para verificar o conteúdo do mesmo.

**Comment by killerall** [comment]
@izacsc 
Você testou no Lobo Guara?

**Comment by izacsc** [comment]
Testei sim. Na verdade só testei nele.
